bkaradzic/bgfx

examples/common/entry/entry_ios.mm
examples/common/entry/entry_osx.mm
examples/runtime/iOS-Info.plist
makefile
scripts/example-common.lua
scripts/genie.lua

added ios/osx bundle resource loading
added info.plist for iOS Xcode examples
Xcode now uses only Universal target ( should use 'Standard' as it is default in Xcode projects - this will require modification of genie)

added separate ios/osx Xcode project generation

---

3rdparty/ib-compress/readbitstream.h
examples/common/font/font_manager.cpp
examples/common/nanovg/fontstash.h

Compile fixes for Apple GCC 4.2

---

scripts/bgfx.lua
scripts/example-common.lua

It is connected to work in : https://github.com/bkaradzic/bx/pull/48

Added support for building on VS2012/13 targeting XP

---

examples/common/entry/entry.h
examples/common/entry/entry_android.cpp
examples/common/entry/entry_asmjs.cpp
examples/common/entry/entry_ios.mm
examples/common/entry/entry_nacl.cpp
examples/common/entry/entry_osx.mm
examples/common/entry/entry_qnx.cpp
examples/common/entry/entry_sdl.cpp
examples/common/entry/entry_winrt.cpp
examples/common/entry/entry_x11.cpp

Implemented existing OSX window commands + added toggleFullscreen().

OS X candy.. :)

---

examples/common/imgui/imgui.cpp
src/renderer_gl.cpp

Error was :
error: 'Imgui::m_surfaceHeight' will be initialized after [-Werror=reorder]

Reorder warning fix

---

scripts/genie.lua
src/ovr.cpp
src/ovr.h

Tested against the following SDKs:
- 0.5.0-beta
- 0.4.4-beta
- 0.4.3-beta
- 0.4.2-beta
- 0.4.1-beta
- 0.4.0-beta

Support Oculus SDK versions through 0.5.0.1-beta

---

src/glcontext_nsgl.mm

`GlContext::create` was leaking autoreleased objects as it was invoking Cocoa with no `NSAutoreleasePool` in place.  This is fixed by adding a small class to hold an `NSAutoreleasePool` for the scope of the function.  Using a class makes it exception-safe, ensuring the `NSAutorleasePool` will be released however `GlContext::create` completes.
`NSOpenGLProfileVersionLegacy` attribute is required for OpenGL 2 applications on 10.7 "Lion" and later to enable OpenGL features deprecated in OpenGL 3.  However, 10.5 "Leopard" and 10.6 "Snow Leopard only support OpenGL 2.1, so this is not necessary on these platforms.  OpenGL 2.1 is detected and used correctly when built on 10.6 "Snow Leopard" (I don't have a 10.5 "Leopard" machine readily available for testing).
I've tested that this builds and …

Fix leaks, support OS X 10.6

---

src/ovr.cpp
src/renderer_d3d11.cpp

I have a few minor tweaks to Oculus support you may be interested in.

Minor Oculus changes

---

src/glcontext_egl.cpp

This is a much much cleaner pull request, thanks for your patient. :-)

Add GLSurfaceView / external EGLContext support on Android

---

src/renderer_gl.cpp

This addresses https://github.com/bkaradzic/bgfx/issues/382

Fix color texture format detection for webgl and gles < 3.0

---

src/renderer_d3d11.cpp

Enable by setting BGFX_D3D11_MAP_CONSTANT_BUFFERS to 1
(XB1) Drops GPU Busy % on spiral from 65% to 20%
(PC) Drops bgfx::d3d11::RendererContextD3D11::commitShaderConstants
CPU usage by 95% (11.21%->0.66%)
(PC) Overall decreases bgfx::d3d11::RenderContextD3D11::submit CPU
usage by another 34% (27.18%->17.90%)
Fixes the blitter crash in #389 (Github won't map this commit to the original pr)
Drawstress timings (Win7 x64 + i7-5820k + GTX 970)
BGFX_D3D11_MAP_CONSTANT_BUFFERS=0 - 110592 draw calls @ 16ms
BGFX_D3D11_MAP_CONSTANT_BUFFERS=1 - 117649 draw calls @ 16ms

Map/Unmap constant buffers instead of using UpdateSubResource

---

src/renderer_d3d11.cpp

Fixing display bug when using flip-sequential swap effect.

---

src/glcontext_eagl.mm

needed for issue #227
implementation is from glcontext_nsgl modified for iOS.

added iOS GL extension function import

---

examples/09-hdr/hdr.cpp
examples/11-fontsdf/fontsdf.cpp
examples/12-lod/lod.cpp
examples/13-stencil/stencil.cpp
examples/14-shadowvolumes/shadowvolumes.cpp
examples/16-shadowmaps/shadowmaps.cpp
examples/17-drawstress/drawstress.cpp
examples/18-ibl/ibl.cpp
examples/19-oit/oit.cpp
examples/21-deferred/deferred.cpp
examples/24-nbody/nbody.cpp
examples/common/imgui/imgui.cpp
examples/common/imgui/ocornut_imgui.cpp
examples/common/imgui/ocornut_imgui.h

ocornut-imgui integrations: mouse wheel, render callbacks, keyboard

---

tools/shaderc/shaderc.cpp

I think I did this right (made a branch with just this commit added to it). Did you want to pull any other commits besides this one?

adding better error message for missing varying.def.sc in shaderc

---

src/renderer_gl.cpp

Revert "Fix crash on some OpenGLES devices"

---

src/vertexdecl.cpp

Had two problems: 1# Bit field didn't got updated for Uint10. 2# Shifting by 8 on uint8_t. Problem was introduced on: 8da579ff99a62318682f1e913f5e0d9f6b8f8b2c.

Fixing encodeAsInt field. 

---

examples/common/imgui/imgui.cpp

affects all examples using imgui

fixed segfault in imgui with default allocator

---

src/renderer_d3d11.cpp
src/shader_dxbc.cpp

For your review, changes we needed to make locally to ship on Windows Phone/RT, plus one pull request for BX.

Changes needed for WinRT

---

scripts/bgfx.lua

Since I am working on a custom genie action called "xcode7", this serve my purpose

add support for custom xcode actions for bgfx.lua

---

3rdparty/dxsdk/include/dxgitype.h

newer have DXGI_* already defined

this makes patch work on all mingw versions

---

examples/common/aviwriter.h

See comments in the individual commits. :)

AVI writer fixes

---

src/renderer_mtl.mm

Fixes uniform constant overwrites across frames while a render consuming them is still in flight.

Metal: Added triple buffering of uniform buffers.

---

examples/15-shadowmaps-simple/shadowmaps_simple.cpp

Note this change depends on a related PR in bx repo

shadowmaps_simple: fix OGL shadow camera volume

---

src/glcontext_eagl.h
src/glcontext_eagl.mm
src/renderer_gl.cpp

Reverts bkaradzic/bgfx#716 <- it breaks GL framebuffers.

Revert "iOS SwapChain support"

---

README.md
examples/01-cubes/cubes.cpp
examples/02-metaballs/metaballs.cpp
examples/04-mesh/mesh.cpp
examples/05-instancing/instancing.cpp
examples/06-bump/bump.cpp
examples/12-lod/lod.cpp
examples/24-nbody/nbody.cpp
examples/26-occlusion/occlusion.cpp
include/bgfx/bgfx.h
scripts/genie.lua
src/ovr.cpp
src/ovr.h
src/renderer_d3d11.cpp
src/renderer_gl.cpp

This pull request updates current Oculus Rift implemenation from SDK 0.5 to 1.3. Support for any SDK's prior to 1.3 has been completely dropped.

OculusVR: updated to SDK 1.3

---

examples/18-ibl/fs_ibl_mesh.sc
examples/18-ibl/ibl.cpp

@bkaradzic: shaders need to be recompiled/updated for all backends.

18-ibl fixes.

---

src/bgfx_p.h

ensure buffer is 16-byte aligned

---

src/renderer_mtl.mm

Sorry about the whitespace changes, my editor went crazy trying to fixing it.

Fixed implicit cast errors in Metal when strictly compiling C++

---

src/renderer_mtl.h
src/renderer_mtl.mm

- iOS9 fixes
- removing cpu/gpu syncs (wip)

metal backend

---

examples/common/entry/entry.cpp
examples/common/entry/entry_android.cpp

Correcting and simplifying emulated mouse events from touch events.
Correcting a bug in entry too, mouse click were not updating mouse position (issue not visible on Windows, but visible on android, as the mouse move event is not triggered by the system if the user clicks without moving).

Bugfix mouse click position

---

src/renderer_mtl.mm

m_saveScreenshot must be enabled before calling rendercontext::submit() to be able to save the shot. This could be done in a SaveScreenshot 'Pre' command as we already discussed.

metal save screenshot

---

src/renderer_mtl.h
src/renderer_mtl.mm

added cpu/gpu timer
fixed handling iOS device orientation change
fixed BGFX_DEBUG_IFH rendering
acquire drawable just before needed
added sampler comparison where available

metal fixes

---

examples/18-ibl/fs_ibl_mesh.sc
examples/18-ibl/vs_ibl_skybox.sc

The .bin output of shaderc for these shaders will need to be rebuilt by someone whose `make` will work correctly for it :)

Fix issues with example 18-ibl's shaders.

---

src/glcontext_nsgl.mm

Mainly this is a compatibility fix for GLFW, but it would apply to any custom window implementation that sets a contentView prior to initialization.

Don't clobber existing contentView if one exists.

---

src/renderer_mtl.mm

fixes crash due to unbalanced reference count

unbalanced retain / release

---

include/bgfx/c99/bgfx.h

getUniformInfo exposed to c99 API

expose getUniformInfo to c99 API

---

examples/common/entry/entry_osx.mm
src/renderer_mtl.h
src/renderer_mtl.mm

osx meamleak fix
refactored commandqueue handling to be somewhat similar to d3d12
removed slow cb sync in buffer update

metal fixes, optim

---

3rdparty/glsl-optimizer/src/glsl/glsl_optimizer.cpp
src/renderer_gl.cpp

This is a pre-merge of a PR I put in for glsl-optimizer as the project appears to be much less active than bgfx. [Original](https://github.com/aras-p/glsl-optimizer/pull/137)

Support for high precision Metal texture samplers.

---

examples/common/image.cpp
src/renderer_gl.cpp

https://github.com/nothings/stb/issues/434

Don't force stb image loader to use RGBA8.

---

examples/common/nanovg/fontstash.h
examples/common/nanovg/nanovg.cpp
examples/common/nanovg/nanovg.h

This commit pulls more changes that was not included in #1088.

Updates NanoVG to the latest commit.

---

src/renderer_mtl.mm

fixes https://github.com/bkaradzic/bgfx/issues/995

metal - texture array creation bug fix

---

examples/common/nanovg/nanovg_bgfx.cpp
src/renderer_mtl.mm

Fixes bugs found in #1139, though not actually solved the issue.

Fixes texture format for NanoVG framebuffer.

---

src/renderer_mtl.mm

maybe some cleanup would be needed to use bgfx::isValid, but at least it compiles

fixed compilation of metal renderer with new constant style

---

examples/12-lod/lod.cpp
examples/21-deferred/deferred.cpp
examples/33-pom/pom.cpp

With SetWindowPos there was a strange when the user tried to grab the window. This is fixed with SetNextWindowPos.

fixed imgui window position

---

examples/13-stencil/stencil.cpp

working on issue #1143
That was harder than I expected. Converted it twice. Geom is black both times. 
I found that it is because of this line: https://github.com/bkaradzic/bgfx/blob/525af7685ea65ef9f6cafaf563ffbfb063c9df37/examples/common/entry/entry.cpp#L402
This caused that s_uniforms.submitConstUniforms(); did nothing in init. I moved it into update.

stencil example to entry::AppI

---

examples/23-vectordisplay/main.cpp
examples/23-vectordisplay/vectordisplay.cpp
examples/23-vectordisplay/vectordisplay.h

notes:
I guess this should use caps
https://github.com/bkaradzic/bgfx/compare/master...attilaz:vector-display-entry?expand=1#diff-ed4b14a229c78d51d7e9fcd084595f46R47
https://github.com/bkaradzic/bgfx/compare/master...attilaz:vector-display-entry?expand=1#diff-5eab9a17ff9bcce324fa46910221cf3aR53
I needed a contructor with no parameter, I set parameters in init.

Vector Display to entry::AppI

---

examples/16-shadowmaps/shadowmaps.cpp

I replaced imguiChoose with ImGui::RadioButtons which has a similar look. Could use listbox or combobox.
I removed imguiEnum functions and implemented them in-place. 
ImGui has an int slider so I removed m_numSplitsf and simply using an int variable instead of two (m_numSplitsf and m_numSplits)
I see no easy way to implement step for SliderFloat. I haven't removed step parameter from ShadowMapSettings though. Could be removed if you don't know a way to implement them, or don't want to.
For sizePwrTo I implemented 1.0f step like this: https://github.com/bkaradzic/bgfx/compare/master...attilaz:shadowmaps-imgui?expand=1#diff-131882cabf675c74c1b19e89f19a284bR2096
Quite ugly but it seem to be working.
Could use int parameter instead of float in ShadowMapSettings. Or store float to int, …

16-shadowmaps: Switched to ImGui

---

3rdparty/ocornut-imgui/imgui_user.h
3rdparty/ocornut-imgui/imgui_user.inl
3rdparty/ocornut-imgui/widgets/color_wheel.h
3rdparty/ocornut-imgui/widgets/color_wheel.inl
examples/28-wireframe/wireframe.cpp

also contains the port of colorwheel to ImGui.
Dear ImGui's renderer doesn't seem to be supporting every nanovg features( gradient fills, fill holes, ) so I had to be creative. I didn't find any major differences.

28-wireframe: switched to imgui

---

examples/18-ibl/ibl.cpp

There is a missing component: https://github.com/bkaradzic/bgfx/compare/master...attilaz:18-ibl-imgui?expand=1#diff-acecace6801ee69d8bdbeb60c77ad7bcR622
Could you implement it?
I haven't implemented imguiTabs instead I use a simple button with a wrapper(https://github.com/bkaradzic/bgfx/compare/master...attilaz:18-ibl-imgui?expand=1#diff-acecace6801ee69d8bdbeb60c77ad7bcR483). Not sure if this is ok.
And I found an error in conversion: I left this in the source (https://github.com/bkaradzic/bgfx/compare/master...attilaz:18-ibl-imgui?expand=1#diff-acecace6801ee69d8bdbeb60c77ad7bcR690)
Sorry about that. 
This requires colorwheel (from previous PR).

18-ibl: switched to imgui

---

examples/16-shadowmaps/shadowmaps.cpp

16-shadowmaps fixed when used with combined examples

---

examples/common/entry/entry_sdl.cpp

SDL_GameControllerAddMapping needs zero-terminated string

---

scripts/bgfx.lua

I have a bgfx setup which includes some additional C exports.
In order to keep it synced with BGFX I want to reuse the original lua scripts, and I need the bgfx project definition to be customizable externaly.
This little change would make my life a lot easier, please accept :)

Small change in bgfx.lua for more flexibility

---

src/bgfx.cpp
src/renderer_d3d11.cpp
src/renderer_d3d12.cpp
src/renderer_d3d9.cpp
src/renderer_d3d9.h
src/renderer_vk.cpp

Add BX_FALLTHROUGH to avoid -Wimplicit-fallthrough false positives

---

examples/common/entry/entry_noop.cpp

My linker is complaining otherwise

 add missing return statement

---

scripts/bgfx.lua
scripts/bgfx.natvis

Not sure if tools\ is the right place for it, feel free to move it.

Added bgfx.natvis.

---

src/renderer_d3d11.cpp
src/renderer_d3d12.cpp

Semi-common character in URLs...

Fix bgfx::setName to not choke on '%'

---

src/renderer_d3d11.cpp
src/renderer_gl.cpp

Minor fixes for BGFX_CONFIG_USE_OVR code that had gotten out of sync.

fix ovr compile errors

---

src/renderer_gl.cpp

Part of some changes we had in place. This adds compatibility for some older ATI drivers.

Compatibility with old ATI drivers

---

src/bgfx.cpp

bugfix: use c99 adapter

---

examples/common/entry/entry_ios.mm
src/renderer_mtl.mm

These are fixes for https://github.com/bkaradzic/bgfx/issues/1568
I have also removed currentDrawable() as it is not used anymore.

iOS metal fixes

---

tools/shaderc/shaderc_glsl.cpp

metal texture uniform var are passed from xlatMtlMain as parameters. they are something like this:
```
fragment xlatMtlShaderOutput xlatMtlMain (xlatMtlShaderInput _mtl_i [[stage_in]], constant xlatMtlShaderUniform& _mtl_u [[buffer(0)]]
,   texture2d<float> s_basecolor [[texture(0)]], sampler _mtlsmp_s_basecolor [[sampler(0)]]
,   texture2d<float> s_normal [[texture(1)]], sampler _mtlsmp_s_normal [[sampler(1)]])
```
So we need to parse this code to get the uniform var and save to bin file

fix metal shader lack of texutre uniform variable

---

src/renderer_mtl.h
src/renderer_mtl.mm

It is less change than it seems:
- Processing shader parameters was put into 'processArguments' to be able to use with compute pipelines too. 
- In submit the clear part was indented (put inside an if) to handle draw/compute works but the diff seems to be clueless about this, and showing almost the whole submit as changed...
I have added BGFX_CAPS_COMPUTE and BGFX_CAPS_DRAW_INDIRECT, maybe you want to disable because examples that use these features without shaders doesn't work.
I have attached the compiled metal shaders. You can copy them to examples/runtime/shaders/metal to test 24-nbody and 37-gdr. They worked for me on macOS.
[metal-shaders.zip](https://github.com/bkaradzic/bgfx/files/2729824/metal-shaders.zip)

metal compute and drawindirect

---

examples/common/example-glue.cpp

examples now have an FPS histogram, min, max, avg

---

examples/common/entry/entry_osx.mm
src/bgfx.cpp
src/renderer_mtl.mm

Fix for https://github.com/bkaradzic/bgfx/issues/1607

Moved autoreleasepool into renderframe

---

scripts/shader.mk
scripts/shaderc.lua
src/bgfx_compute.sh
src/renderer_mtl.h
src/renderer_mtl.mm
tools/shaderc/shaderc.cpp
tools/shaderc/shaderc_spirv.cpp

24-nbody is working with generated shaders.

Metal compute shader generation using spirv-cross

---

src/renderer_mtl.mm

getMips cubemap fix

---

scripts/bgfx-idl.lua
scripts/bgfx.idl
scripts/codegen.lua
scripts/genie.lua
scripts/idl.lua

I add 
```lua
dofile "bgfx-idl.lua"
newaction {
trigger = "idl",
description = "Generate bgfx interface source code",
execute = doidl
}
```
into scripts/genie.lua , I'm not sure if it's the right place.
btw, bgfx.idl is separated from bgfx-idl.lua

Add idl code generator 

---

examples/common/entry/entry_osx.mm
src/renderer_mtl.h
src/renderer_mtl.mm

Also fixes the rare case when nextDrawable returns nil. It happens on iOS 10 when app is running, the phone goes to sleep and user presses button to wake the phone. 
And some memleak and out of bounds index problem.

Osx multiple window support fixes

---

tools/shaderc/shaderc_spirv.cpp

ShaderC now emits sampler uniforms for Metal and Spirv (Issue discussed in #1689)
Some notes:
- I have only tested on Metal, not spirv
- It feels a little fragile to me to be grabbing names of textures, and cutting off the 'Texture' part to get the name of the uniform. This is what the metal code path did, but I don't know if this is also valid for spirv.

shaderc_spirv now emitting sampler uniforms

---

src/renderer_gl.cpp

Fix GL texture array

---

3rdparty/glslang/glslang/Include/Common.h

See  https://github.com/bkaradzic/bgfx/issues/1733  and  https://github.com/bkaradzic/bgfx/commit/148e03255fd0198e274fff441f33820993031a83#diff-fd8d82dcea2b0a978ea4cfc2472faf98

Fix MinGW build

---

examples/common/entry/entry_osx.mm

- exit fix
- using native fullscreen support instead of borderless window

OSX entry changes

---

src/renderer_gl.cpp

Added command barrier bit when submitting with an indirect buffer - this fixes the flickering on tess-41

command sync

---

examples/common/entry/dialog.cpp

caught this while trying to use local compile of geometryv.

fix dialog null terminator

---

src/renderer_mtl.mm

https://github.com/bkaradzic/bgfx/issues/1833#issuecomment-516038640

fixing readTexture for discrete gpu

---

tools/shaderc/shaderc.cpp
tools/shaderc/shaderc_metal.cpp

More info:
https://github.com/KhronosGroup/SPIRV-Cross/pull/1036
https://github.com/KhronosGroup/SPIRV-Cross/issues/1072

Metal: Fix resource binding for latest spirv-cross

---

src/renderer_vk.cpp

I have tested with imgui combobox.

Vulkan: scissor extent fixed.

---

src/renderer_vk.cpp

Hello! This is the 7th PR of my Vulkan backend implementation (#274)
- swapchain creation and release codes are refactored as a function, and `init()` and `shutdown()` uses these functions.
- during `updateResolution()`, swapchain is recreated.
- now resizing a window can be done!
- Multiple swapchain creation is not yet implemented.
- I've test resizing on:
* windows 10 (amd ryzen + rtx2070)
* linux (ubuntu, amd ryzen + rtx2070)
* macbook pro (el capitan, retina 15", mid 2014)
Thank you!

vulkan backend implementation 7: refactor swapchain

---

examples/common/shaderlib.sh

It is useful to transform normals.

added cofactor function to shaderlib.sh

---

3rdparty/dear-imgui/widgets/dock.inl

dear-imgui: avoid potentially uninitialized warning

---

README.md

readme: add openblack to projects using bgfx

---

src/bgfx_shader.sh

Fixes #1933  concerns. Second PR for gh-pages branch will come soon!

Macro based shader helper functions for constructing matrices in shaders.

---

tools/geometryv/geometryv.cpp

max camera distance depends on loaded mesh size

geometryv: added attrib/radius info and show 3d axes option

---

scripts/genie.lua

Moved some options from the toolchain to the bgfx examples projects
Associated PR in bx: https://github.com/bkaradzic/bx/pull/228

Moved Emscripten options from toolchain

---

src/renderer_mtl.mm

Fix for https://github.com/bkaradzic/bgfx/issues/1773

always calling UI API on main thread

---

src/glcontext_glx.cpp

Previously, the code checked for an extension by checking if the pointer returned from
glXGetProcAddress was NULL or not.
But in truth, you can get a non-NULL pointer even if that extension is not supported.
Now, we parse the glXQueryExtensionsString() results.
GLFW code that does similar checks, for reference: https://github.com/glfw/glfw/blob/51bb76c7c3de934b2dd3affcdc297a32e4817835/src/glx_context.c#L208
fixes #1367

Check for GLX vblank extensions more properly.

---

examples/16-shadowmaps/shadowmaps.cpp

The `16-shadowmaps` example contained some old duplicated and outdated mesh loading code.
This cleans it up to use the same code as the other examples.

Remove duplicate outdated mesh loading code in 16-shadowmaps

---

src/renderer_d3d12.cpp

1. D3D12's swapchain doesn't accpet sRGB format. We need to use the linear format as m_scd.format.
2. Fill a rtvDesc for creating a RTV, respect to BGFX_RESET_SRGB_BACKBUFFER flag.
3. Choose SRV's color format base on BGFX_RESET_SRGB_BACKBUFFER flag.

Fix the sRGB support in D3D12 renderer

---

bindings/cs/bgfx.cs
bindings/d/funcs.d
bindings/d/types.d
examples/41-tess/tess.cpp
examples/common/bgfx_utils.cpp
include/bgfx/bgfx.h
include/bgfx/c99/bgfx.h
include/bgfx/defines.h
scripts/bgfx.idl
src/bgfx.cpp
src/bgfx.idl.inl
src/bgfx_p.h

As promised, here is the PR for discard flags in submit @cloudwu

Submit discard flags

---

src/renderer_vk.cpp

This PR fixes a few validation errors I was getting with the Vulkan backend, mostly related to blitting where the size was UINT16_MAX and `vkCmdBlitImage` expects correct ranges not exceeding the actual texture size.
It also updates the validation layer to the new non-deprecated one. This requires SDK 1.1.106.0 or later (released in April 2019). Main reason for that is that the deprecated layer will be removed in the next SDK:
(quote from somebody involved with LunarG)

Vulkan: fix validation errors, switch to new validation layers

---

src/renderer_vk.cpp

Vulkan: fall back to deprecated validation layers if necessary

---

src/renderer_vk.cpp

This PR should fix #2071 (see discussion for more info) and #1950 (validation layers are completely disabled if they're not found).

Fix #2071, #1950

---

src/glcontext_html5.cpp

Create WebGL 2 context if available. Work around Chrome performance bug https://bugs.chromium.org/p/chromium/issues/detail?id=1045643

Create WebGL 2 context if available

---

src/renderer_vk.cpp

Better support for enabling and disabling vulkan instance layers and instance extensions and vulkan device layers and device extensions.

Reworked vulkan layers and extensions support

---

src/renderer.h

Needs https://github.com/bkaradzic/bx/pull/239

Micro-pptimize hot matrix maths in renderer draw call submission

---

src/renderer_d3d12.cpp

Cleanup dead code in D3D12 renderer

Cleanup dead code

---

examples/42-bunnylod/progmesh.c

@dougbinks, @cloudwu 
Please review...

Updated license text.

---

examples/common/entry/entry_html5.cpp
src/glcontext_egl.cpp
src/glcontext_html5.cpp
src/renderer_gl.cpp

Add checks for Emscripten API return values to make sure API calls are not failing.

Add checks for Emscripten API return values

---

CONTRIBUTING.md

Update chat link from gitter to discord in CONTRIBUTING.md

Update chat link from gitter to discord.

---

3rdparty/sdf/sdf.h
examples/common/font/font_manager.cpp

Update sdf from https://github.com/memononen/SDF

update sdf see #2193

---

src/dxgi.cpp

Add support for https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.swapchainpanel?view=winrt-19041 .

Add SwapChainPanel support

---

src/dxgi.cpp

Fix https://github.com/bkaradzic/bgfx/pull/2215#issuecomment-663915931

Fix reference release

---

src/renderer_d3d12.cpp
src/renderer_d3d12.h
src/renderer_vk.cpp
src/renderer_vk.h

This is a list of features I've been working for the past days.
- `[VK/DX12] Fix setScissor behavior` fixes #2240
- `[VK] Add Screenshot feature` fixes #2228
All the others just add missing features I was requiring personally to work for FFNx :)
Feel free to suggest any changes if you see anything that could be improved.
Cheers!

Various Vulkan/Direct3D 12 enhancements

---

src/renderer_vk.cpp

This PR adds texture readback to the Vulkan renderer. I also removed the blit path from the screenshot code which was overkill since we know if the format needs to be swizzled or not (and the old code always swizzled anyway which was a potential bug).
@julianxhokaxhiu If you have a minute to test the screenshot code, I'd appreciate it. You initially added it, and I just want to be sure it doesn't indirectly break anything with the MSAA stuff you added.

Vulkan: Add texture readback

---

bindings/bf/bgfx.bf
scripts/bindings-bf.lua
scripts/genie.lua

IDL bindings for Beef Programming Language (https://www.beeflang.org/).

IDL Beef bindings

---

tools/shaderc/shaderc.cpp

An oversight from my previous PR

Add missing preprocessor macro for ESSL

---

src/shader_dxbc.cpp
src/shader_dxbc.h

Copy RDEF and STATS chunks when patching the shader code.

Added support for Resource Definition and Stats in DXBC

---

src/shader_dxbc.cpp

fix uint32 for none windows env

---

makefile

Minimal changes to support building Apple silicon

Add support for building Apple silicon

---

examples/43-denoise/fs_denoise_txaa.sc
examples/xx-bokeh/bokeh.cpp
examples/xx-bokeh/bokeh_dof.sh
examples/xx-bokeh/fs_bokeh_copy.sc
examples/xx-bokeh/fs_bokeh_dof_combine.sc
examples/xx-bokeh/fs_bokeh_dof_debug.sc
examples/xx-bokeh/fs_bokeh_dof_downsample.sc
examples/xx-bokeh/fs_bokeh_dof_second_pass.sc
examples/xx-bokeh/fs_bokeh_dof_single_pass.sc
examples/xx-bokeh/fs_bokeh_forward.sc
examples/xx-bokeh/fs_bokeh_forward_grid.sc
examples/xx-bokeh/fs_bokeh_linear_depth.sc
examples/xx-bokeh/makefile
examples/xx-bokeh/parameters.sh
examples/xx-bokeh/varying.def.sc
examples/xx-bokeh/vs_bokeh_forward.sc
examples/xx-bokeh/vs_bokeh_screenquad.sc

https://github.com/bkaradzic/bgfx/issues/1674
implemented bokeh dof in a single pass as described in https://blog.tuxedolabs.com/2018/05/04/bokeh-depth-of-field-in-single-pass.html
including optimizations discussed in closing paragraph
...
remember thinking that dof effect looked really nice and always wanted to get around to implementing it...
...
also includes a one line change to fix typo in shader from denoise example

bokeh depth of field

---

tools/shaderc/shaderc_spirv.cpp

This addresses https://github.com/bkaradzic/bgfx/issues/2428 - removing obsolete branch point.

[shaderc] [spirv] Remove obsolete branch point.

---

src/bgfx_p.h

Minor addition to https://github.com/bkaradzic/bgfx/pull/2439.
- check that attachment sample counts match
- calculate correct 3D texture layer count

Additional framebuffer validation

---

src/renderer_webgpu.cpp
src/renderer_webgpu.h

WebGPU/Dawn just slipped a new change right after the previous PR, so we update to that as well

WebGPU: Update to latest Attachments changes

---

include/bgfx/embedded_shader.h

Here's part 2 of the embedded shaders change (part 1: #2535).

Split embedded shaders into essl and glsl - Part 2

---

src/renderer_mtl.h
src/renderer_mtl.mm

I have no idea why this fixes https://github.com/bkaradzic/bgfx/issues/1867 
I'm not a metal expert so take this with pull request with a grain of salt. Maybe @attilaz has a better alternative to this?

Weird fix for frame rate doubling after second created window.

---

examples/common/entry/dialog_darwin.mm

Fix this issue: https://github.com/bkaradzic/bgfx/issues/2588

Fix deadlock on MacOS

---

scripts/bgfx.idl

Make sure to end the enums with `()` which was inconsistent before.

Cleanup bgfx.idl

---

src/renderer_vk.cpp

Aknowledging that needResolve and needMipGen are mutually exclusive.

Simplify vulkan texture resolve

---

src/renderer_vk.cpp

This addresses a subtle bug when the sequence of blit operations contains 2 consecutive copies like so:
A -> B,  C -> A  (src of a blit becomes dst of next blit)
A -> B,  B -> C  (dst of a blit becomes src of next blit)
A -> B,  B -> A  (dst and src of blit are swapped in the next one)
The last case is necessary to implement blitting part of an image (A) into itself (using B as intermediate). The code as currently written triggers a validation error because B is transitioned back to its original layout (instead of staying src layout) in the second blit.

Fix layout transition when cur and prev blit ops share the same images

---

3rdparty/dxsdk/include/d3d11.h
3rdparty/dxsdk/include/d3d11_1.h
3rdparty/dxsdk/include/d3d11_2.h
3rdparty/dxsdk/include/d3d11_3.h
3rdparty/dxsdk/include/d3d11_4.h
3rdparty/dxsdk/include/d3d11sdklayers.h
3rdparty/dxsdk/include/d3d11shadertracing.h
3rdparty/dxsdk/include/d3d12.h
3rdparty/dxsdk/include/d3d12_1.h
3rdparty/dxsdk/include/d3d12sdklayers.h
3rdparty/dxsdk/include/d3d12video.h
3rdparty/dxsdk/include/d3dcommon.h
3rdparty/dxsdk/include/dxgi.h
3rdparty/dxsdk/include/dxgi1_2.h
3rdparty/dxsdk/include/dxgi1_3.h
3rdparty/dxsdk/include/dxgi1_4.h
3rdparty/dxsdk/include/dxgi1_5.h
3rdparty/dxsdk/include/dxgi1_6.h
3rdparty/dxsdk/include/dxgidebug.h
3rdparty/dxsdk/include/dxva2api.h

mingw minimum version required is 475

rpcndr version using 475

---

src/renderer_gl.cpp
tools/shaderc/shaderc.cpp

shaderc_glsl.cpp does some patching already in gles 3 (before submitting the code to glsl_optimizer which complains otherwise).

Check if gl_Frag[Data/Color] are not already patched

---

examples/common/font/font_manager.cpp

Fix alloc-dealloc-mismatch (operator new [] vs operator delete

Fix bad delete in font_manager.cpp

---

src/glcontext_nsgl.mm

[glContext update]; and [glContext setView:glView]; always needs to be called from main thread

Fix crash from context setView and context update not being called from main thread in glcontext_nsgl.mm

---

scripts/bindings-d.lua

Uhh dunno why this was wrong but I fixed for ya :)

Fixed uint8_t being bound to byte instead of ubyte

---

scripts/bgfx.idl
scripts/codegen.lua

Couldn't find most of the things I wanted to change, but this should be sufficient for now

Minor rewording & increase of clarity

---

src/glimports.h
src/renderer_gl.cpp

Note: I'm using (g_caps.limits.maxFBAttachments > 0) as a test that MRT is available.

Import glDrawBuffers() from WEBGL_draw_buffers extension

---

bindings/zig/bgfx.zig
scripts/bindings-zig.lua
scripts/genie.lua

Added bindings generation for zig language.

Added zig bindings generation

---

tools/shaderc/shaderc.cpp

I added support to the shader compiler to output to stdout as well as I find it useful for piping and I use it to enable quick iteration while developing shaders.
I assume this might be useful to others as well.

Shaderc console out

---

src/renderer_mtl.h
src/renderer_mtl.mm

I think this fix is related to this PR:
https://github.com/bkaradzic/bgfx/pull/2119
It did not change metal renderer.

fix metal renderer set image bug

---

src/renderer_mtl.mm

It relate to this PR:
https://github.com/bkaradzic/bgfx/pull/2783

Metal merge texture format

---

examples/13-stencil/stencil.cpp
examples/14-shadowvolumes/shadowvolumes.cpp

Fix #2824, gcc 12.1 build issues

---

examples/07-callback/callback.cpp

Fixes the first problem in #2824

Update callback.cpp (fixes first part of #2824)

---

src/dxgi.cpp
src/renderer_d3d11.cpp

- Use ResizeBuffers for WinRT
- Set maximum frame latency for WinRT

Fixes when running in WinRT

---

README.md

Added a presentation of HARFANG 3D to the readme file, with still images, YT link and a rather comprehensive description of what the framework is about.

Added a presentation of HARFANG 3D.

---

examples/09-hdr/fs_hdr_bright.sc
examples/09-hdr/fs_hdr_tonemap.sc

Fix typo in source

---

src/renderer_d3d11.cpp
src/renderer_d3d12.cpp

Revert "Resolve texture format correctly on D3D11/D3D12"

---

src/renderer_mtl.mm

The swizzle wasn't properly changed in #2878

metal: Fix BGR to RGB swizzle

---

tools/geometryv/geometryv.cpp

bx::kFloatMin to bx:kFloatSmallest

---

examples/48-drawindirect/drawindirect.cpp

AppVeyor was complaining about a uint32 expression for a uint16 argument

Fix vs build

---

.github/workflows/main.yml

See https://docs.github.com/en/actions/using-jobs/using-concurrency

CI: Cancel any in-progress job or run

---

examples/assets/textures/textures.ninja
scripts/build.ninja

Pretty much what it says on the tin

Add astc to ninja scripts

---

src/renderer_vk.cpp

Described here: [https://stackoverflow.com/a/72791361](https://stackoverflow.com/a/72791361)

Fixed MoltenVK on Mac to reflect new requirements

---

examples/common/entry/dialog.cpp

the save file dialog in windows was an open file dialog, by mistake

fix for save file dialog in windows

---

examples/common/entry/entry_ios.mm

When initWithFrame is being called s_ctx has not been created yet. Fix with correct assign order.

fix ios entry

---

tools/shaderc/shaderc_hlsl.cpp

Revert "fix unused uniforms replace"

---

bindings/d/package.d
scripts/bindings-d.lua

I was looking through the bindings and realised that I formatted the comments weirdly for a couple of cases. While fixing that, I also noticed a couple of oversights in my re-casing, so I fixed those as well. :)

D bindings: Comment reformat, couple of oversights fixed

---

bindings/d/package.d
scripts/bgfx.idl
scripts/bindings-d.lua

Hopefully it's all good now :sweat_smile:

D bindings: deterministic sub-struct order

---

bindings/bf/bgfx.bf
bindings/cs/bgfx.cs
bindings/d/package.d
bindings/zig/bgfx.zig
scripts/bgfx.idl

Fixes IDL/Bindings for other languages having crashes due to changes to PlatformData struct.
I'm not sure I did it right but it seems right from the code I see!

Fix Native Window Type IDL/Bindings;

---

bindings/d/package.d
scripts/bindings-d.lua

A pretty stupid oversight that I didn't catch in my tests. :woman_facepalming:

D bindings: Fix error in dynamic version

---

README.md

Added our game WARCANA to readme.md

Added WARCANA to Readme.md

---

README.md

Accidentally pushed an older draft of the description for Tomb4Plus. This corrects the description to the intended version.

Corrected Tomb4Plus description.

---

src/renderer_vk.cpp

Here is the work I did when investigating frame stutter. I thought I'd contribute it upstream if you are interested. Gives good view of where the time is spent. Will be interesting to see the change once the NVIDIA explicit sync stuff is fully rolled out.

More vulkan profiling.

---

src/bgfx.cpp

Revert "Fix: Fix Uniform buffer doing too many iterations when updating renderer uniforms"

---

scripts/bgfx.doxygen

Update config for Doxygen 

---

docs/overview.rst

docs: Fix supported Android version

---

examples/18-ibl/ibl.cpp

18-ibl: Fix widgets id conflict
