bkaradzic/bgfx

- 3rdparty/khronos/gl/glext.h
When compile 32 bits version (osx-release32 or osx-debug32) fail with:
````
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: ../../osx32_clang/bin/libexample-commonDebug.a(entry_x11.o) has no symbols
==== Building bgfx (debug32) ====
Creating ../../osx32_clang/obj/x32/Debug/bgfx
glcontext_eagl.mm
glcontext_nsgl.mm
In file included from ../../../src/glcontext_nsgl.mm:9:
In file included from ../../../src/renderer_gl.h:39:
../../../3rdparty/khronos/gl/glext.h:468:19: fatal error: typedef redefinition with different types ('ptrdiff_t' (aka 'int') vs 'intptr_t' (aka 'long'))
typedef ptrdiff_t GLsizeiptr;
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/System/Library/Frameworks/OpenGL.frame …
```
> Trying fix osx 32bits

- scripts/bgfx.lua
- scripts/example-common.lua
- scripts/genie.lua
- scripts/geometryc.lua
- scripts/makedisttex.lua
- scripts/shaderc.lua
- scripts/texturec.lua
Using path.join instead of string concatenation makes the scripts more
OS-neutral. It also protects against missing or doubled "/" characters
in paths.
> bgfx genie scripts: use path.join to compose paths

- scripts/bgfx.lua
On Linux one would get the following error:
Linking bgfx-shared-lib
/usr/bin/ld: ../../linux64_gcc/obj/x64/Debug/bgfx-shared-lib/src/image.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
../../linux64_gcc/obj/x64/Debug/bgfx-shared-lib/src/image.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
as object files are compiled without the -fPIC flag. This commit fixes it.
> Linux: fixed building of shared libraries

- examples/25-c99/helloworld.c
The existing code is valid C99, however there only C99
specific feature used that is incompatible with the
MSVC C compiler is the relaxed variable declaration rules.
> Fix C99 example for MSVC toolchains

- src/renderer_d3d11.cpp
See remarks of:
https://msdn.microsoft.com/en-us/library/windows/desktop/ff476092(v=vs.85).aspx
Most PC drivers don't seem to enforce this, but it will
crash the xb1 implementation if fed an unaligned value.
> D3D11 constant buffer must align ByteWidth to 16 bytes

- src/renderer_d3d9.cpp
Fix for :
error: array index 1 is past the end of the array (which contains 1 element) [-Werror,-Warray-bounds]
m_samplerFlags[stage][1] = UINT32_MAX;
> Fix for array-bounds in renderer_d3d9.cpp 

- src/bgfx_p.h
For doing perf testing I wanted to see how many draw calls we could actually push, so I made some tweaks to allow the config to go above size of uint16_t.
> Allow the max draw call count to go above 65k.

- tools/shaderc/shaderc.cpp
- tools/shaderc/shaderc.h
- tools/shaderc/shaderc_hlsl.cpp
I'm not sure what you think of this implementation; it's pretty hacky, but it seems to do the job.
> Change shaderc to remove unused uniforms from DX11 shaders

- src/bgfx_shader.sh
- src/renderer_d3d11.cpp
- tools/shaderc/shaderc.cpp
This fixes a bunch of things required to get D3D11 working with downlevel hardware and adds proper caps detection.
> D3D11 downlevel hardware support

- src/renderer.h
- src/renderer_d3d11.cpp
The ViewState struct is so big that it blows out the stack on ARM devices. This change promotes it to a member variable.
> Fixing crash on WP8 ARM

- tools/shaderc/shaderc_hlsl.cpp
This GUID changes depending on what version of the DirectX SDK you have. The GUID is defined in d3d11shader.h as a const global, not a preprocessor macro, so this #ifndef was clobbering it always. This caused DX11 shader compliation to fail when using the Windows 8.1 SDK.
> Stop hardcoding the GUID for ID3D11ShaderReflection.

- src/renderer_d3d11.cpp
Fixes this error on VC12/x64:
renderer_d3d11.cpp(687, 0): error C4701: potentially uninitialized local variable 'adapter' used
I assume the check on 677 will cause a bailout before a null / uninitialized adapter pointer could ever be used?
> Fixes error C4701 in renderer_d3d11.cpp on VC12 build

- src/renderer_d3d11.cpp
When adding sRGB support for the backbuffer render target in D3D11,
the now explicitly specified RTV desc specifies a TEXTURE2D dimension.
For multisampled targets, this needs to be TEXTURE2DMS dimension.
This solves it by branching on the presence of MSAA in the reset flags but
could envisionably be obtained by looking at the desc of the backbuffer.
> Create backbuffer RTVs honoring multisampling

- src/renderer_d3d11.h
bgfx wasn't able to build, due to some duplicated typedef.
See a discussion on the webkit dev forums, on how to properly detect ming32-w64 [here](http://sourceforge.net/p/mingw-w64/discussion/723798/thread/ea355c1f/).
> fix building under mingw32-w64

- src/renderer_d3d11.cpp
(XB1) Drops GPU Busy % on spiral from 65% to 20%
(PC) Drops bgfx::d3d11::RendererContextD3D11::commitShaderConstants
CPU usage by 95% (11.21%->0.66%)
(PC) Overall decreases bgfx::d3d11::RenderContextD3D11::submit CPU
usage by another 34% (27.18%->17.90%)
> Map/Unmap constant buffers instead of using UpdateSubResource

- tools/geometryc/geometryc.cpp
Meshes exported from blender which do not contains texture coordinates were not converted properly.
I think there was a bug on "hasNormal" detection too.
OBJ file for reference (note the "//"):
```
o NoTexCoord
v -0.200000 0.000000 -1.000000
v -0.000000 0.000000 -1.000000
v 0.000000 0.000000 1.000000
v -0.200000 0.000000 1.000000
v -0.200000 0.500000 -1.000000
v -0.000000 0.500000 -1.000000
v 0.000000 0.500000 1.000000
v -0.200000 0.500000 1.000000
vn 0.000000 0.000000 -1.000000
vn 1.000000 0.000000 -0.000000
vn 0.000000 0.000000 1.000000
vn -1.000000 0.000000 0.000000
vn 0.000000 -1.000000 0.000000
vn 0.000000 1.000000 0.000000
s off
f 5//1 6//1 2//1 1//1
f 6//2 7//2 3//2 2//2
f 7//3 8//3 4//3 3//3
f 8//4 5//4 1//4 4//4
f 1//5 2//5 3//5 4//5
f 8//6 7//6 6//6 5//6
```
> Fixing geometryc for meshes exported without uv coordinates

- examples/01-cubes/cubes.cpp
- examples/02-metaballs/metaballs.cpp
- examples/04-mesh/mesh.cpp
- examples/05-instancing/instancing.cpp
- examples/06-bump/bump.cpp
- examples/10-font/font.cpp
- examples/11-fontsdf/fontsdf.cpp
- examples/12-lod/lod.cpp
- examples/14-shadowvolumes/shadowvolumes.cpp
- examples/24-nbody/nbody.cpp
- examples/common/imgui/imgui.cpp
- include/bgfx.c99.h
- include/bgfx.h
- include/bgfxdefines.h
- src/bgfx_p.h
- src/ovr.cpp
- src/ovr.h
- src/renderer_d3d11.cpp
- src/renderer_gl.cpp
BREAKING: bgfx::getHMD() now returns a valid pointer
if the VR runtime was initialized. This is different
from existing behavior where getHMD returned NULL until
a bgfx::reset(... BGFX_RESET_HMD) was issued. Applications
must now check HMD::flags for the current state of the VR
runtime. The following code has the code change required:
`const bgfx::HMD* hmd = bgfx::getHMD()
if (NULL != hmd)`
becomes:
`const bgfx::HMD* hmd = bgfx::getHMD()
if (NULL != hmd && 0 != (hmd->flags & BGFX_HMD_RENDRERING))
{
// rendering logic
}`
See the updated examples for details.
This allows applications to create the appropriately
sized back buffer for the HMD device by using the new device
resolution fields HMD::deviceHeight and HMD::deviceWidth.
These values report the pixel resolution of the attached
HMD …
> VR: Add device resolution to HMD. Init at startup.

- src/ovr.cpp
This prevents bleeding across the individual viewports
when the oculus SDK applies distortion mapping. The current
reccommended values are 100px for SDK <= 0.5 and 8px for > 0.5
See: http://static.oculus.com/sdk-downloads/documents/0.6.0/Oculus_Developer_Guide.pdf
in the "Bugs Fixed Since the Last Release" section.
For an example of this artifact, see the correct scene render:
followed by a scene that bleeds the left eye into the right eye:
> VR: Add buffer between left/right eye textures

- src/renderer_d3d11.cpp
- src/renderer_gl.cpp
Fixes #338
Create the swap chain without MSAA, and the eye textures
with MSAA. The core issue was using the surface description
for the backbuffer for the DSV on the eye textures which did
not match.
This meethod follows both the oculus and openvr guidance on MSAA -
MSAA is configured on the eye render targets, but not on the swap
chain.
> VR: Properly support MSAA in OVR builds

- src/ovr.cpp
- src/ovr.h
- src/renderer_d3d11.cpp
- src/renderer_gl.cpp
Bug fix for #419
Viewport calculations need to take VR eye buffer size into
account. Noticable at the older 100px boundary. Skewing still
exists at newer 8px buffer, but is harder to notice.
Eventually causes pretty bad eye strain, though.
Easily reproduced by setting the buffer to something obscenely
large, such as 2048.
> VR: Fix skewed viewports with buffered eye textures

- examples/common/imgui/ocornut_imgui.cpp
handle negative scissor inputs…
removed unnecessary vertex count calculation
> Fixes for ocornut-imgui integration

- 3rdparty/ocornut-imgui/imgui.cpp
- 3rdparty/ocornut-imgui/imgui.h
- examples/common/imgui/scintilla.cpp
Removed the need for getFontInfo(). Note: linegap is always 0 as that's what imgui does for paragraph (will add support for linegap later on. I found it was often zero)
> Scintilla/imgui: removed getFontInfo(), using data exposed by imgui

- src/glcontext_nsgl.mm
fix for https://github.com/bkaradzic/bgfx/issues/439
> Fix for Context not bound on OSX 10.10.3 #439

- examples/common/entry/entry_ios.mm
- src/glcontext_eagl.mm
When an iOS UIView is resized or rotated, the associated FBO and RBO needed to be recreated, otherwise the rendered output will be stretched uglily.
> Improved the handling of iOS UIView resize / rotate

- src/renderer_d3d9.cpp
If a framebuffer is created before bgfx::reset is handled, d3d9 device is not reset correctly and application crashes. 
Code to reproduce the crash:
```cpp
int _main_(int /*_argc*/, char** /*_argv*/)
{
HINSTANCE instance = (HINSTANCE)GetModuleHandle(NULL);
WNDCLASSEX wnd;
memset(&wnd, 0, sizeof(wnd));
wnd.cbSize = sizeof(wnd);
wnd.style = CS_HREDRAW | CS_VREDRAW;
wnd.lpfnWndProc = DefWindowProc;
wnd.hInstance = instance;
wnd.hIcon = nullptr;
wnd.hCursor = nullptr;
wnd.lpszClassName = "bgfxa";
wnd.hIconSm = nullptr;
RegisterClassExA(&wnd);
bgfx::init();
bgfx::reset(500, 500);
auto whandle = CreateWindowA("bgfxa"
, "BGFXa"
, WS_OVERLAPPEDWINDOW | WS_VISIBLE
, 0
, 0
, 400
, 400
, NULL
, NULL
, instance
, 0
);
bgfx::createFrameBuffer(whandle, 400, 400);
bgfx::frame();
bgfx::frame();
return 0; …
```
> d3d9 framebuffer correctly handles bgfx::reset

- src/renderer_gl.cpp
On some older OpenGLES devices, attempting to bind textures to
unsupported compressed formats can crash. So explicitly disable the
unsupported formats so this never happens.
> Fix crash on some OpenGLES devices

- examples/common/entry/entry.cpp
- examples/common/entry/entry.h
- examples/common/entry/entry_android.cpp
- examples/common/entry/entry_asmjs.cpp
- examples/common/entry/entry_ios.mm
- examples/common/entry/entry_osx.mm
- examples/common/entry/entry_p.h
Step 1. On Android WillSuspend and WillResume maps to focus and DidSuspend and DidResume maps to onPause and onResume. On OSX WillSuspend and DidSuspend maps to resign key, WillResume and DidResumg maps to make key.
> Adds suspend event mapped to application lifecycle

- examples/common/imgui/imgui.cpp
Doing scissor test on CPU to avoid lots of draw calls when elements are in a long scroll list.
> Doing scissor test on CPU.

- include/bgfx.c99.h
The BGFX_HANDLE_T macro ended with a semicolon and all of the uses
also ended with a semicolon, so there was an extra semicolon in
the resulting code.
> [c99] Remove extra semicolon after typedef.

- makefile
This allows passing flags to genie via the makefile:
make osx GENIE_FLAGS=--with-glfw
> Allow passing flags to genie via make.

- src/bgfx.cpp
Inconsistency:
> "bgfx::reset" uses "context->m_resolution" to resize textures.
> "bgfx::createTexture2d" uses "context->frame[0]->m_resolution".
The problem appears when the first "bgfx::reset" is done with a resolution different than 1280x720px, and a texture2d is created consecutively using "bgfx::createTexture2d(bgfx::BackbufferRatio::Enum,...)".
Bug not detected by HDR sample because main window size is setted to 1280x720.
> Textures created with BackbufferRatio::enum are not sized correctly

- src/glcontext_nsgl.mm
Support building/running on versions of OSX that lack high-DPI support.
> Support OSX versions before high-DPI support was added

- examples/16-shadowmaps/shadowmaps.cpp
Problem wasn't apparent until I adjusted the FOV to 90:
http://i.imgur.com/Tlw7pNq.png
> Fix for projection width in 16-shadowmaps example.

- examples/common/entry/entry.cpp
- scripts/genie.lua
- src/bgfx.cpp
- src/bgfx_p.h
- src/renderer_d3d11.cpp
- src/renderer_d3d9.cpp
- src/renderer_gl.cpp
Can't seem to get the OpenGL GPU profiling to compile due to unresolved external symbols. Not sure how you'd want that solved in the grand scheme of things (suggested: using namespace bgfx; didn't work).
You'll need to update Remotery before these changes will work.
> Extended Remotery profiling.

- src/renderer_d3d11.cpp
- src/renderer_d3d9.cpp
SrcRect and DstRect need to be NULL in DX9/DX11 when performing a copy from depth texture to depth texture.
> Fix blit for depth textures.

- src/renderer_mtl.mm
fixed the follow errors:
Cannot initialize a member subobject of type 'MTLPixelFormat' with an rvalue of type 'int' 
while compiling for OSX with  Xcode 7.1
> fixed compile errors on osx in renderer_mtl

- examples/15-shadowmaps-simple/shadowmaps_simple.cpp
- examples/16-shadowmaps/shadowmaps.cpp
Crash log:
..\..\..\src\renderer_d3d9.cpp (2838): BGFX Texture   8: BGRA8 (requested: BGRA8), 1024x1024 (render target).
..\..\..\src\renderer_d3d9.cpp (2496): BGFX CHECK device->CreateTexture(_width , _height , _numMips , 0 , s_textureFormat[fmt].m_fmt , D3DPOOL_SYSTEMMEM , &m_staging2d , 0 ) FAILED 0x8876086c
> Fix crash in D3D9 shadowmap examples.

- src/renderer_mtl.mm
Storing flags passed down to buffer object. (note: `BufferMtl` is typedef'd to `IndexBufferMtl`)
> Fix 32bit indices for Metal

- examples/20-nanovg/nanovg.cpp
nvgCreateImage returns 0 on failure, not bgfx::invalidHandle!
> Fixed image loading error handling in 20-nanovg

- scripts/texturec.lua
Fixes a build issue with Remotery include paths by forcibly disabling profiling for texturec.
> Fixed texturec build with --with-profiler enabled

- examples/common/entry/entry_windows.cpp
It wasn't possible to use the period on numpad before. Added VK_DECIMAL to translateKey array. This works fine on Windows 8.1
> Added VK_DECIMAL to keyboard code translation

- src/bgfx_p.h
Had a problem when expanding a dynamic vertex buffer. This change seems to fix it.
> fix: when resizing a dynamic vertex buffer, update numVertices

- examples/common/imgui/imgui.cpp
- examples/common/imgui/imgui.h
This is useful for logically or-ing the state of several UI elements together to know if any have changed (e.g. because some common action needs to be taken):
uiChanged |= imguiBool(...)
uiChanged |= imguiSlider(...)
...
> Modified imguiBool to return 'changed' state

- makefile
- scripts/genie.lua
This makes it easier for package managers to locate the required dependencies. With these changes I was able to package bgfx for nixos without needing to monkeypatch.
> Configurable genie, bx location

- src/renderer_d3d11.cpp
- src/renderer_gl.cpp
Added missing swizzle for RGBA to BGRA (copied from saveScreenShot).
I'm not able to test D3D12, but D3D9 seems fine.
> Fixed swapped R and B in D3D11 and OpenGL video capture

- examples/16-shadowmaps/shadowmaps.cpp
Shadow maps now get submitted only when necessary.
> Fixing a D3D11 warning.

- tools/geometryc/geometryc.cpp
It seems like bx::open() returns true on success, so there should be a negation in this error check.
> Fixed backwards error check in geometryc.

- src/image.cpp
- src/image.h
'_mips' is a pre-defined macro on android-mips platform, changing function parameter name to '_numMips'
> Fixing android-mips build

- src/glcontext_nsgl.h
Needed because when the context has already been created (e.g. using GLFW), m_view doesn't get initialized inside create and the code here https://github.com/bkaradzic/bgfx/blob/master/src/glcontext_nsgl.mm#L142 crashes.
> Set m_view to 0 in GlContext ctor

- src/glcontext_eagl.h
- src/glcontext_eagl.mm
- src/renderer_gl.cpp
Please find here support for (auto)resizeable SwapChain on iOS.
This feature allows creation of multiple UIViews with EAGL layers to be rendered on with the same bgfx::frame() call, with the same EAGL context, thus reusing all the resources loaded (shaders, vertex arrays, etc) and taking advantage of the existing structure on bgfx.
Best,
The Pacemaker Team
> iOS SwapChain support

- include/bgfx/bgfx.h
While researching this I noticed that the “program” part of the sort key is set to 0 for invalid programs (i.e. those used with `touch`), presumably so they sort first. But, 0 is also a valid program ID. So, `touch` calls won't necessarily sort before all other calls if program ID 0 is also used.
It looks like bgfx uses the first 8 program IDs internally so it didn't cause any issues for me. Just thought it might be worth pointing out here in case it's a mistake.
> Document bgfx::touch.

- src/hmd_ovr.cpp
- src/hmd_ovr.h
- src/renderer_gl.cpp
OVR::commitEye() is no longer needed since now it's only an internal one-liner. Fix from PR #746 has also been applied to GL renderer, so it's the same everywhere.
> Remove commitEye() and fix extra frame of latency in OpenGL as well

- src/hmd_ovr.cpp
- src/hmd_ovr.h
- src/renderer_d3d11.cpp
- src/renderer_d3d11.h
- src/renderer_gl.cpp
- src/renderer_gl.h
This commit makes the BGFX_RESET_MSAA* flag useful again with OculusVR applications.
> OculusVR: added MSAA support

- src/hmd_ovr.cpp
This commit fixes issues with stereoscopy (discussed in gitter chat earlier today)
> OculusVR: fix stereoscopic view

- src/vertexdecl.cpp
when m_stride is not part of m_hash then
decl1.begin()
.add(bgfx::Attrib::Position, 3, bgfx::AttribType::Float)
.end();
and:
decl2.begin()
.add(bgfx::Attrib::Position, 3, bgfx::AttribType::Float)
.skip(3 * sizeof(float))
.end();
are considered as same decls.
> VertexDecl::m_hash should count m_stride too

- src/bgfx.cpp
It's not safe to reuse a va_list over multiple var-arg calls.
> Fixed reuse of va_list in traceVargs

- src/renderer_gl.cpp
`glDisable(GL_DEPTH_TEST)` disables not just depth testing but depth writing too. In the OpenGL renderer, it is called even when depth writing is enabled. This commit makes it fall back to `glEnable(GL_DEPTH_TEST)` and `glDepthFunc(GL_ALWAYS)` when it is enabled.
> Fix a bug where the depth buffer is not written to in the OpenGL renderer

- examples/common/entry/entry_android.cpp
- src/bgfx.cpp
- src/bgfx_p.h
- src/glcontext_egl.cpp
On Android when the application goes into the background, the EGL
window surface becomes invalid. It is possible to resume rendering when
coming to the foreground by resetting and reinitializing bgfx from
scratch, but this is costly in terms of performance.
This patch provides an alternative by letting the application provide a
new native window, causing bgfx to recreate just the EGL window surface
while keeping the EGL context intact. This allows the application to
resume rendering without needing to reload textures, shaders, etc.
To test, build and run the Hello World example on Android, switch to
another app and then back again. The screen should not remain blank
after switching back.
> Make it possible to reset the native window

- include/bgfx/bgfxplatform.h
I was trying to get bgfx and GLFW running but was running into an issue when initializing bgfx.
In ```include/bgfx/bgfxplatform.h``` the window handle is initialized from a glfw window using:
```
pd.ndt          = glfwGetX11Display();
pd.nwh          = (void*)(uintptr_t)glfwGetX11Window(_window);
pd.context      = glfwGetGLXContext(_window);
```
however by doing so I get an error that it is not able to create drawables after importing the OpenGL functions:
```
../../../src/glimports.h (462): BGFX 0x7ffff4e0cf20 glStringMarkerGREMEDY (glStringMarkerGREMEDY)
../../../src/glimports.h (463): BGFX 0x7ffff7fcc040 glFrameTerminatorGREMEDY (glFrameTerminatorGREMEDY)
../../../src/glimports.h (464): BGFX 0x7ffff7fcc050 glGetTranslatedShaderSourceANGLE (glGetTranslatedShaderSourceANGLE)
libGL error: …
```
> Use GLX calls to get window handle on Linux/BSD instead of X11 calls.

- src/renderer_mtl.h
- src/renderer_mtl.mm
fixed typo in vertex half vertex format
added missing texture formats
fixed packed depth/stencil format usage
Note that I have to add missing texture formats to s_textureFormat. This problem should be caught by  static assert but it seems on XCode with default settings static_assert does not work.
> metal fixes

- src/renderer_d3d11.cpp
OpenVR requires DXGI 1.1 to share textures using a keyed
mutex to guantee ordering between the compositor and application.
OpenVR will startup with an adpater created by a 1.0 factory, but
will fail when submitting frames to the compositor.
See: https://steamcommunity.com/app/358720/discussions/0/405692224241830277/
> Attempt to use DXGI 1.1 when possible

- examples/common/nanovg/nanovg.h
- examples/common/nanovg/nanovg_bgfx.cpp
- examples/common/nanovg/nanovg_bgfx.h
This commit moves the additional nanovg functions for bgfx to a separate header file, so it is possible to compile the original nanovg  source files with bgfx in a custom build environment.
> Moves additional bgfx nanovg functions to a separate header file.

- examples/common/entry/entry_ios.mm
- examples/common/nanovg/nanovg.cpp
- examples/common/nanovg/nanovg.h
- examples/common/nanovg/nanovg_bgfx.cpp
This commit fixes the bug that the bgfx does not respect the `devicePixelRatio` parameter passed to nanovg's `nvgBeginFrame()` function. The problem is caused by the `bgfx::setViewRect()` call defined in the `nvgRenderViewport()` function, as it should take size in consideration of the `devicePixelRatio` value.
However, this commit does not fix nanovg's example app because currently there is no easy way to pass the scale value to the `ExampleNanoVG::update()` method as it calls `nvgBeginFrame()`.
PS. I also requested a pull request for forwarding the `devicePixelRatio` parameter in the original `nanovg` project and it's already merged. https://github.com/memononen/nanovg/pull/297
> Adds iOS device's Retina screen support for nanovg.

- src/glcontext_eagl.mm
This commit gives custom `CAEAGLLayer` instance a chance to set the `opaque` property through the `style` property. Currently, the `GlContext` implementation for `CAEAGLLayer` always sets the layer's `opaque` property to `true` explicitly no matter what the original value is. Though setting the layer as opaque does help for performance, there are times this option should be turned off by decision. Now the `opaque` property is respected if setting in the `style` dictionary.
> Allows to change the `opaque` property of `CAEAGLLayer`.

- examples/common/nanovg/nanovg_bgfx.cpp
- examples/common/nanovg/nanovg_bgfx.h
This commit ports nanovg's helper functions for rendering stuff in framebuffer defined in `nanovg_gl_utils.h`. Also, a new `nvgState()` function is created for bgfx backend so it is possible to blend between framebuffers, which feature is long requested but not yet supported in original nanovg. The `nvgState()` function can be called between `nvgBeginFrame()` and `nvgEndFrame()`.
Example:
float scale = 2;
NVGLUframebuffer* fb = nvgluCreateFramebuffer(ctx, 100 * scale, 100 * scale, 0);
nvgluBindFramebuffer(fb);
nvgBeginFrame(ctx, 100, 100, scale);
// renders anything offscreen
nvgEndFrame(ctx);
nvgluBindFramebuffer(NULL);
// Pastes the framebuffer rendering.
nvgBeginFrame(ctx, 1024, 768, scale);
NVGpaint paint = nvgImagePattern(ctx, 0, 0, 100, 100, 0, fb->image, 1);
nvgBeginPath(ctx); …
> Implements nanovg's framebuffer helper functions.

- src/renderer_mtl.h
- src/renderer_mtl.mm
Synchronize textures with read back flag. 
example-30-picking now works for Metal renderer
> metal: synchronize textures with READ flag

- src/renderer_mtl.h
- src/renderer_mtl.mm
This commit fixes #870 that it uses Mac-only methods and causes iOS failed to compile.
> Fixes the issue that mac-only methods cause iOS failed to compile.

- examples/common/nanovg/nanovg.cpp
- examples/common/nanovg/nanovg.h
- examples/common/nanovg/nanovg_bgfx.cpp
- examples/common/nanovg/nanovg_bgfx.h
This commit updates bgfx's NanoVG codebase to adapt the latest NanoVG commit since I've implemented first-class blending support (https://github.com/memononen/nanovg/pull/298) for the original NanoVG and there is no need of `nvgState()` anymore.
> Updates nanovg to support global composite operation.

- include/bgfx/bgfx.h
- include/bgfx/c99/bgfx.h
- src/bgfx.cpp
Expose debug API using `va_list`, which allows usage in Swift
> improve inter-operability by exposing dbgTextPrintfVargs API

- examples/common/entry/entry_glfw.cpp
This fills in the GLFW implementation of the example entry code. It requires GLFW 3.2 and has been tested with VS2015 and MinGW-w64, with Clang on OS X and GCC on Linux.
I think it includes all features except `ENTRY_WINDOW_FLAG_FRAME`. Context creation has been left entirely to bgfx, analogous to the SDL2 backend. The gamepad input is currently a terrible hack implemented on top of the joystick API. I didn't putting a lot of effort into it now as I'm about to add a real gamepad API for 3.3, which solves the problem properly.
The second commit is an optional optimization, kept separate for now as it may introduce some gamepad input lag.
> Usable GLFW entry backend

- makefile
- scripts/genie.lua
This PR adds a new flag to `genie.lua` called `--with-examples` and uses it to control whether the example binaries are built or not. It also changes the default options in `makefile` to include this flag, such that the default behavior of `bgfx` compilation is unchanged.
This allows users who are building with CI systems or as part of a larger automated build process to avoid having to compile examples each time they build `bgfx`.  They can instead use `genie` directly to configure their project to build without examples.
I think this change matches the style of your other configuration options, @bkaradzic, but please feel free to correct it if not.
> Added flag to control building examples.

- makefile
Together with changes to the bx toolchain, this allows for building an arm64 static library for iOS
> Added support for ios-arm64 compilation

- src/hmd_ovr.cpp
DX11 will signal an error on the mirror present if the compositor
is not serving the application frames to the hardware.
> Do not render VR mirror texture is the headset is not rendering

- src/hmd_ovr.cpp
- src/hmd_ovr.h
- src/renderer_d3d11.cpp
- src/renderer_d3d11.h
- src/renderer_gl.cpp
- src/renderer_gl.h
Simplify the renderer interface for VR to separate the OVR
implementation from the overall HMD foundation.
Part of merging OpenVR back upstream.
> Combine OVRBufferI and OVRMirrorI into a single interface

- src/hmd_ovr.h
- src/renderer_d3d11.cpp
- src/renderer_d3d11.h
- src/renderer_gl.cpp
Clear mirror and eye textures of OVRRenderI at startup
instead of in the individual renderer interfaces
> Fix opengl OVR texture lifetime issues

- src/hmd.cpp
- src/hmd.h
- src/hmd_ovr.cpp
- src/hmd_ovr.h
- src/renderer_d3d11.cpp
- src/renderer_d3d11.h
- src/renderer_gl.cpp
- src/renderer_gl.h
The new platform agnositic class bgfx::VR manages the
functionality that is shared across the various VR platforms.
The individual platform renderers no longer need
to interface with the internal VR tpyes (OVRRenderI) directly
This greatly simplifies the OVR object's surface area which
is now provided by the VRImplI interface. bgfx::VR now manages
core lifecycle issues of the headset.
The notable renderer API changes are the separation of sensor
sampling and rendering. We need these separate so we can control
the timing (later commit) of camera sampling with finer granularity
than at the start of the video frame.
> Add a new platform agnostic bgfx::VR internal class

- include/bgfx/c99/bgfx.h
c4fa560 added two new fields to different positions in the C++ and C99 headers
> Fixed order of fields in bgfx_caps_t not matching bgfx::Caps

- include/bgfx/bgfxplatform.h
- include/bgfx/c99/bgfxplatform.h
- src/hmd.h
- src/hmd_ovr.cpp
Without the ovrSession, you are unable to call any functions in LibOVR (and there's a lot in there which BGFX *shouldn't* cover).
This also removes the unused adapter LUID from the VRDesc struct.
Usage:
```cpp
bgfx::PlatformData pd;
pd.session = NULL;
// [...]
if (OVR_SUCCESS(ovr_Initialize(NULL))) {
ovrSession session;
ovrGraphicsLuid luid;
ovr_Create(&session, &luid);
pd.session = (void*)session;
}
bgfx::setPlatformData(pd);
// later...
ovr_Shutdown();
```
> Allow user-provided ovrSession via PlatformData

- src/renderer_gl.cpp
example-09-hdr asserts on an iPad Mini 2 running iOS 10.0.1 (14A403) with the following message:
`BGFX CHECK glInvalidateFramebuffer(0x8D40, idx, buffers); GL error 0x500: GL_INVALID_ENUM`
Although it's valid according to the spec (OpenGL ES 3.0.4 (August 27, 2014)), Apple's driver isn't happy with the GL_DEPTH_STENCIL_ATTACHMENT enum. I suspect this has something to do with GL_DEPTH_STENCIL_ATTACHMENT not being supported by GL_EXT_discard_framebuffer (glInvalidateFramebuffer's predecessor).
As I've seen other drivers complain and GL_DEPTH_ATTACHMENT|GL_STENCIL_ATTACHMENT is functionality equivalent, I've replaced the enum assignment.
> glInvalidateFramebuffer: iOS (iPad Mini 2, iOS 10.0.1) invalid enum work around

- src/renderer_gl.cpp
> Revert "glInvalidateFramebuffer: iOS (iPad Mini 2, iOS 10.0.1) invalid enum work around"

- examples/common/entry/entry_x11.cpp
For consistency with other platforms (Windows, at least)
> Use m_mz in ButtonPress mouse event instead of 0

- src/renderer_gl.cpp
D16 and D24S8 test in initTestTexture of renderer_gl now perform correct texImage2D call.
> * Fix AsmJS D16 D24S8 format / internal format match

- src/hmd.cpp
- src/hmd.h
- src/hmd_ovr.cpp
- src/hmd_ovr.h
- src/renderer_d3d11.cpp
- src/renderer_gl.cpp
This allows the game to render to a single FB and
pass that into existing post process pipeline.
> Use a single render target for VR rendering

- src/image.cpp
When converting texture with PVRTexTool the format is not found by bgfx. I also found out that texturec doesn't handle A8 textures properly (that is when converting from RGBA image where A should be used, but instead some other channel is used).
> Added KTX A8 texture format.

- scripts/shaderc.lua
I assume this is a safe change? My builds on Linux were failing due to pthread not being linked.
> Remove hyphen in shaderc.lua (s/linux-*/linux*/)

- tools/shaderc/shaderc.cpp
Current help when running shaderc says
```
-i <include path>             Include path (for multiple paths use semicolon).
```
I took this to mean that one should do:
```
shaderc -i path1;path2
```
when in reality it's 
```
shaderc -i path1 -i path2
```
so I changed the text to 
```
-i <include path>             Include path (for multiple paths use use -i multiple times).
```
There's probably better language, but this is at least not misleading.
> Fix doc for shaderc

- examples/common/entry/entry_sdl.cpp
I noticed that the SDL version no longer built due to changes to `bx:open`, `bs::close` and `bx:read`.
> Updating code to match bx changes.

- src/glcontext_glx.cpp
If BGFX_CONFIG_DEBUG is defined, get a GL debug context. This mirrors the
behavior from wgl, and allows KHR_debug/ARB_debug_output messages to work.
> Ensure we get a debug context as appropriate in glx.

- src/glcontext_egl.cpp
EGL_Android_Recordable extension allows to use a surface as an input for recording with extremely low overhead. The current capture method, and in particular the glReadPixels call performs badly when trying to record video, this extensions allows for native video recording.
Enabling the extension, but not using it doesn't seem to have any measurable performance cost.
> Added support for EGL_ANDROID_recordable

- examples/common/font/text_metrics.cpp
- examples/common/font/text_metrics.h
I don't want new/delete TextMetrics instance every time I need calculate text width/height.
> new function TextMetrics::clearText()

- examples/common/font/text_metrics.cpp
> TextMetrics includes \n

- examples/common/nanovg/nanovg.cpp
- examples/common/nanovg/nanovg.h
- examples/common/nanovg/nanovg_bgfx.cpp
This commit updates NanoVG's bgfx backend to match the original NanoVG's latest commit, which has significant changes about composite operation implementation as mentioned in pull request https://github.com/memononen/nanovg/pull/312.
> Updates NanoVG to the latest commit.

- examples/common/nanovg/nanovg_bgfx.cpp
- examples/common/nanovg/nanovg_bgfx.h
This commit changes the `nvgluCreateFramebuffer()` function to not assign a view id automatically as it would easily reach the limit of `uint8_t`. Instead, a new `nvgluSetViewFramebuffer()` function is created to allow users to assign the view id manually as mentioned in #1095.
> Allows to set view id of NanoVG’s framebuffer manually.

- src/bgfx.cpp
- src/bgfx_p.h
- src/renderer_d3d11.cpp
- src/renderer_d3d12.cpp
- src/renderer_d3d9.cpp
- src/renderer_gl.cpp
- src/renderer_mtl.mm
Allows binding of dynamic vertex/index buffers as resources that can be accessed in vertex/fragment shaders (previously only had this capability in compute shaders). This is useful for compute-oriented techniques like tiled forward lighting.
Not exposed in public headers yet.
> Feature: set shader vertex/index buffer, squashed into one commit

- src/renderer_gl.cpp
Device info from log was:
Vendor: 'Imagination Technologies'
Renderer: 'Renderer: PowerVR SGX 540'
Version: 'OpenGL ES 2.0 build 1.8@905891'
> enable detach shader workaround

- examples/15-shadowmaps-simple/shadowmaps_simple.cpp
Notes:
I haven't changed flipV computation, but shouldn't it depend on caps->originBottomLeft instead of checking renderer types?
https://github.com/bkaradzic/bgfx/compare/master...attilaz:shadowmaps-simple-entry?expand=1#diff-922d9000b9dea8a91b8caa66460999f9R60
Sample works fine on OSX-OpenGL, but I expected some problem with setUniform in the init part(it was problematic in stencil example). I left it in the init.
https://github.com/bkaradzic/bgfx/compare/master...attilaz:shadowmaps-simple-entry?expand=1#diff-922d9000b9dea8a91b8caa66460999f9R79
> shadowmaps simple to entry::AppI

- examples/16-shadowmaps/shadowmaps.cpp
notes:
This example is huge ( and great :) ). I tested it with a lot of settings, I didn't find any difference, but even the original example had some problem with directional light on OSX/OpenGL:
I was surprised that I can set values like this: https://github.com/bkaradzic/bgfx/compare/master...attilaz:shadowmaps-entry?expand=1#diff-131882cabf675c74c1b19e89f19a284bR1408
Maybe it is a c++11 thing?
But it didn't work for array of structures, so I did a memcpy for smSettings: https://github.com/bkaradzic/bgfx/compare/master...attilaz:shadowmaps-entry?expand=1#diff-131882cabf675c74c1b19e89f19a284bR1880
Putting these to update (instead if init) fixes rendering when resolution changes:  
https://github.com/bkaradzic/bgfx/compare/master...attilaz:shadowmaps-entry?expand=1#diff-131882cabf675c74c1 …
> shadowmaps to entry::AppI

- examples/11-fontsdf/fontsdf.cpp
I used fixed window size ( as it was already in the example). 
https://github.com/bkaradzic/bgfx/compare/master...attilaz:11-fontsdf-dearimgui?expand=1#diff-4ade17483b9348cc0f0e68523527517fR135
As I see for example 09-hdr uses: https://github.com/bkaradzic/bgfx/blob/master/examples/09-hdr/hdr.cpp#L307 this computation for window size, but this doesn't seem to handle window size changes well. Or I am doing something wrong?
> 11-fontsdf converted to dear imgui

- examples/14-shadowvolumes/shadowvolumes.cpp
Notes:
I don't know how to implement inactive state in dear imgui. So I either simply show the component in an active state (light pattern selector when m_settings_updateLights is false) or hide it (stencil buffer implemanted depth pass/fail when in mixed mode).
On OSX the depth pass method has some issues. Strange inverted lighting for some light position. This was there before the conversion.
> 14-shadowvolumes: switched to imgui

- include/bgfx/c99/bgfx.h
when building bgfx as a shared library - now works with MinGW-w64 under windows and also under linux when -fvisibility=hidden is passed to the compiler to hide all symbols by default (which is recommended - it's a good practice)
reworked - using ```<bx/platform.h>```
> Fix exporting macros for the C99 API

- examples/common/entry/entry_windows.cpp
Fixes windows incorrectly moving when resized under entry_windows, as reported in #1211.
> entry_windows: Fix window incorrectly moving on resize

- src/renderer_gl.cpp
Implementation of a fallback in bgfx::readTexture for renderer_gl, using glReadPixels, when glGetTexImage is not supported, mostly for gles based renderers ( ios, asmjs )
> gl_renderer readTexture fallback for gles based renderers

- src/renderer_mtl.mm
Metal: Add support of setting CAMetalLayer as PlatformData.nwh for macOS(OSX) platform
> Metal: Add support of setting CAMetalLayer as PlatformData.nwh (OSX)

- src/renderer_mtl.h
This was  the cause of the slow fullscreen blending on metal compared to opengl es on the same hardware. On metal compatible mobile gpus there is no fixed function blending hardware, they are just patching shaders with blending code ( I have checked this with implementing blending with states and programmable blending on metal and gles. the performance was exactly the same). Disabling fastmath caused slower generated code for blending.
> removed fastMathEnabled = NO;

- 3rdparty/ocornut-imgui/widgets/gizmo.inl
Thanks For This Great Library . There Were One Build Error Using vs2012 express compiler that it can't initialize class members outside of constructor.  Minor Fix in  "struct Context" in imgui's gizmo.inl.
.
> Minor Fixing Compile Error on vs2012 express

- examples/common/entry/entry.cpp
I think this is more convenient on desktop, but is a must have on mobile where app is running in fullscreen and window size is set to screen size.
> preserve window size when switching example

- 3rdparty/dxsdk/include/d3dx12.h
- src/renderer_d3d12.cpp
bgfx mingw64 version crushs on d3d12 . I found some d3d12 apis have different calling conversion in gcc .
For example : 
`LUID ID3D12Device::GetAdapterLuid() ` 
returns a struct LUID . For gcc, it passed return value in register, but d3d12.dll  use the second argument for return address.
I tried to add `-fpcc-struct-return` first , but the ABI difference is still exist. For gcc, the return address is the first arguement, but  the second for vc/d3d12.dll (first one is this) .
This patch need to modify 3rdparty/dxsdk , maybe there is a better way .
> bugfix for d3d12 renderer mingw64

- examples/15-shadowmaps-simple/shadowmaps_simple.cpp
- src/renderer_mtl.h
- src/renderer_mtl.mm
Fix for https://github.com/bkaradzic/bgfx/issues/1227 .
It gets texture slot from compiled shaders and maps it to Sampler uniform. So sampler uniform MUST be defined before using shader (shadowmap_simple has a bug with invalid uniform name).
> Fix sampler/texture indices for metal

- src/renderer_mtl.h
- src/renderer_mtl.mm
- setLabel now in 'wrapper' I have tested this and it compiles on older sdks ( gives warning). It is compatible with iOS8 devices, where Function setLabel is not available.
- fixed texture skip
- fixed performance issue related to submitBlit. It caused problem because it closed active rendercommand encoder even when blit was not used, so device had to store/load framebuffer. ( thanks to @jazzbre)
> misc metal fix/optim

- examples/common/example-glue.cpp
The obsolete `ImGui::Begin` takes `float bg_alpha` as a fourth argument, but `ImGuiWindowFlags_AlwaysAutoResize` was passed as the fourth argument.
> Fixed flag ImGuiWindowFlags_AlwaysAutoResize been passed as alpha argument

- include/bgfx/defines.h
`uint32_t(_ref)` can be compiled by C++ compiler, but it's invalid in C.
> uint32_t(_ref) can't be compiled by C compiler

- examples/27-terrain/terrain.cpp
In Example 27 Terrain:
When selecting the **Height Texture** rendering mode, the visible height (if not 0) changes for no reason (small shifting/tilting).
I narrowed the problem down to the mapping of the function `texture2DLod`.
I do not know what coordinates it expects, but I guessed, that it might do something like:
int x = (int)(x_float * size_x)
This can lead to accidental rounding down, so I added `0.5` before diving by the size to make the position be "in the middle of the pixel" (I guess (0.0, 0.0) is the upper left corner of the first pixel).
I am not really familiar with graphics stuff. I can only say, that it fixed the problem for me.
I also fixed some incorrect out of bounds checks.
> Example 27 Terrain: Fixed incorrect height display in mode Height Texture

- src/renderer_gl.cpp
I test 21-deferred under OPENGL renderer , it shows blank  sometimes.
I checked opengl renderer source, and found when the scissor rect is zero, it just continue to next item.  https://github.com/cloudwu/bgfx/blob/master/src/renderer_gl.cpp#L6948-L6951   (https://github.com/bkaradzic/bgfx/commit/8b3f752af50e6c700ac46db34adff36a66165223)
In this case, currentState.m_stateFlags is changed , but it doesn't call the associated opengl api :
`glDisable(GL_DEPTH_TEST)`  .
This patch can fix this bug, but I guess other renderers should also need fix this problem.
> bugfix: restore old flags when skip zero scissor rect

- tools/shaderc/shaderc.cpp
- tools/shaderc/shaderc.h
- tools/shaderc/shaderc_glsl.cpp
- tools/shaderc/shaderc_hlsl.cpp
- tools/shaderc/shaderc_pssl.cpp
- tools/shaderc/shaderc_spirv.cpp
CompileShader is split into two functions. The first could be used as a runtime library function(https://github.com/attilaz/bgfx/blob/shaderc_api/tools/shaderc/shaderc.cpp#L869): 
It gets varying and shader data in memory also it gets options struct instead of a command line string.
The second parses the command line and loads files into memory.
To get a proper API  parameters would need some work. Varying is zero terminated string without length parameter. _shader has length param...
Also not sure if bx::FileWriter could write into memory or some other writer should be used... 
I have tested shaderc with the shadergen makefile in the examples and the result was the same as before.
While I was browsing the code I have found this: …
> Adding an API to shaderc

- src/renderer_d3d11.cpp
- src/renderer_d3d12.cpp
```
../../../src/renderer_d3d11.cpp: In member function 'void* bgfx::d3d11::DirectAccessResourceD3D11::createTexture3D(const D3D11_TEXTURE3D_DESC*, const D3D11_SUBRESOURCE_DATA*, ID3D11Texture3D**)':
../../../src/renderer_d3d11.cpp:4626:72: warning: passing NULL to non-pointer argument 4 of 'virtual HRESULT ID3D11DeviceContext::Map(ID3D11Resource*, UINT, D3D11_MAP, UINT, D3D11_MAPPED_SUBRESOURCE*)' [-Wconversion-null]
deviceCtx->Map(m_texture3d, 0, D3D11_MAP_WRITE, NULL, &mappedResource);
```
See https://msdn.microsoft.com/zh-cn/library/windows/desktop/ff476457(v=vs.85).aspx
```
../../../src/renderer_d3d12.cpp: In member function 'void bgfx::d3d12::RendererContextD3D12::submitBlit(bgfx::BlitState&, uint16_t)':
../../../src/renderer_d3d12.cpp:4969:108: warning: missing initializer for …
```
> fix warning in mingw gcc

- include/bgfx/bgfx.h
The macro `BGFX_HANDLE` is used the following way `BGFX_HANDLE(DynamicIndexBufferHandle);`, however it creates an error when using -Werror=pedantic with GCC since the `;` is unneeded.
I removed the `;` as I can't silence this warning without removing pendantic as a whole.
> Fix GCC error: extra ‘;’ [-Werror=pedantic]

- examples/02-metaballs/metaballs.cpp
- examples/05-instancing/instancing.cpp
- examples/08-update/update.cpp
- examples/14-shadowvolumes/shadowvolumes.cpp
- examples/21-deferred/deferred.cpp
- examples/22-windows/windows.cpp
- examples/26-occlusion/occlusion.cpp
``bgfx::dbgTextPrintf(...)`` calls weren't showing up in most of the samples since they didn't have ```BGFX_DEBUG_TEXT``` set.
I rearranged the screen-space elements on a few of these from the top-left area so that they wouldn't be drawing over/under the ImGui diagnostic window. 
Fixed a couple localized bugs.
> Samples cleanup

- src/renderer_d3d11.cpp
On Windows8+, DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL gives a hupe CPU saving and better latency, so try it and fallback to DXGI_SWAP_EFFECT_DISCARD if we didn't manage to create the swapchain (for win7).
I also set BufferCount to 2 since we already call ResizeBuffers with 2 in updateResolution.
> D3D11 : try to create swapchain with DXGI_SWAP_EFFECT_FLIP_SEQUENTIAL 1st

- 3rdparty/forsyth-too/forsythtriangleorderoptimizer.cpp
- 3rdparty/forsyth-too/forsythtriangleorderoptimizer.h
- tools/geometryc/geometryc.cpp
- Forsyth::OptimizeFaces() now has 2 overloads, 1 for uint16_t and one
for uint32_t sized indices. Internally each overload now calls down to
the templated OptimizeFacesImpl() providing the respective index type.
- The new 'vertexBaseIndex' is the starting vertex index
subtracted from each index in indexList to allow safe operation on
multiple objects in a single index buffer.
- Also replaced the interal int typedefs with common types provided by
stdint.h
> uint32 size indices and vertexBaseIndex to Forsyth

- examples/common/entry/entry_osx.mm
The height returned by contentRectForFrameRect is not exactly the same as the ENTRY_DEFAULT_HEIGHT if the screen size is not big enough.
For example, on my Mac, rect.height equals 702, which is 18 less than ENTRY_DEFAULT_HEIGHT(720).
This will cause the imgui’s cord system offset by 18, so even the cursor is not on the button, the imgui will still think the mouse is hover the button, also, the top of imgui’s window will also offset a little bit.
However, these symptom will gone when the window is resized.
In short, this fix unify the behavior of window size event in initial state with resize.
> Fix OSX initial window size event.

- 3rdparty/fcpp/cpp1.c
- 3rdparty/fcpp/cpp3.c
- 3rdparty/fcpp/cpp6.c
- 3rdparty/fcpp/cppadd.h
- 3rdparty/glsl-optimizer/src/glsl/glsl_optimizer.cpp
- tools/shaderc/shaderc_glsl.cpp
This commit fixes memory leaks in shaderc.
Upstream PR for fcpp : https://github.com/bagder/fcpp/pull/2
Upstream PR for glsl-optimizer : https://github.com/aras-p/glsl-optimizer/pull/142
I didn't see any other leaks with my simple shaders, but there might still be a few lying around.
> Fix shaderc leaks

- src/renderer_mtl.mm
Source:
https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf
At Resources/Maximum number of layers per 1D texture array, 2D texture array, or 3D texture
> maxTextureLayers limit for Metal

- src/glcontext_eagl.mm
ios11 requires to flush transactions before creating a new
framebuffer for full screen postproceses.
> fix ios11 black screen when using postprocess

- src/renderer_d3d12.cpp
It's the same d3d12 bug as #1239 .
> fix mingw-gcc bug like #1239

- 3rdparty/glslang/glslang/Include/Common.h
I can't build glslang by mingw-gcc , the error message is:
```
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/stdio.h:1469:0,
from C:/msys64/mingw64/x86_64-w64-mingw32/include/locale.h:12,
from C:/msys64/mingw64/include/c++/7.2.0/clocale:42,
from C:/msys64/mingw64/include/c++/7.2.0/x86_64-w64-mingw32/bits/c++locale.h:41,
from C:/msys64/mingw64/include/c++/7.2.0/bits/localefwd.h:40,
from C:/msys64/mingw64/include/c++/7.2.0/string:43,
from C:/msys64/mingw64/include/c++/7.2.0/stdexcept:39,
from C:/msys64/mingw64/include/c++/7.2.0/array:39,
from C:/msys64/mingw64/include/c++/7.2.0/tuple:39,
from C:/msys64/mingw64/include/c++/7.2.0/unordered_set:41,
from E:/opensource/bgfx/3rdparty/glslang/glslang/Include/Common.h:93,
from …
```
> fix mingw gcc error

- src/glimports.h
- src/renderer_d3d11.cpp
- src/renderer_gl.cpp
This adds the ability to bind a FrameBuffer to a 2D Texture Array layer, which wasn't implemented so far.
I tested that it works in my own code, but none of the examples use that feature.
I checked that the examples still work.
Some notes :
- GL was already storing the number of layers in the `m_depth` member of the texture object, but D3D11 wasn't, so I opted to do the same for D3D11. 
- glFramebufferTextureLayer needed to be added to the GL imports. I'm not exactly sure I added them in the right way, but I think you will know how exactly it needs to be (glFramebufferTextureLayer exists in GL >= 30, GLES >= 30 and in an extension called ARB_geometry_shader4 ?)
EDIT : I have no idea why the CI build fails. This doesn't look related to the code ?
> Add 2D Texture layer attachment support in GL and D3D11

- src/renderer_d3d11.cpp
```
renderer_d3d11.cpp
In file included from ../../../../bx/include/bx/bx.h:17:0,
from ../../../src/config.h:9,
from ../../../src/bgfx_p.h:23,
from ../../../src/renderer_d3d11.cpp:6:
../../../src/renderer_d3d11.cpp: In member function 'bool bgfx::d3d11::RendererContextD3D11::init(const bgfx::Init&)':
../../../../bx/include/bx/macros.h:76:26: warning: attribute 'fallthrough' not preceding a case label or default label
^
../../../src/renderer_d3d11.cpp:1511:5: note: in expansion of macro 'BX_FALLTHROUGH'
BX_FALLTHROUGH;
```
This warning is introduced by https://github.com/bkaradzic/bgfx/commit/480620751bcdc51dec9c71d917975c1de6a9723d  because of removing `case ErrorState::CreatedDXGIFactory` .
> remove BX_FALLTHROUGH to avoid warning

- src/nvapi.cpp
int * uint32_t = uint32_t, so cast first to avoid truncation.
> NVAPI:  Don't truncate available memory to 4GiB

- README.md
Twinkle's url no longer works, so removing it.
> Updating README.md to remove Twinkle

- src/renderer_d3d11.cpp
Blitting to a 2D texture layer doesn't work on D3D11 : I pinned it down to these two lines, where the dest and source Z parameters are ignored if the texture is not a cubemap.
I simply removed the cubemap check, since it doesn't make much sense IIUC (2d textures can have layers too).
> Fix blit to 2D texture layer on D3D11

- examples/16-shadowmaps/shadowmaps.cpp
The slices of the camera frustum in the shadowmap example are calculated wrong because the height is inverted. This fixes it and makes the frustum slices much tighter (hence improves shadow quality in the example).
> Fix wrong frustum in shadowmaps example

- src/renderer_gl.cpp
When loading a shader that is using uint, but no other >120 features, it is patched with version #version 120 and fails loading. This fixes it.
> GL Shaders using uint need #version 130

- src/renderer_gl.cpp
WebGL 2.0 doesn't support binary program functionality, so if bgfx is compiled with ES = 3.0 for WebGL, it causes multiple failures :  this fixes it.
> Fix Webgl2 binary program support

- src/bgfx.cpp
The C99 api `bgfx_init` is broken now. I found you forgot transform C++ interface to C99 struct when you changed api `bgfx_init`.
ps. Could you add C99 api `bgfx_init_ctor` into the document ?
> fix c99 bgfx_init

- examples/common/entry/entry_sdl.cpp
Results in this bug https://github.com/bkaradzic/bgfx/issues/1341
> Fix: Mouse up/down events from entry_sdl.cpp incorrectly have mouse_z=0

- tools/shaderc/shaderc_hlsl.cpp
Hello, when the DirectX11 HLSL shader compiler is used with debug (for example: `--debug --profile vs_4_0`), errors have the format:
`<path to hlsl>(<row>,<column>): <error text>`
or:
`<path to hlsl>(<row>,<start column>-<end column>): <error text>`
for example:
`E:\tmp\vs_cubes.bin.hlsl(9,1-2): error X3000: unrecognized identifier 'xx'`
This will search and skip the hlsl path in the error message.
> Error line searching for HLSL compiled with debug info

- include/bgfx/bgfx.h
- include/bgfx/c99/bgfx.h
- src/bgfx.cpp
I found some c99 api are missing when I do lua binding. I need these two api to convert struct bgfx_vertex_decl back to a lua table.
> Add C99 api : bgfx_vertex_decl_decode and bgfx_vertex_decl_has

- include/bgfx/c99/bgfx.h
When trying to use `BGFX_INVALID_HANDLE` in C, I get an error that it's undeclared. This fix clears everything up and is functionally identical to its C++ equivalent.
Really enjoying what BGFX has to offer! Keep it up!
> Fixes "BGFX_INVALID_HANDLE undeclared" error in C

- src/shader_dxbc.cpp
if we have the wrong RCP operands count, bgfx::read will return the wrong size and the library will crush.
> Fixed RCP operands count.

- makefile
See: https://github.com/bkaradzic/bgfx/blob/master/scripts/shaderc.lua#L161
Considering all `mingw-gcc` builds are targeting the same operating system, the appropriate flag should be set or this condition will fail during cross-compilation - as shown above.
For example: building for Windows on Unix using the `mingw-gcc-release64` action will implicitly define Unix as the target system. We are targeting Windows, not Unix, and therefore we want the condition to pass and avoid any Unix-only source files. Cygwin can fix this by providing all required files but also includes several unwanted runtime dependencies and is not always a viable solution.
> Fix mingw-gcc target system

- tools/shaderc/shaderc.cpp
When printing the binary representation of the converted shader, shaderc
also prints a comment with the ascii readable characters for each line.
For unprintable characters, it relies on isprint() to replace them with
the '.' character.
Under MSVC 2017, isprint() may incorrectly return true for the tab
character. This patch adds a WAR to explicitly test for tabs, to make
sure they get replaced with '.'.
See here for discussion of isprint() bug on stackoverflow:
https://stackoverflow.com/questions/51435249/isprint-t-evaluates-to-true-64-with-md-compiler-option
> Fix issue with tab character in shaderc output

- 3rdparty/dxsdk/include/d3dx12.h
- src/renderer_d3d12.cpp
gcc 8.2.0 warning :
```
../../../src/renderer_d3d12.cpp:571:116: warning: cast between incompatible pointer to member types from 'D3D12_CPU_DESCRIPTOR_HANDLE (ID3D12DescriptorHeap::*)()' to 'PFN_GET_CPU_DESCRIPTOR_HANDLE_FOR_HEAP_START' {aka 'void (ID3D12DescriptorHeap::*)(D3D12_CPU_DESCRIPTOR_HANDLE*)'} [-Wcast-function-type]
(_heap->*(PFN_GET_CPU_DESCRIPTOR_HANDLE_FOR_HEAP_START)(&ID3D12DescriptorHeap::GetCPUDescriptorHandleForHeapStart) )(&handle);
```
> fix warnings for gcc 8.2

- include/bgfx/bgfx.h
- include/bgfx/defines.h
- src/bgfx.cpp
- src/bgfx_p.h
For now the only way to get an encoder usable from a worker thread is to call `bgfx::begin()` from a thread that is not the main thread.
This adds the ability to explicitly get an encoder for a worker thread from the main thread when calling `bgfx::begin()`.
> Add option to force bgfx::begin() to return an encoder for a worker thread

- src/renderer_gl.cpp
This reverts commit https://github.com/bkaradzic/bgfx/commit/42b1104b741c05a633cd0b4e4057edf2a8251e96 which was intended as a fix to https://github.com/bkaradzic/bgfx/issues/1395
The argument here is that the problem in https://github.com/bkaradzic/bgfx/issues/1395 could perfectly have been worked around by the user by using a `ivec4` attribute instead of an `uvec4`, which works just as well, while the current situation can only be worked around by compiling bgfx with a custom `BGFX_CONFIG_RENDERER_OPENGL` compiler define.
AFAIU the more functionality of bgfx is not tied to `BGFX_CONFIG_RENDERER_OPENGL`, and just works out of the box, the better.
> Revert 42b1104

- src/renderer_gl.cpp
- src/renderer_gl.h
There is a bug which cause instancing to simply fail with WebGL 2
The cause is that the instancing attributes are never disabled after having been used. In WebGL 2, specifically, this will cause the next draw call to fail. This fixes the problem by disabling instancing attributes when they were used.
> Fix webgl2 instancing bug

- src/renderer_gl.cpp
- src/renderer_gl.h
This pursue (and finishes, I presume) the work from previous pull request https://github.com/bkaradzic/bgfx/pull/1512 to make bgfx play nice with WebGL 2.0
In some cases, WebGL will produce errors because some attributes are still bound, but they are not bound to any buffers anymore.
This is due to bgfx not unbinding them after finishing with a program. This patch fixes it by always unbinding attributes when binding a new program, and the last bound program at the end of the draw loop.
I hesitated to add this behavior under `#IF BX_PLATFORM_EMSCRIPTEN` guards, but I assumed the performance would be more than negligible so it would not hurt to add it to the general path.
(Some reference of browser code enforcing this:
https://dxr.mozilla.org/mozilla-central/rev/a461fe03fdb07218b7f50e92c59dd …
> Unbind Attributes after use

- examples/32-particles/particles.cpp
mtxSRT produced a matrix that ImGuizmo did not agree with when it came to rotation(ImGuizmo::ROTATE) which produced endless rotation. Using ImGuizmo's RecomposeMatrixFromComponents fixes this issue.
> Fixed ImGuizmo::ROTATE operation

- src/bgfx.cpp
- src/renderer_gl.cpp
Made an attempt at creating a pull request which deals with the things mentioned in #1528.
I feel that it should be ok that `isFramebufferFormatValid` only checks that it has an `internalFmt` just like `isImageFormatValid`.
Also, for devices that support `D24S8`-format but not `GL_DEPTH_STENCIL_ATTACHMENT` I made a proposed fix for that.
Finally I changed `isTextureFormatValid` to allow for creating framebuffers of formats that are only supported as that.
> OpenGL format detection and wider framebuffer-creation support

- makefile
Removing mips abi as its no longer included in the android ndk.
see corresponding bx pull request: bkaradzic/bx#193
> Android ndk 18

- src/glcontext_glx.cpp
- src/glcontext_glx.h
This change makes bgfx open the default X display in case the user specified a custom window handle, but didn't specify the display. The display pointer is stored in a new ```m_display``` attribute, which is necessary to know if bgfx has to call ```XCloseDisplay()``` or not. I replaced all occurrences of ```(::Display*)g_platformData.ndt``` with ```m_display```.
glcontext_vk.cpp might still have this problem, I didn't look into it though.
I tested this on linux with all of the possible scenarios and it works.
> fixes #1559 - Support opening X display on GLX

- examples/31-rsm/reflectiveshadowmap.cpp
- src/bgfx_shader.sh
- Add shadow 2d array and shadow cube samplers defines for hlsl
- Update comment in the rsm example (specify newer version of texture comparison flag name)
> Add shadow 2d array and shadow cube samplers defines for hlsl

- tools/shaderc/shaderc_glsl.cpp
Hi, bkaradzic:
I find a bug that shaderrc will generate wrong shader for matal,  generated code will lose uniform information.
I have fixed this problem.
> fix shaderrc generate wrong shader of matal

- src/renderer_mtl.mm
It doesn't work when submit without indexed buffer on ios/metal.
`draw.m_numVertices` may be `UINT32_MAX` here.
> We should use numVertices here rather than draw.m_numVertices

- src/renderer_gl.cpp
it was only unbinding `GL_DRAW_BUFFER` when the vbo target could be either `GL_DRAW_BUFFER` or `GL_DRAW_INDIRECT_BUFFER`.
see https://github.com/bkaradzic/bgfx/blob/6bff345637c981136e4694b6dd3cac493be63adc/src/renderer_gl.h#L1186 for detail
> VertexBufferGL unbinds correct target if destroyed

- src/renderer_mtl.mm
I have removed m_backBufferDepth and m_backBufferStencil, as they were not used anymore.
I have removed m_backBufferColorMsaa, it was used just here here(https://github.com/bkaradzic/bgfx/blob/master/src/renderer_mtl.mm#L1569), but inside the block swapChain->m_backBufferColorMsaa was used. 
I have removed m_backBufferPixelFormatHash. It was used just here (https://github.com/bkaradzic/bgfx/blob/master/src/renderer_mtl.mm#L1734). It wasn't even initialized. I think the hash for backbuffer is 'm_mainFrameBuffer.m_pixelFormatHash'.
> fixed metal backbuffer issues

- scripts/shaderc.lua
- tools/shaderc/shaderc_spirv.cpp
I have added legalization. It fixed the texture write access problem for MSL. I have added it for spirv output too, because as far as I can understand glslang can generate invalid spirv output when using hlsl input.
see warning here:
https://github.com/bkaradzic/bgfx/blob/master/3rdparty/glslang/hlsl/hlslParseHelper.cpp#L9969
Diff is terrible this time too. I have just added an extra indent for success path.
> added spirv legalization

- tools/shaderc/shaderc.cpp
Fix for a crash I encountered when using shaderc in release mode when compiling a shader with incorrect input attributes. 
bx::findIdentifierMatch will run through the end of the list, as there is no closing NULL to stop the iteration, causing a crash in release mode, and resulting in shaderc exiting out without printing any errors.
> Crash fix for shaderc.cpp in release mode.

- tools/shaderc/shaderc_spirv.cpp
It seems reflection doesn't have a way to query used(live) samplers.
> Fix for 'used samplers was converted to static'

- examples/08-update/update.cpp
- src/renderer_mtl.h
- src/renderer_mtl.mm
Fixed issue: https://github.com/bkaradzic/bgfx/issues/1618
08-update: added a cube that has a texturecube that is rendered using framebuffer attachment. It looks the same as the one whose texture is updated with compute shader.
> Metal fb attachment

- src/renderer_d3d12.cpp
WINRT version doesn't compile due to typo
> Fixed missing paren on line 2227 for WinRT

- src/renderer_d3d9.cpp
Summary
=======
Adding support to `bgfx::updateTexture` for D3D9 to properly handle BCn texture formats.
Description
===========
In testing I found that compressed texture formats (BCn) aren't supported well in D3D9. Namely, I ran into corruption issues when trying to upload data. I deduced that this is because of three reasons:
1. The pitch is not calculated correctly for a block compression format.
2. The number of "lines" (y) to loop over to memcpy to the locked rectangle doesn't take block height into consideration.
3. For BC4/BC5 formats, the locked pitch returned doesn't accurately represent the actual pitch of the data.
To solve this, I have added a helper function `useD3D9Pitch` to encapsulate the check for BC4/BC5 (so that we can reference it in multiple places). And I created a …
> Correct pitch usage for D3D9 updateTexture calls.

- examples/37-gpudrivenrendering/cs_gdr_copy_z.sc
- examples/37-gpudrivenrendering/cs_gdr_downscale_hi_z.sc
- examples/37-gpudrivenrendering/cs_gdr_occlude_props.sc
- examples/37-gpudrivenrendering/cs_gdr_stream_compaction.sc
- examples/37-gpudrivenrendering/gpudrivenrendering.cpp
This fixes the first pass ('copy') of Z Buffer downscale for OpenGL.
It was handled with cs_gdr_downscale_hi_z.sc now it is handled with cs_gdr_copy_z.sc using sampler texelfetch instead of imageLoad.
Also fixed coordinate differences.
NOTE: On OpenGL there are still has problem with flat varying. It seems shaderc only adds flat to vs or fs, not both which causes link error.
Needs shader recompile.
> 37-gpudrivenrendering fix for OpenGL

- examples/common/entry/entry_glfw.cpp
- examples/common/entry/entry_sdl.cpp
- scripts/genie.lua
- src/glcontext_egl.h
The SDL and GLFW entries can now use Wayland by passing `--with-wayland` to genie.
> Add Wayland support to SDL and GLFW entry backends.

- 3rdparty/dear-imgui/widgets/gizmo.inl
To test the gizmo issue, you can use the particles example.
Comment line 1436 in gizmo.inl and then in particles.cpp, change the gizmo op to SCALE and right before calling gizmo in Update, apply some angles in the emitter uniforms. At this point the gizmo handles will be difficult to use.
Revert all the above to see the fix in action.
> ImGuizmo updates and fix for gizmo issue

- src/amalgamated.cpp
I was using amalgamated.cpp with my build system and the commit on https://github.com/bkaradzic/bgfx/commit/9f7c3281e1ae0e3074f171a74c8c91e655d92138 did not add the new renderer to the file, causing a build error. I've added the missing renderer to the file to fix it.
> Adds missing renderer_nvn.cpp to amalgamated.cpp

- examples/common/bgfx_utils.cpp
- examples/common/bgfx_utils.h
bgfx_util :: loadTexture only support BGFX_SAMPLER_* with uint32_t flags,
while bgfx::createTexture use uint64_t flags to support both TEXTURE & SAMPLER flags
> loadTex support 'BGFX_TEXTURE_*' flags for texture creation

- examples/13-stencil/stencil.cpp
- examples/14-shadowvolumes/shadowvolumes.cpp
- src/bgfx.cpp
- src/renderer.h
- src/renderer_d3d11.cpp
- src/renderer_d3d12.cpp
- src/renderer_d3d9.cpp
- src/renderer_gl.cpp
- src/renderer_mtl.mm
Use of bx::uint32_cnttz with 0 results in undefined value.
> FIX asan error (false positive).

- src/glcontext_nsgl.mm
- src/renderer_mtl.mm
I'm using bgfx in my application, along side Qt.
This is needed for interop between bgfx and Qt.
Qt has an API to get the native handle from a UI widget, called QWidget::winId(). However on mac, this returns a NSView and not an NSWindow. My patch updates the bgfx backend, so that it can accept both NSView and NSWindow in bgfx::PlatformData.nwh.
> Add support for using NSView for platform window handle

- src/renderer_d3d11.cpp
- src/renderer_d3d12.cpp
- src/renderer_d3d9.cpp
- src/renderer_gl.cpp
- src/renderer_mtl.mm
The logic is now that vertex decl in the draw call always overrides/aliases the one in the vertex buffer, if present.
Examples still look correct on my machine.
> Implement aliasing vertex buffer with different vertex declaration.

- src/renderer_mtl.mm
Our program raise an error :
```
-[MTLVertexDescriptorInternal newSerializedDescriptor], line 825: error 'None of the attributes set bufferIndex to 2, but MTLVertexDescriptor set buffer layout[2].stride(12).'
```
I found a similar issue https://github.com/hugoam/mud/issues/7 reported.
We use 2 streams, but 1 didn't use any `Attrib` for some program.  This patch can fix this issue.  
Btw, why `vertexDesc.attributes[loc].bufferIndex`  is base 1 ? Is `vertexDesc.layouts[0]` reserved for other use ? 
I saw `bufferIndex` can be 0 in a metal example https://github.com/metal-by-example/sample-code/blob/master/objc/07-Mipmapping/Mipmapping/MBERenderer.m#L59 .
> Don't set layouts when the stream not used

- src/renderer_gl.cpp
If the opengl render has been modified to allow glClipControl to create a hetrogeneous depth buffer then anything blitted using the internal blit() functions will set to z=-1 and culled, making things such as debug text invisible. This fixes this
> Fixes blitter not taking into account homogeneousDepth

- examples/common/imgui/imgui.cpp
- examples/common/imgui/imgui.h
I'm writing a bgfx imgui lua bindings, and I found `imguiBeginFrame` only support ascii char now.
This PR add a unicode inputChar support by `io.AddInputCharactersUTF8`.
btw, I include  `<dear-imgui/imgui_internal.h>` because I use the internal function `ImTextStrToUtf8`. I'm not sure is there any equivalent function in `bx`. (Converting a unicode code point to utf-8 string)
> unicode inputChar support for imguiBeginFrame

- examples/common/entry/entry_windows.cpp
`WM_CHAR` was not handled correctly.
1. The window is create in ANSI mode, so `WM_CHAR` can't received unicode code point. `WideCharToMultiByte` will not get the UTF-8 string.
2. `_wparam` is a `WPARAM`, it's not a 16bit (WCHAR) integer. `(LPCWSTR)&_wparam` has some endian problem. Of cource, Windows always run on the little-endian platform :)
3. We should handle surrogate pairs. For example, the emoji U+1F604 😀 , it is posted by two `WM_CHAR` message. See https://github.com/bkaradzic/bgfx/pull/1756
> UTF-8 support for windows entry

- examples/common/imgui/imgui.cpp
- examples/common/imgui/imgui.h
1. I found io.AddInputCharacter can handle unicode code point, so we don't need  `AddInputCharactersUTF8` .
2.  We should not call  `AddInputCharacter` where no char message, because  it will push a message to a internal queue of imgui, and 0 is a valid char. So I change the default value of `_inputChar` to -1.
3. Actually, bgfx haven't handle input char now (Always use the default value), but my binding use this API `imguiBeginFrame` .
> AddInputCharacter can handle Unicode

- scripts/genie.lua
- scripts/texturev.lua
This just fixes the bgfx genie scripts to work with any xcode project version, rather than just xcode4, particularly as the makefile is currently using xcode8 :)
> Generalise genie xcode4 cases to apply to all xcode project versions.

- include/bgfx/c99/bgfx.h
- scripts/temp.bgfx.h
There are C++ APIs  `xxxHandle::IsValid`  https://github.com/bkaradzic/bgfx/blob/master/include/bgfx/bgfx.h#L18
But there is no C99 equivalent , this macro `bgfx_handle_is_valid` can check whether a handle is valid.
> Add C99 api(macro) BGFX_HANDLE_ID_VALID

- src/renderer_gl.cpp
If g_caps.homogeneousDepth is false then clearing MRT buffers fails, as MRT buffers are cleared by rending a quad over the buffer with z = -1, which is rejected via clipping. This is fixed by adding a check
> Fixed MRT buffers not being cleared if homogeneousDepth is disabled

- examples/common/entry/entry_winrt.cx
Use std::lround() instead to avoid compilation error.
> Fix compilation of example entry_winrt.cx on VS2017.

- src/renderer_d3d11.cpp
- src/renderer_d3d12.cpp
- src/renderer_gl.cpp
When both SRGB and MSAA are enabled, DX11 & 12 fail to intialize, and OpenGL use a non-SRGB backbuffer.
This fix produce the expected behaviour on my computer, although I have no idea if this is the correct way to do it.
I haven't checked the other renderers.
> Use SRGB texture format on backbuffer when MSAA is enabled (DX11, DX12, OpenGL)

- examples/37-gpudrivenrendering/gpudrivenrendering.cpp
Skip the first frame because the content of m_drawcallInstanceCounts is uninitialized,
and the atomicAdd used in RENDER_PASS_OCCLUDE_PROPS_ID can produce random results.
Fixes #1794
> Fix gpudrivenrendering example on Linux

- examples/common/entry/entry_asmjs.cpp
- makefile
- src/amalgamated.cpp
- src/glcontext_html5.cpp
- src/glcontext_html5.h
- src/renderer_gl.cpp
- src/renderer_gl.h
This uses the emscripten API to directly create a canvas webgl context, instead of going through the EGL compat layer.  It also does some annoying work around GL errors to work around an emscripten bug; this is being fixed on the emscripten side, but it would only be present in the very latest emscripten.
(The double-error bug was present even before; I doubt bgfx debug builds worked fully with emscripten without some hacking.  Or at least, they may have "worked" because debugBreak did nothing on emscripten before...)
> Create HTML5/Esmscripten glcontext

- src/glcontext_eagl.mm
During compilation for iOS using OpenGLES the following errors are thrown for file src/glcontext_eagl.mm.
```
error: cast of C pointer type 'void *' to Objective-C pointer type 'CAEAGLLayer *' requires a bridged cast
...
```
Fix: Add missing `__bridge` keyword for void-pointer cast (see http://clang.llvm.org/docs/AutomaticReferenceCounting.html#bridged-casts )
```
error: 'release' is unavailable: not available in automatic reference counting mode [context release]; 
```
Fix: Remove context release which is no longer needed according to ARC standard (see https://en.wikipedia.org/wiki/Automatic_Reference_Counting )
> Fix compile time errors for objective-c using opengles

- bindings/cs/bgfx.cs
- scripts/bindings-cs.lua
Couple small fixes:
- make it a partial static class instead of struct
- make everything public, but put it in a namespace
- allow for users overriding DllName (by defining `BGFX_CSHARP_CUSTOM_DLLNAME` and providing a `public static partial class bgfx { const string DllName = ... }` in another cs file that the build with.
> Make c# bindings bgfx a static class; make it public; put it in a namespace

- bindings/cs/bgfx.cs
- scripts/bindings-cs.lua
- support arrays (GPU array had to move to uint, as c# does not allow fixed size struct arrays) 
- move chars and bools to bytes
- marshal return string right 
- add Count to enums 
(those are all the changes i needed to get it working for il2cpp etc. for the small subset we are using for now)
> fix some c# bindings gen

- bindings/cs/bgfx.cs
- scripts/bindings-cs.lua
Replacing bools as bytes is not needed for parameters, only in structs. 
They unfortunately have to be bytes in structs, because if they are bools with a MarshalAs we can no longer take pointers to the structs.
> c# bindings: bring back bool as params, only replace by byte in structs. 

- src/glcontext_egl.cpp
> Return the current surface to the previous one after FBO create / destroy on android

- src/bgfx.cpp
Issue was reported by @PyryM 
bgfx.cpp has compile error on XCode 11 beta. I was able to reproduce this in latest (non-beta) XCode with renaming bgfx.cpp to bgfx.mm, that triggered strict objc_msgSend checking. It seems XCode 11 will check this rule in cpp files too. 
Info about strict checking and how to fix it:
https://stackoverflow.com/questions/27771345/what-exactly-does-enable-strict-checking-of-objc-msgsend-calls-mean
Issue:
../../../src/bgfx.cpp:2265:11: fatal error: no matching function for call to
'objc_msgSend'
pool = objc_msgSend(obj, sel_getUid("init") );
^~~~~~~~~~~~
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/objc/message.h:63:1: note: 
candidate function not viable: requires 0 arguments, but 2 were provided
objc_msgSend(void /* id self, SEL op, ... */ ) …
> Fixed objc_msgSend in strict checking mode

- examples/common/nanovg/nanovg_bgfx.cpp
Your cleanup commit (https://github.com/bkaradzic/bx/commit/49bd00e4461f27baecc42195943d81a624bc2f29) reordered the arguments of `bx::cleanup`, but the usage of it in bgfx wasn't updated accordingly. There was only one usage, being nanovg_bgfx.cpp. I fixed the order of the arguments in the calling code.
Too validate the bug, run the nanovg example. This crashes with a heap-buffer-overflow error.
Cheers!
> Fixed gather usage after cleanup commit in bx.

- src/renderer_vk.cpp
- src/renderer_vk.h
Hello, this is the 2nd PR of my vulkan backend implementation
- VkStructure initialization becomes more explicit now.
- Samplers are cached by using sampler flags and the number of mipmap as a hash key.
- A framebuffer is created for color / depth attachments.
- The render pass is created and cached for attachment information, which is used for creating framebuffer.
- Fix several bugs in the texture update routine
- The executable examples:
* Complete: 1, 2, 3, 4, 6, 7, 9, 10, 11, 12, 13, 14, 18, 19, 20, 23, 27, 28
* Partial
- 8: some of cubes that should use compute shader are not shown.
- 15: shape of shadow is not correct
- 16: validation error occurred while switch the type of light
Thank you for reading.
> vulkan backend implementation 2 - framebuffer / mipmap / cached sampler

- src/renderer_vk.cpp
- src/renderer_vk.h
Hello again! This is the 3rd PR for my vulkan backend implementation.
- implement blit operation
- implement debug draw
- implement instancing (roughly)
- 00-helloworld and 05-instancing start to work!
- In 08-update, the second cube (which represents the usage of blit function) can be drawn.
- Currently, I've just bound the instance data with the sequential order. I think that method this cannot work if the instance data attributes are not sequential order.
```glsl
// this works
$input a_position, a_color0, i_data0, i_data1, i_data2, i_data3, i_data4
...
// this may not work
$input a_position, a_color0, i_data1, i_data0
```
- So, should I consider the disordered instance attributes? If so, I should modify the shader compiler to store the information about instance attributes.
Thank you …
> vulkan backend implementation 3: blit, debug draw, and instancing

- src/renderer_vk.cpp
Hello, this is the 4th PR of my vulkan backend implementation (#274) !
- Multiple vertex streaming is implemented! In order to support this, pipeline creation process and bindings of vertex buffers are modified.
- Some additional condition handling codes are added for devices that don't have debug_utils extension (it was needed when I run the examples on my android device, which does not have `EXT_debug_utils` extensions...)
- After enumerating present modes that are supported by hardware, choose the preferred present mode first and set it.
* currently, the order of present modes is FIFO, FIFO relaxed, Mailbox, and Immediate.
* I referred the vulkan reference book to pick FIFO at first.
- During render pass creation, attachment's load and store operations are set by LOAD and STORE, …
> vulkan backend implementation 4: multiple vertex streaming

- src/renderer_vk.cpp
related issue: https://github.com/bkaradzic/bgfx/issues/274#issuecomment-520246171
- If vertex streams does not have attributes that are required by the vertex shader, bind it with default setting on vertex stream 0, like the previous code does.
- Additionally, check the texture's stencil aspect bit with vulkan format, not with bgfx format.
> Vulkan backend: fix bug in input vertex binding 

- src/bgfx_compute.sh
- src/bgfx_p.h
- src/renderer_vk.cpp
- src/renderer_vk.h
- tools/shaderc/shaderc_spirv.cpp
Hello, this is 5th PR of my Vulkan backend implementation (#274) !
- Compute shaders are supported now. (currently example 8 and 24 become working)
- Storage buffer and image variables declared in a compute shader are stored as `UniformType::End`, with descriptor type and binding index on shader compilation.
- So I had to modify the uniform creation step in `bgfx_p.h`, not to create the uniform which has `UniformType::End` type. Please let me know if it would lead to any side effects.
- Storage images would have two image views, one for compute shaders and the other for fragments shaders.
- The example 8 and 24 start to work.
- Fix crash bug when executing examples.
- Optimize render process by caching, i.e. binding infomations
Thank you!
> vulkan backend implementation 5: compute shader

- examples/15-shadowmaps-simple/shadowmaps_simple.cpp
There was an issue with example-15 with vulkan renderer. I have found that it was not a renderer specific problem. Vulkan doesn't expose BGFX_CAPS_TEXTURE_COMPARE_LEQUAL caps so a different code path was used, other renderers had the same issue with disabling shadow sampler path.
Fix was only adding bgfx::touch(0) to force update u_depthScaleOffset uniform, it was skipped otherwise.
For better test coverage I have added an option to disable shadow sampler usage.
> 15-shadowmaps-simple: Fixed float depth packing mode

- src/renderer_vk.cpp
- src/renderer_vk.h
Hello! This is the 6th PR of my Vulkan backend implementation (#274)
- Uniform buffer objects which are set by setUniform() or predefined are now using dynamic uniform buffer.
- Thus descriptor set can be reused if renderBind information or pipeline layout is not changed.
- Allocating and writing descriptor sets is refactored into a function.
- I also tried to cache descriptor set like d3d12 implementation (using something like bindLru in the d3d12 backend), but failed. Maybe descriptor sets are already in a descriptor pool, so allocation and free is fast enough to be in a frame.
- After this optimization, example-17 now start to work, and active scissor rect drawing in example-21 also works. Perhaps the main reason that these examples don't work is the lack of descriptor sets (1024 for …
> vulkan backend implementation 6: some optimization

- src/renderer_vk.cpp
This was hitting debug validation:
`CommandBuffer, Validation, 0:  [ UNASSIGNED-CoreValidation-Image-ZeroAreaSubregion ] Object: VK_NULL_HANDLE (Type = 6) | vkCmdCopyBufferToImage(): pRegion[3] imageExtent of {1, 0, 1} has zero area`
Should have been `uint32_t idealWidth  = bx::max<uint32_t>(1, m_width  >> imageInfos[ii].mipLevel);` etc. but that's redundant since the dimensions are already in `ImageInfo`.
> Use correct texture mip dimensions in Vulkan renderer.

- tools/shaderc/shaderc.cpp
A glsl shader using only the SAMPLER2DARRAY() macro wasn't being detected as using the texture array extension.
> Fixes shaderc texture array usage detection

- src/renderer_gl.cpp
Adds gl_InstanceID (GL_ARB_draw_instanced) support for drivers that don't implement GL_EXT_gpu_shader4 extension (e.g. mesa driver 'i915' on Pentium G3258).
Don't emit the glsl extension GL_EXT_gpu_shader4 if it isn't supported by the driver (e.g. mesa driver 'i915'). In case the shader uses gl_VertexID, bump up the shader version to 130.
> Fixes gpu_shader4 for some drivers

- src/renderer_gl.cpp
Support gl_FragColor with glsl fragment shaders with version 430. (Fixes example 41 using opengl)
> Fix gl_FragColor for example 41

- src/renderer_vk.cpp
This was manifesting as occasionally wrong texture wrap mode.
> Fix uninitialized Vulkan sampler hash.

- src/bgfx.cpp
https://github.com/bkaradzic/bgfx/blob/master/src/renderer_mtl.h#L68
> commandBuffer, commandEncoders are autoreleased objects. Needs AutoreleasePool!
We should enable `AutoreleasePool` in iOS,  otherwise the `commandBuffer` is leaking.
> Fix memory leak in iOS

- src/renderer_gl.cpp
Fixes #1723 
I moved the makeCurrent() call to the top, above all GL calls. Seems safer and more logical, although it's not necessary for the fix.
> End debug group before switching context

- tools/shaderc/shaderc_spirv.cpp
Fixes  #1829 by disabling check.
```
Error: In Vulkan, OpTypeStruct must not contain an opaque type.
%BgfxSampler2D = OpTypeStruct %6 %8
```
> shaderc: Add before hlsl validation option to spirv

- tools/shaderc/shaderc_metal.cpp
- tools/shaderc/shaderc_spirv.cpp
This checks for BgfxSampler names instead of d3d sampler states. Every sampler type is included in check.
On Metal: Textures shouldn't be ever removed with changing to static because compiler gives error for them. Cannot construct texture on global scope.
I did some research on this issue
https://github.com/KhronosGroup/glslang/issues/1727
Samplers/Textures are accessed through a static program variable struct (eg BgfxSampler2D) , The reflection code doesn't see raw samplers/texture as used. It sees the struct and its member variables as used, but as it is a static variable not a uniform (https://github.com/bkaradzic/bgfx/blob/master/src/bgfx_shader.sh#L341 ) it doesn't reports it as live uniform. 
It doesn't seem to be an easy fix for them, so I wouldn't count on it anytime soon. Static …
> Fixed isampler and usampler for metal/spirv

- scripts/shader.mk
- src/bgfx_shader.sh
and fixed a typo.
I have tested it with modifying shaders of 06-bump and 09-hdr. It worked with D3D11 and OpenGL renderer on windows, also checked compilation for metal and spirv. Metal shaders looked ok to me. 
I am unsure about handling 'BGFX_SHADER_LANGUAGE_GLSL >= 130'. 
Current version of handling texture functions seems incomplete too me, but maybe shaderc does some magic for other versions.
https://github.com/bkaradzic/bgfx/blob/72eb05b71e569ba55db0152c054e83abd639acd4/src/bgfx_shader.sh#L546
> Added texture functions with bias parameter

- src/bgfx_p.h
- src/renderer_gl.cpp
- fix mip level computation for asmjs. this needs also the same fix in bimg.
- add support for srgb textures in es2/webgl. this needs a new column in the format table as srgb fmt can now be different that fmt.
> Fix calc num miplevels and add ext_srgb support 

- include/bgfx/defines.h
- scripts/bgfx.idl
- src/renderer_d3d11.cpp
- src/renderer_d3d12.cpp
- src/renderer_gl.cpp
- src/renderer_mtl.h
- src/renderer_mtl.mm
- src/renderer_vk.cpp
Added BGFX_STATE_FRONT_CCW flag to set front facing winding.
Supported by every API but D3D9. 
Some file formats (like GLTF) support changing the winding.
> Front facing

- src/renderer_vk.cpp
This change lets the Vulkan backend support the BGFX_RESET_VSYNC flag so that vsync can be disabled.  This is important for MAME as many emulated systems don't sync at 60.0 Hz and forcing them to do so causes weird behavior.
The original patch is by @couriersud but due to real-life syndrome I'm handling the pull request for him.
> Support disabling Vsync on Vulkan

- src/renderer_vk.cpp
Part of the patch was missing the first time, this should fix it.
> Support disabling vsync on Vulkan, take 2

- src/renderer_mtl.h
- src/renderer_mtl.mm
**The Problem:**
macOS 10.15 does not define the `MTLRenderCommandEncoder setFrontFacing` message.  This warning occurs when compiling:
```
==== Building bgfx-shared-lib (release64) ====
renderer_mtl.mm
In file included from ../../../src/renderer_mtl.mm:10:
../../../src/renderer_mtl.h:431:11: warning: instance method '-setFrontFacing:' not found
(return type defaults to 'id') [-Wobjc-method-access]
[m_obj setFrontFacing:_frontFacing];
^~~~~~~~~~~~~~
```
The examples crash with this error:
```
2019-11-02 20:33:51.954 examplesRelease[90366:433716] -[BronzeMtlRenderCmdEncoder setFrontFacing:]: unrecognized selector sent to instance 0x7ff53007f800
2019-11-02 20:33:51.955 examplesRelease[90366:433716] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: …
```
> Use MTLRenderCommandEncoder setFrontFacingWinding instead of setFrontFacing

- src/renderer_d3d11.cpp
I was playing around and noticed that D3D11 was throwing an exception if BGFX_RESET_SRGB_BACKBUFFER is used in conjunction with BGFX_RESET_MSAA_*
> Fix D3D11 exception with srgb backbuffer

- src/shader_dxbc.cpp
I hit this while trying to do something goofy, trying to sample a cubemap with an offset... which is unsupported as per the HLSL docs. The shader actually compiled ok, but would blow up in this file.
I'd hit the assert down at shader_dxbc.cpp:2032. `BX_CHECK(size/4 == instruction.length, "read %d, expected %d", size/4, instruction.length); BX_UNUSED(size);` This change catches the bad state much sooner. Seems like a good idea to add this in-case the HLSL spec and what you handle in this file diverges.
> add an assert to catch unknown opcodes earlier

- src/renderer_gl.cpp
It appears they are not supported on iOS.
Tested on the full range of iOS devices from iPhone 5s to iPhone 11
> [iOS] disabling D16 and D24S8 texture formats

- examples/common/nanovg/nanovg_bgfx.cpp
- examples/common/nanovg/nanovg_bgfx.h
- src/renderer_mtl.h
- src/renderer_mtl.mm
The internal pointer is interpreted as being of type id MTLTexture.
> Implemented overrideInternal for Metal

- examples/common/bounds.cpp
Currently the Android build fails when following the steps here...
https://github.com/Nodrev/bgfx-android-activity#bgfx-android-activity---android-glue-for-bgfx
...with errors like this the one below.
This fix explicitly makes it call the bx namespace version of sqrt.
`
bounds.cpp
../../../examples/common/bounds.cpp:276:19: error: call to 'sqrt' is ambiguous
_sphere.radius = sqrt(maxDistSq);
^~~~
/Users/oliver/Library/Android/sdk/ndk/21.0.6113669/sources/cxx-stl/llvm-libc++/include/math.h:1074:46: note: candidate function
inline _LIBCPP_INLINE_VISIBILITY float       sqrt(float __lcpp_x) _NOEXCEPT       {return ::sqrtf(__lcpp_x);}
^
../../../../bx/include/bx/inline/math.inl:237:29: note: candidate function
inline BX_CONST_FUNC float sqrt(float _a)
^ …
> Fixed ambiguity calling sqrt

- examples/common/entry/entry_asmjs.cpp
Passing `nullptr` or `0` to emscripten_set_yyy_callback is now incorrect and must be replaced with `EMSCRIPTEN_EVENT_TARGET_DOCUMENT`
Also `canvasX` and `canvasY` are deprecated and their value is now 0, must use `targetX` and `targetY`
> Update entry_asmjs to updated Emscripten html5 API

- src/bgfx_p.h
This was printing something like:
`Invalid handle. createFrameBuffer texture handle handle: 0 (max 2048)"`
The "handle handle" bothered me :)
now prints:
`Invalid handle. createFrameBuffer texture handle: 0 (max 2048)"`
> cleanup: fix redundancy in error message

- src/renderer_gl.cpp
Fixes #2000.
I've applied reverse patch to Cluster's older revision of bgfx and it stopped working (at least on Linux/GLSL/GLX) while logging the following error:
```
[23:02:35][critical] Failed to compile shader.
```
My application logs the same error (through `bgfx::CallbackI`) on newer/current bgfx, so i'm fairly sure this PR is fixing regression of some sorts.
It basically restores branching on shaders with `#version 430` to pre- 0c90be6 version without changing anything else. I've also checked that 41-tess works with this patch.
> Restored old behavior of handling shaders with "#version 430" in them

- src/renderer_vk.cpp
Fixes buffer overrun.
After filling up the wds array, the code writes two more entries.
So the array needs to be enlarged by 2 elements.
> This fixes a buffer overflow in an array of write descriptor sets.

- src/renderer_gl.cpp
Fix case of drawing different indices of same vertex buffer using same
instance data.
This can happen in the case of conditionally drawing subsets of vertex
buffer stored in different index buffers while re-using non-transient
instance buffers.
With the following diff, you can reproduce this bug.
It does three things differently from the instancing example:
1. It uses a dynamic buffer instead of a transient one. For performance reasons, in our application, we only occasionally update the instance buffer based on a dirty flag.
2. We're using two index buffers. In our application, these two buffers represent different components of a mesh, which aren't always shown (e.g. different stages of building a house).
3. It draws the geometry twice. In our application, we don't draw the exact same …
> rebind instance data buffer if index buffer changes

- src/renderer_gl.cpp
Fix case of drawing different offsets of indices of same vertex buffer
using same instance data.
This can happen in the case of conditionally drawing subsets of vertex
buffer stored in different offsets of the same index buffer while re-using
non-transient instance buffers.
This is a follow-up to #1919 for a corner case of using different offsets of the same index buffers.
> rebind instance data buffer if index offset changes

- src/renderer_vk.cpp
Let's try this one more time...
I deleted the old fork, and this is a brand new fork, completely sync'ed.
Last time, I tried fetching upstream changes, but somehow that did not work?
About the patch: worst case, the code uses 2 desciptor sets per sampler, and then two more for vs/fs uniform buffers.
> Properly size the set, so that no overrun happens.

- bindings/cs/bgfx.cs
- bindings/cs/bgfx_dllname.cs
- scripts/bindings-cs.lua
- scripts/genie.lua
This avoids the hacky `BGFX_CSHARP_CUSTOM_DLLNAME` thing that didn't actually ever work properly, and gives people the ability to use the cs file directly as-is even with a custom DllName (by just providing their own second file).
> CSharp bindings: move DllName definition to other, optional file

- src/glcontext_nsgl.mm
- src/renderer_mtl.mm
This is sort of a follow-on from #2001:
- `[nsWindow contentView]` must be called on main thread as well
- all the similar code in `glcontext_nsgl.mm` must have the same treatment
However, all of this (and #2001) introduces a new problem; if `bgfx::frame` is called on the main thread, then if this code is ever hit it will cause a deadlock (because frame will wait for renderFrame to complete, and renderFrame will hit this code which wants to execute on the main thread).
I would actually suggest that we ditch all of this and just restrict what can be passed as `nwh`, and stop allowing it to be a NSView/NSWindow:
- For `GlContext`, require that `nwh` is a ` NSOpenGLView*`, and that `context` is a `NSOpenGLCOntext*`.
- For Metal, require that `nwh` is a `CAMetalLayer`.
The existing code could …
> Move more Mac UI-thread-only calls to main thread

- examples/08-update/update.cpp
- src/renderer_d3d11.cpp
- src/renderer_mtl.mm
Description labels overlap geometry to save space, but can be toggled on/off to see textures only. 
Added row of cubes whose compressed texture is created with empty content then updated using bgfx::updateTexture2D.
Fixed default srcPitch in d3d11 renderer for compressed textures. I think for 3d compressed textures slicepitch needs modification too, but as I wasn't be able test I haven't modified it.
I have tested on d3d11 and d3d9 and it works. I will test it on metal and (hopefully) fix issues. (https://github.com/bkaradzic/bgfx/issues/2004)
Edited:
I couldn't figure out how to upload mips that have smaller then block size dimensions on D3D11. 
Edited2:
I have added second commit with fix for metal renderer.
> Added description labels to 08-update

- src/renderer_mtl.mm
I am not sure why this code was commented, but it took me a while to understand why MSAA is not working for Metal (sample count is set to 1 for all MSAA settings). I reenabled it and it works.
> Reenable MSAA for Metal

- include/bgfx/c99/bgfx.h
WinRT dll should also use __declspec to build.
> Let WinRT dll Build

- src/renderer_d3d11.cpp
Modified CreateShaderResourceView() calls to use descriptors from prior SRVs to handle cases where SRV format cannot be directly deduced from texture format. This happens when using D3D11's typeless texture formats, which can be introduced into a BGFX app using overrideInternal.
> Enable overrideInternal with typeless textures for D3D11

- src/renderer_d3d12.cpp
- src/renderer_d3d12.h
Align to the overrideInternal in other renderers.
> Implement the overrideInternal in D3D12 renderer

- bindings/cs/bgfx.cs
- scripts/bindings-cs.lua
There's currently no good way to check if a handle is valid from the C# bindings.  This adds a `Valid` property.
> Add Valid property to handle types for C# bindings

- README.md
Hi! I've published a set of Free Pascal bindings for BGFX [here.](https://github.com/Akira13641/PasBGFX)
The API unit is a machine-generated-then-hand-tweaked direct translation of the C99 headers. I've also so far committed a port of the "Hello World" example (using a simple SDL2-based example runner I wrote), and intend to work on converting more of the examples as well.
This PR just adds the repo link to `readme.md`.
> Add Pascal (Free Pascal) bindings to the list

- src/renderer_d3d11.cpp
- src/renderer_d3d12.cpp
Enable to create RTVs and DSVs from a slice of texture array, with or without MSAA, in D3D11 and D3D12 renderer. Also skip the clear after creation in D3D12 renderer.
> Fill some blanks in RTV and DSV creation

- src/renderer_gl.cpp
- tools/shaderc/shaderc_glsl.cpp
Fixes #1891
In a glsl pixel shader, when sampling a 2DArray with `texture2DArray` while using a `flat` varying, shaderc will generate of `textureArray` calls instead of `texture2DArray`.
And bgfx  will fail to load the produced shader while compiling with opengl:
```
[2019-09-24 11:14:26.525] [debug] bgfx: bgfx/src/renderer_gl.cpp:5904: BGFX Failed to compile shader. 0: 0(45) : error C1503: undefined variable "textureArray"
0(45) : error C1503: undefined variable "textureArray"
0(47) : error C1503: undefined variable "textureArray"
0(47) : error C1503: undefined variable "textureArray"
0(49) : error C1503: undefined variable "textureArray"
0(49) : error C1503: undefined variable "textureArray"
```
When the `flat` qualifier is in the source, `glslopt` will generate glsl 130 code.
This, …
> Fix to errors when mixing flat and texture2DArray

- src/renderer_d3d12.cpp
Callers may need to access the default D3D12 command queue. Store it to the device so that it can be exposed.
Related to #2043
> Store the command queue into device in D3D12 renderer

- src/renderer_d3d11.cpp
- src/renderer_d3d12.cpp
1. A crash in D3D11 renderer when create a texture with flag BGFX_TEXTURE_RT_WRITE_ONLY then override it, bcause m_srv is NULL.
2. In headless mode, RendererContextD3D12::m_swapChain is NULL, clear it resulting a D3D12 debug error
> Fix a couple framebuffer related bugs in D3D renderer

- src/renderer_gl.cpp
Avoid querying GL_MAX_ARRAY_TEXTURE_LAYERS and GL_MAX_LABEL_LENGTH if it is known at compile time that the GL context is not new enough to have them.
This reduces GL error noise e.g. when creating WebGL contexts.
> Avoid querying GL_MAX_ARRAY_TEXTURE_LAYERS and GL_MAX_LABEL_LENGTH

- src/renderer_gl.cpp
GL_RGBA4 and GL_RGB5A1 texture formats use GL_RGBA as base format and internalFormat in GLES2. 
Using GL_BGRA as format and internalFormat is from the GL_BGRA extension.
> Fix RGBA4 and RGB5A1 format & internalFormat

- src/bgfx.cpp
Fix for https://github.com/bkaradzic/bgfx/issues/730
> Keep debug text colours the same with sRGB backbuffer on/off

- src/config.h
Tested on Catalina only, don't see why it shouldn't work on other x86 versions of MacOS
> Added X86 to platform to allow metal support on iOS Simulator

- src/renderer_vk.cpp
When submitting a draw with just a vertex buffer and no index buffer, `RendererContextVK::submit` uses an unititialized vertex layout to calculate the number of vertices and crashes.
> Fix Vulkan renderer crash when submitting without index buffer

- src/bgfx_shader.sh
This change correctly expands macros in resource definitions when compiling with HLSL shader profile 4_0 and below, including targetting SPIRV via glslang.
With shader profile 5/GLSL you could already do the following:
```c++
#define SAMPLER_COLOR 0
SAMPLER2D(s_texColor, SAMPLER_COLOR);
```
but with shader profile <= 4 it would concatenate the identifier, yielding something like `uniform SamplerState s_texColorSampler : register(sSAMPLER_COLOR)`.
The added CONCAT macro is the usual [token pasting with macro expansion](https://stackoverflow.com/questions/12630548/c-expand-macro-with-token-pasting) but the double CONCAT with 0 seems to be needed for fcpp to produce the correct result.
I've only fixed macro expansion for this specific case because it's the only place where I think it makes …
> Macro expansion for registers with shader profile <= 4

- src/renderer_vk.cpp
This PR adds support for BGFX_RESET_SRGB_BACKBUFFER and BGFX_TEXTURE_SRGB on the Vulkan backend.
Support for sRGB textures was already 99% there, just needed to select the correct format based on the texture flags. Maybe there's a reason it wasn't done by default? Pinging @rinthel just to make sure
Also removed instance layers during device creation, those are deprecated and ignored.
> Vulkan: enable sRGB backbuffer and sRGB textures

- src/renderer_vk.cpp
This fixes a bug where `bgfx::setBuffer` called with an index buffer ended up binding a random vertex buffer.
> Vulkan: bind correct compute index buffer

- examples/common/entry/entry_windows.cpp
I assume that with setMouseLock I can enable/disable locking for the same window, but
when calling setMouseLock(window, true) then setMouseLock(window, false) the second call did nothing because of `if (_hwnd != m_mouseLock)` check at the beginning of the function.
Also m_mouseLock was never set back to zero for the false case. So the message processing function was stuck in lock mode.
https://github.com/bkaradzic/bgfx/blob/master/examples/common/entry/entry_windows.cpp#L769
> setMouseLock windows fix for  _lock = false case

- src/renderer_vk.cpp
Apparently `vkAllocateMemory` returns different errors if validation layers are on. Changed it to just checking if it succeeded or not before trying the next memory type.
> Fix #2071 again

- src/renderer_gl.cpp
Optimize glUniform1iv and glUniform4fv to use faster glUniform1i and glUniform4f on WebGL.
> Optimize glUniform1iv and glUniform4fv

- src/renderer_gl.cpp
- src/renderer_gl.h
This was tested manually against WebGL 1 and 2 contexts.
> Fix OpenGL ES texture formats and remove runtime texture probing on WebGL.

- src/renderer_gl.cpp
when trying to use a depth texture from a MSAA frameBuffer, the depth component of the frame buffer wasn't being resolved (code was skipping). This should resolve the issue. Added logic to skip if the depth texture has RT_WRITE_ONLY flag so that there's no unecessary glBlitFrameBuffer call if the depth texture isn't being used.
> make sure depth textures are resolved as well when blitting frameBuffer

- 3rdparty/glsl-optimizer/src/glsl/ir_print_glsl_visitor.cpp
- src/bgfx_shader.sh
- src/renderer_gl.cpp
- src/renderer_gl.h
- tools/shaderc/shaderc.cpp
Hi!
I added support for the OpenGL ES extension OES_EGL_image_external. We use this on Android to be able to render textures from the camera and video player without copying them to a regular Texture2D.
This adds a function "bgfx::overrideInternal(ptr, target)" to the api, that allows the user to override the sampler target, and a "SAMPLEREXTERNAL" macro to use in the shaders.
I also patched glsl-optimizer to correctly handle the uniform "samplerExternal".
On backends other then OpenGL ES, the SAMPLEREXTERNAL is treated as a regular SAMPLER2D
Any feedback is welcome : )
> Added support for the extension OES_EGL_image_external(_essl3) for GLES2

- src/glimports.h
- src/renderer_gl.cpp
- src/renderer_gl.h
Manage a cache of current uniform state to avoid reuploading state that is already on the GPU side.
In a WebGL build, this was observed to reduce the number of GL calls from ~21k/frame to about ~7.5k/frame.
> Avoid redundant uniform uploads

- tools/shaderc/shaderc.h
Currently `const char * str` gets converted to a StringView when its passed to `bx::strFindNl`, incurring a strlen. We have the data to calculate the strlen and fully construct the StringView.
> shader read optimization

- src/renderer_gl.cpp
- tools/shaderc/shaderc.cpp
GpuShader5 extension isn't supported on fragment shaders.
Bumps the GLSL version to support the 'bitsTo' functions when present on the shader.
> Fix GpuShader5 extension on Intel and support 'bitsTo' functions

- examples/15-shadowmaps-simple/fs_sms_shadow.sc
- src/renderer_vk.cpp
- Remove some dead code
- Fix a bug where we are attaching a color attachment while the frame buffer does not have one
- Fix a bug where the shader is writing to a color attachment while the frame buffer does not have one
- Check that there is a fragment shader in some cases where we just assumed that there was one
> Vulkan cleanup and minor bug fixes

- src/renderer_vk.cpp
- src/renderer_vk.h
This fixes a bunch of bugs related to Vulkan texture creation and update
Currently, running 06-update example crashes on my machine for a bunch of reasons
- Creating 3D textures is broken due to memory corruption by writing to an undersized array
- When a compressed format is not supported, the TextureVK::update function does not do any conversion to the actual texture format, and it breaks
- Also it's a minor tweak, but storing the formats as Enums doesn't cost anything and helps tremendously while debugging (instead of seeing an integer value)
- Updating 3D textures might be broken in general, I'm not even sure my code is correct, but nothing in the examples tests that
> Fix Vulkan texture update/upload

- src/renderer_webgpu.cpp
- src/renderer_webgpu.h
I was in the process of trying to fix this bug when you merged my PR 😄 
My changes to how uniform buffers are written to (removing the deprecated `setSubData` function and use pre-mapped staging buffers instead) introduced a bug that I was trying to isolate.
We were sending the copy of the staging buffer to the uniform buffer *after* the render commands. So we need two different command encoders to make sure that we stage the uniforms *before* the render commands while preserving the same render loop structure.
This does this change, which fixes the remaining bugs introduced while I was addressing the comments of the PR.
> WebGPU - Fix order of uniforms staging and render commands

- makefile
The [bgfx documentation states](https://bkaradzic.github.io/bgfx/overview.html#sdl-glfw-etc):
> You can use --with-sdl when runnning GENie to enable SDL2 integration with examples: genie --with-sdl vs2012
This change makes this possible when calling `make`. If a variable called `WINDOWING_LIBRARY` is set and its value is `sdl` it adds `--with-sdl` to the GENie invocation, and if its value is `glfw` it adds `--with-glfw` to the GENie invocation. In all other cases the previous behaviour is used.
The following examples are all valid:
```
make projgen
make projgen WINDOWING_LIB=sdl
make projgen WINDOWING_LIB=glfw
```
> Adds the ability to pass a WINDOWING_LIB variable to 'make' which sets `--with-sdl` or `--with-glfw`

- src/renderer_webgpu.cpp
- tools/shaderc/shaderc_spirv.cpp
Many small compilation and bug fixes to the WebGPU backend
(BGFX_CONFIG_DEBUG_ANNOTATION must stay off in that file for now because WebGPU is strict about always calling push/popDebugGroup in pairs and the current code is incorrect in that regard. Well that and it's not even implemented in Emscripten)
> WebGPU various small fixes

- examples/common/entry/entry_html5.cpp
- makefile
- scripts/bgfx.lua
- scripts/genie.lua
- scripts/geometryv.lua
- scripts/texturev.lua
- src/bgfx_p.h
- src/glcontext_html5.cpp
Update examples to build on Emscripten Wasm. Add separate wasm and wasm2js targets.
> Update examples to build on Emscripten Wasm.

- scripts/bgfx.lua
- scripts/genie.lua
bgfx defines many config macros in `src/config.h` . If it allows changing these macros before generating projects would be better.
For examples, we can use
```
make BGFX_CONFIG=MAX_COMMAND_BUFFER_SIZE=131072:MAX_INSTANCE_DATA_COUNT=6
```
to change `BGFX_DEFINE_MAX_COMMAND_BUFFER_SIZE` and `BGFX_DEFINE_MAX_INSTANCE_DATA_COUNT`.
> Allow passing config macros from env

- makefile
I can't build bgfx today
```
../bx/tools/bin/windows/genie               --with-examples                            --gcc=asmjs           gmake
Error: invalid value 'asmjs' for option 'gcc'
stack traceback:
[C]: in function 'error'
[string "_WORKING_DIR        = os.getcwd()..."]:63: in function '_premake_main'
```
Option asmjs changes to wasm2js in this commit : 
https://github.com/bkaradzic/bx/commit/8d1e6bbe75639d5af80d4145a4f26254aa786aae
> Change asmjs to wasm2js

- examples/42-bunnylod/bunnylod.cpp
- examples/42-bunnylod/progmesh.c
- scripts/genie.lua
I reimplement https://github.com/dougbinks/BunnyLOD in bgfx today.
There are still some issues: 
1. I use the shaders `vs_picking_shaded` and `fs_picking_shaded` of `30-picking`. 
2. Init is too slow ( 8 seconds in my computer) , because the algorithm is O(n^2) , and bunny.bin have more than 100k vertices. A simpler mesh would be much faster.
3. This LOD algotithm need removing the vertices with the same position. The exist `bunny.bin` have many vertices with the same posiotions (different normals). I wrote functions `findDuplicateVertices` and `mergeVertices` to merge these vertices. It's O(n^2) , too.  But I think it can be done offline.
> Add example 42 : BunnyLOD

- examples/42-bunnylod/bunnylod.cpp
1. Use bgfx::weldVertices instead
2. Cache data to temp/bunnylod.cache after first run.
> Improve example 42

- src/renderer_gl.cpp
Broadened bypass mechanism for GLSL default headers in the OpenGL renderer. This reflects the fact that, if the first line of a shader is already a #version declaration, we never want to write lines above that regardless of what version is declared.
The motivation for this change is that Babylon Native uses a custom pipeline to cross-compile shaders and make them compatible with bgfx at runtime. An obstacle we encountered was that, when our shader output targeted GL version 310 (for Android), the logic in renderer_gl.cpp would write additional information to the tops of our shaders above the `#version` declaration, which the shader compiler would then reject because it doesn't allow for duplicate versions or for code to appear above the version. Noting that there was already a mechanism …
> Broadened bypass mechanism for GLSL default headers

- scripts/bgfx.lua
Fixing android shared library build making target extension ``.dll`` instead on ``.so`` when compiling on windows
> Fix target extension on android for shared-library

- scripts/bgfx.lua
Based on https://stackoverflow.com/questions/47279824/android-ndk-dlopen-failed
> Small fix on soname defining on ldflags

- src/renderer_d3d11.cpp
Fixes for two uninitialized variables:
* m_needPresent is not initialized which causes https://github.com/bkaradzic/bgfx/blob/d86c16213e66669fa33df556d95dc984ae6e049b/src/renderer_d3d11.cpp#L2251 to execute even though it shouldn't.
* m_msaaRt is uninitialized when using `init.platformData.backBuffer`
> Fix some uninitialized variables

- 3rdparty/sdf/sdf.h
When I include sdf.h in my C file, gcc reported
```
bgfx/3rdparty/sdf/sdf.h:116:6: error: conflicting types for 'sdfCoverageToDistance'
void sdfCoverageToDistance(unsigned char* out, int outstride,
^~~~~~~~~~~~~~~~~~~~~
In file included from font_manager.c:11:
bgfx/3rdparty/sdf/sdf.h:55:6: note: previous declaration of 'sdfCoverageToDistance' was here
void sdfCoverageToDistance(unsigned char* out, int outstride, float maxdist,
^~~~~~~~~~~~~~~~~~~~~
```
> fix declaration of sdfCoverageToDistance

- scripts/genie.lua
Changing the xcode platform to just `Native`. This lets xcode handle all the target stuff, and works regardless of target.
> Updating xcode config.

- src/renderer_gl.cpp
I've found this issue while rendering my scene where the last draw call, before the `glBlitFramebuffer` is being called, does have scissoring enabled.
This behavior causes the blit to inherit the scissoring copying only the region within the scissor region. Not sure why, but I noticed that this is being done also on line https://github.com/bkaradzic/bgfx/blob/master/src/renderer_gl.cpp#L3778 but not on the other two calls.
The patch should fix this behavior.
Example of the issue (Left is OK, Right is WRONG):
> OpenGL: Disable scissor testing while blitting framebuffers when MSAA is enabled

- src/renderer_vk.cpp
On some platforms (Windows) the framebuffer size becomes 0x0 when
the window is minimized. This leads to a validation error and
subsequently crashes.
This change correctly cleans up semaphores and the swapchain.
> Fix crash on window minimize on vulkan renderer.

- src/renderer_mtl.h
- src/renderer_mtl.mm
For Metal, when the BGFX_RESET_INTERNAL_FORCE is set with a new native window handle, the swapchain is reinited to reflect the change.
> re-init metal swapchain when providing a new native window handle

- src/renderer_vk.h
Validation will swamp your logs with a warning on every call
> Don't call vkCmdEndDebugUtilsLabelEXT when unsupported

- src/dxgi.cpp
- src/renderer_d3d11.cpp
In master, the swapchain fails to create when BGFX_RESET_SRGB_BACKBUFFER is set, and fails over to DXGI_SWAP_EFFECT_DISCARD.
In this PR, we use the exception listed here: https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/converting-data-color-space
to use a _SRGB format render target view into a non- _SRGB format backbuffer. 
This allows the swapchain to be created successfully with DXGI_SWAP_EFFECT_FLIP_DISCARD.
Also, we make sure to only set DXGI_SWAP_CHAIN_FLAG_FRAME_LATENCY_WAITABLE_OBJECT when using the flip presentation model, as it only works there.
> only use srgb views into non-srgb backbuffers to enable flip

- src/renderer_d3d11.cpp
to talk about current expected behavior instead of previous behavior
> improve explanatory comment about _SRGB backbuffers

- examples/37-gpudrivenrendering/cs_gdr_stream_compaction.sc
When compiling shader cs_gdr_stream_compaction.sc on GCN 1.0 gpus
the following error appears:
> Compute link error: HW_UNSUPPORTED.
> ERROR: Internal compile error, error code: E_SC_NOTSUPPORTED
> Shader not supported by HW
These changes avoid the error.
> Fixes example 37 on Windows using AMD GCN 1.0 gpus

- src/renderer_gl.cpp
This example was broken on Windows and Linux when using OpenGL.
The code path when using immutable compressed textures was wrong.
> Fixes example 08 when using OpenGL

- examples/41-tess/cs_terrain_lod.sc
- examples/41-tess/isubd.sh
- examples/41-tess/terrain_common.sh
The glsl function findMSB is overriden, causing an error on Windows and Linux
when running on AMD or Intel gpus. Nvidia, for whatever reason, seems to allow
overriding the function.
> Fixes example 41 on OpenGL

- examples/42-bunnylod/bunnylod.cpp
- examples/42-bunnylod/fs_bunnylod.sc
- examples/42-bunnylod/makefile
- examples/42-bunnylod/varying.def.sc
- examples/42-bunnylod/vs_bunnylod.sc
Because example 42 was using the shaders from example 07 (callback), which have
input vertex attributes position and color, while the mesh from example 42 has
attributes position and normal, this causes problems on Windows when using
AMD gpus (no bunny mesh would appear on the window).
> Fixes example 42

- tools/shaderc/shaderc_metal.cpp
Fixes #2166. Probably not the very very best solution, but definitely an improvement that fixes most cases I assume. (Counterexample: declare two uniforms on the same line... but that didn't work before either.)
> Fix uniform stripping procedure for unexpected newlines in Metal shaderc.

- src/renderer_vk.cpp
Depends on pull request #2123.
When resizing the window, there's a race condition between the
validation of vkCreateSwapchainKHR's arguments and the actual
size of the window.
This ignores the validation warning when vkCreateSwapchainKHR succeeds.
On some graphic drivers vkAcquireNextImage and vkQueuePresentKHR
may return VK_SUBOPTIMAL_KHR. This is being handled as an error, which
leads to those frames being unnecessarily skipped.
> Vulkan validation fixes

- src/glcontext_nsgl.mm
- src/glcontext_wgl.cpp
These changes to glcontext_wgl.cpp and glcontext_nsgl.mm add support for a non-main thread rendering (renderFrame not called so bgfx creates a render thread) for WGL and NSGL when the developer provides a context.
GLX context already works in this scenario, and the code changes make the behaviour of these three desktop GL backends more similar.
The code changes should not have any backwards compatibility issues, and I have run a wide range of examples with backend set to OpenGL to test. 
These changes are useful when a developer wants to interface their code with an external framework / plugin system which has performance critical code running on the main thread (for example audio plugins), and where either a context has already been created or where the developer needs to create the …
> Add support for non main thread rendering for WGL and NSGL when developer provides context

- bindings/cs/bgfx.cs
- bindings/d/funcs.d
- include/bgfx/c99/bgfx.h
- makefile
- scripts/bgfx.idl
- src/bgfx.idl.inl
The C API `set_vertex_buffer` and `set_dynamic_vertex_buffer` need the 5th parameter `_layoutHandle` as the C++ APIs have.
This patch adds `.layoutHandle "VertexLayoutHandle" ` for `setVertexBuffer` in .idl file. Other (diff) files are generated by `make idl` .
> Add missing VertexLayoutHandle for C APIs

- bindings/cs/bgfx.cs
- bindings/d/funcs.d
- bindings/d/types.d
- include/bgfx/c99/bgfx.h
- include/bgfx/defines.h
- scripts/bgfx.idl
- src/bgfx.idl.inl
Add C APIs:
1. encoder_set_vertex_buffer_with_layout
2. encoder_set_dynamic_vertex_buffer_with_layout
3. encoder_set_transient_vertex_buffer_with_layout
4. set_vertex_buffer_with_layout
5. set_dynamic_vertex_buffer_with_layout
6. set_transient_vertex_buffer_with_layout
See #2249 
All the files in the patch except `scripts/bgfx.idl` is generated by `make idl`.
> add *_with_layout APIs

- src/bgfx_p.h
- src/glcontext_egl.cpp
- src/glcontext_glx.cpp
- src/glcontext_html5.cpp
- src/glcontext_wgl.cpp
gcc (8.2.0) reports a lot of `cast-function-type` warnings like:
```
../../../src/glcontext_wgl.cpp:394:49: warning: cast between incompatible function types from 'PROC' {aka 'long long int (*)()'} to 'bgfx::gl::PFNGLVIEWPORTPROC' {aka 'void (*)(int, int, int, int)'} [-Wcast-function-type]
_func = (_proto)wglGetProcAddress(#_import); \
^
../../../src/glimports.h:12:20: note: in expansion of macro 'GL_EXTENSION'
^~~~~~~~~~~~
../../../src/glimports.h:25:51: note: in expansion of macro 'GL_IMPORT'
#define GL_IMPORT______(_optional, _proto, _func) GL_IMPORT(_optional, _proto, _func, _func)
^~~~~~~~~
../../../src/glimports.h:417:1: note: in expansion of macro 'GL_IMPORT______'
GL_IMPORT______(false, PFNGLVIEWPORTPROC,                          glViewport);
```
This patch add a macro …
> avoid gcc warnings: cast-function-type

- src/renderer_d3d11.cpp
- tools/shaderc/shaderc_hlsl.cpp
Two warnings : 
```
../../../src/renderer_d3d11.cpp: In constructor 'bgfx::d3d11::RendererContextD3D11::RendererContextD3D11()':
../../../src/renderer_d3d11.cpp:3532:8: warning: 'bgfx::d3d11::RendererContextD3D11::m_directAccessSupport' will be initialized after [-Wreorder]
bool m_directAccessSupport;
^~~~~~~~~~~~~~~~~~~~~
../../../src/renderer_d3d11.cpp:3468:8: warning:   'bool bgfx::d3d11::RendererContextD3D11::m_needPresent' [-Wreorder]
bool m_needPresent;
^~~~~~~~~~~~~
../../../src/renderer_d3d11.cpp:660:3: warning:   when initialized here [-Wreorder]
RendererContextD3D11()
^~~~~~~~~~~~~~~~~~~~
```
```
../../../tools/shaderc/shaderc_hlsl.cpp: In function 'bool bgfx::hlsl::compile(const bgfx::Options&, uint32_t, const string&, bx::WriterI*, bool)': …
```
> fix gcc warnings

- examples/common/entry/entry_windows.cpp
`HDROP` is defined in `shellapi.h` which is needed.
> Fix Windows ARM build

- src/renderer_d3d11.cpp
when calling bgfx::init with reset flags that have msaa and sRGB enable, it will casue an D3D error.
the reason is only back buffer from swapchain can create different format with render target view. see： 
https://docs.microsoft.com/en-us/windows/win32/direct3ddxgi/converting-data-color-space
> You can use the ID3D11Device::CreateRenderTargetView method to create DXGI_FORMAT_*_SRGB views on back buffers from a swap chain that you create only with a DXGI_FORMAT_*_UNORM format. This is **a special exception** to the rule for creating render-target views, which states that you can use a different format with ID3D11Device::CreateRenderTargetView only if you created the resource that you want to view with DXGI_FORMAT_*_TYPELESS.
> fix error when create backbuffer with msaa and srgb format

- src/renderer_d3d12.cpp
https://github.com/bkaradzic/bgfx/pull/2042
`ID3D12Resource::GetDesc` has an issue on gcc . This is an old issue, see #1239 .
> Use getResourceDesc instead of GetDesc, See #1239

- src/renderer_d3d12.cpp
>  fix d3d12 error when create backbuffer with msaa and srgb format

- src/glimports.h
- src/renderer_gl.cpp
- src/renderer_gl.h
A texture has to be declared as READBACK to use readTexture(). Also to use a texture as a framebuffer attachment, it must be declared with one of the RT_* flags. A texture cannot be both, so we have to blit between 2 textures to read back.
Blit is implemented in GL with glCopyImageSubData() which is not widely supported (and not at all in WebGL), so this is a proposal for a fallback implemented using an FBO and glCopyTexSubImage2D() which is nearly universal.
This does not support 3D regions, and may have perf issues (not crucial when you're reading back to CPU anyway).
> Add blitting fallback for OGL

- src/renderer_d3d12.cpp
`pRowSizeInBytes` returned from `GetCopyableFootprints` is the actual row width, not the row pitch. This is the only place needing a fix, other code using that function does it correctly. Also a minor change to `requestScreenShot` to unmap without indicating a write, the texture is released right away.
> D3D12: Fix readback

- src/bgfx.cpp
- src/bgfx_p.h
- src/renderer_d3d11.cpp
- src/renderer_d3d12.cpp
- src/renderer_d3d9.cpp
- src/renderer_gl.cpp
- src/renderer_mtl.mm
- src/renderer_vk.cpp
- src/renderer_webgpu.cpp
This PR fixes blitting mips > 0 across all renderers. The problem happened with blits whose extent went beyond the mip size, which is bound to happen with the default `blit` width/height/depth being `UINT16_MAX`.
The blit code in all the renderers used `m_width` of mip 0 to clamp the extent, which is too large and causes all sorts of asserts and errors from the graphics APIs. Clamping now happens in `Encoder::blit` with some extra debug checks, the renderer code just uses those values directly.
I've checked this for D3D11/12, GL and Vulkan with a mipmapped ktx by reading back all the mips and saving them.
Things I didn't check:
- 3D/layered textures
- D3D9 (doesn't support texture to texture blit)
- WebGL
- Metal
There is a minor fix for texture readback for D3D12 with mip > 0, didn't …
> Mip + blit fixes

- examples/common/bounds.cpp
A small PR to fix an ambiguous reference to `sqrt` which will fail compilation under Clang.
> Fixed reference to 'sqrt'

- examples/common/font/font_manager.h
- examples/common/font/text_buffer_manager.h
error: extra ‘;’ [-Werror=pedantic]
> gcc fix warning

- src/renderer_gl.cpp
As detailled on discord, this is necessary for extensions that are not part of the safe set auto-enabled by emscripten.
> Explicitly enable WebGL extensions

- src/renderer_gl.cpp
- src/renderer_gl.h
This change is for coherency with the backend's implementation of [readTexture()](https://github.com/goodartistscopy/bgfx/blob/1ef01f42f4e0dbe96b2536f68955a86baad097a3/src/renderer_gl.cpp#L3228), which always succeed. Right now the else block in this function (the "fallback") is dead code because of the protection in [bgfx::readTexture()](https://github.com/goodartistscopy/bgfx/blob/1ef01f42f4e0dbe96b2536f68955a86baad097a3/src/bgfx.cpp#L4617).
Maybe a cleaner alternative is to acknowledge that the else block is really an emulation, and introduce a compile flag similar to BGFX_GL_CONFIG_BLIT_EMULATION.
So we would have something like this instead
```
g_caps.supported |= (m_readBackSupported || BX_ENABLED(BGFX_GL_CONFIG_TEXTURE_READ_BACK_EMULATION))
? BGFX_CAPS_TEXTURE_READ_BACK
: 0
;
```
I …
> Add opt-in flag for GL tex read back emulation

- tools/shaderc/shaderc.cpp
- tools/shaderc/shaderc_metal.cpp
- tools/shaderc/shaderc_spirv.cpp
This aims to resolve: https://github.com/bkaradzic/bgfx/issues/2285
Updates the `--verbose` option's call to `glslang::SpirvToolsDisassemble` to output based on the spirv target env context being used by Metal and SPIRV.
Also a small alignment fix up in the shaderc help string.
> [shaderc] Metal and SPIR-V disassembly output format option uses associated SPIRV Target Env.

- src/renderer_d3d12.h
This allows bgfx to be built as C++17 with MinGW tools.
> renderer_d3d12.h: Update __mingw_uuidof declaration for C++17

- src/glcontext_html5.cpp
There is an issue that when compiling wasm with BGFX_CONFIG_RENDERER_OPENGLES_MIN_VERSION=30 (to target WebGL2), bgfx will have runtime error(function signature mismatch), and this will fix it.
> Use emscripten_webgl2_get_proc_address for WebGL2 context

- examples/31-rsm/fs_rsm_lbuffer.sc
- examples/31-rsm/fs_rsm_shadow.sc
- examples/common/nanovg/vs_nanovg_fill.sc
- examples/common/shaderlib.sh
- src/bgfx_shader.sh
- tools/shaderc/shaderc.cpp
- tools/shaderc/shaderc_glsl.cpp
- tools/shaderc/shaderc_hlsl.cpp
This pull request fixes #2308 by adding a version preamble to the generated glsl shaders.
It also adds profiles for ESSL targets and limits the set of GLSL profiles.
A side effect is that now shaderc help command now lists all the supported profiles.
Some of the ESSL/GLSL profiles added to the cli are not currently supported by glsl-optimizer.
> Shaderc OpenGL fixes.

- tools/shaderc/shaderc_glsl.cpp
Fixes loading a shaderc shader using `USAMPLER2D`
```
bgfx: bgfx\src\renderer_gl.cpp:4939: BGFX Sampler #1 at location 1.
bgfx: bgfx\src\renderer_gl.cpp:4967: BGFX WARN User defined uniform 's1_countryMap' is not found, it won't be set.
bgfx: bgfx\src\renderer_gl.cpp:4990: BGFX      uniform GL_UNSIGNED_INT_SAMPLER_2D s1_countryMap is at location 1, size 1, offset 0
```
When investigating the output of shaderc, the uniform count does not include the `usampler`.
> shaderc_glsl: parse int samplers like float samplers

- src/bgfx_p.h
In commit [475fea23bc1061461168fd99de41ebc8ee321b3b](https://github.com/bkaradzic/bgfx/commit/475fea23bc1061461168fd99de41ebc8ee321b3b) an optimization was added to skip reset if nothing changes, however this was not honoring the g_platformDataChangedSinceReset flag. This meant that if the windowptr changes between reset calls but the resolution stays the same then we would not properly regenerate and resize textures during reset.
This change just adds a check for g_platformDataChangedSinceReset to rectify this behavior.
> Don't skip reset if platform data has changed

- src/glimports.h
- src/renderer_gl.cpp
The default provoking vertex on OpenGL is the last of a triangle, but
on D3D and Vulkan it is the first.
This patch sets the provoking vertex to the first vertex on OpenGL.
> Make the provoking vertex consistent across OpenGL, D3D and Vulkan

- src/renderer_vk.cpp
When using this compute shader, the following validation errors appear.
This patch fixes the issue.
```
BUFFER_WR(cBuffer, uint, 1);
NUM_THREADS(1u, 1u, 1u)
void main()
{
cBuffer[0] = 0u;
}
```
> ../../../src/renderer_vk.cpp (628): BGFX ---E-       CommandBuffer,
> Validation, 0: Validation Error: [
> VUID-vkCmdBindDescriptorSets-dynamicOffsetCount-00359 ] Object 0: handle =
> 0x7fffe453ec88, type = VK_OBJECT_TYPE_COMMAND_BUFFER; | MessageID =
> 0x82756c54 | vkCmdBindDescriptorSets(): Attempting to bind 1 descriptorSets
> with 0 dynamic descriptors, but dynamicOffsetCount is 1. It should exactly
> match the number of dynamic descriptors. The Vulkan spec states:
> dynamicOffsetCount must be equal to the total number of dynamic descriptors
> in pDescriptorSets
> …
> Fix compute on Vulkan when there is only one buffer but no uniforms

- 3rdparty/webgpu/include/webgpu/webgpu.h
- 3rdparty/webgpu/include/webgpu/webgpu_cpp.h
- 3rdparty/webgpu/webgpu_cpp.cpp
- scripts/bgfx.lua
- scripts/genie.lua
- src/renderer_webgpu.cpp
- src/renderer_webgpu.h
Here are a few updates to WebGPU code:
- update the renderer to match the current state of the API (a bunch of things have changed)
- rebuild embedded shaders to latest shaderc version, as WebGPU needs that
- simplify the `u_model` array so that it's only an array when needed, which is nice but also helps with WebGPU because it's very strict when it comes to not sending all uniforms that are declared in a shader, and this `u_model[32]` array makes many examples break
- rebuild the shaders again to include that change
I'm sure you won't accept this PR as is, but let me know how you want me to divide this work so that you can accept it or some parts of it :)
> WebGPU update

- tools/shaderc/shaderc.cpp
Probably a really petty change, but it's a little confusing for a couple seconds when what looks like one error is actually two.
> add newline at end of error

- src/renderer_gl.cpp
Move the error printout into the BGFX_FATAL, and remove the (now redundant) BX_TRACE.
> Print error messages when shader doesn't compile.

- src/bgfx_p.h
Dynamic buffer with compute read flag can be updated from CPU side.
Since I found that it will check dynamic buffer flag with **BGFX_BUFFER_COMPUTE_WRITE**，so I just check whether this buffer with compute read flag or not.
https://github.com/bkaradzic/bgfx/blob/master/src/bgfx_p.h#L3400
https://github.com/bkaradzic/bgfx/blob/master/src/bgfx_p.h#L3588
> fix update dynamic buffer with compute read flag only 

- src/glcontext_nsgl.mm
Implemented BGFX_CAPS_SWAP_CHAIN in OpenGL on macOS.
I have tried to follow the style as well as possible and not to use any API that may cause incompatibilities in older versions.
Regards
> - Implemented BGFX_CAPS_SWAP_CHAIN in OpenGl on Macos

- src/renderer_vk.cpp
- src/renderer_vk.h
This PR reworks the synchronization in the Vulkan backend to allow pushing render commands ahead of the GPU, similarly to the existing backends.
Currently there's a CPU stall after every compute shader, texture/buffer transfer and render pass (all draw calls of one view). This results in high CPU frame time not only because of the stall (CPU does nothing while GPU is busy) but also because of the non-negligible cost of submitting command buffers. For some examples this easily wastes > 1ms of CPU time.
The frame latency can be controlled with [`Init::Resolution::maxFrameLatency`](https://bkaradzic.github.io/bgfx/bgfx.html#_CPPv4N4bgfx10Resolution15maxFrameLatencyE), from 1 to 3. Using 0 there defaults to 3, similar to the D3D11/12 backends. Current behaviour is similar to a fixed latency …
> Vulkan sync rewrite

- src/renderer_vk.cpp
- src/renderer_vk.h
Miscellaneous fixes for the Vulkan backend, mostly involving textures:
- resize textures that are based on backbuffer ratio (fixes example 09-hdr when resizing)
- support for indirect draw (fixes example 41-tess)
- support for texture array framebuffers (fixes example 08-update [framebuffer cube] and 21-deferred, just some minor validation errors left)
- related: support for VPRT (see https://github.com/bkaradzic/bgfx/issues/2320)
- `BGFX_CONFIG_PREFER_DISCRETE_GPU` is used for device selection (`NvOptimusEnablement`/`AmdPowerXpressRequestHighPerformance` are not enough since they only make the discrete GPU visible)
- use `BGFX_CONFIG_MIP_LOD_BIAS`
- support for `BGFX_DEBUG_WIREFRAME`
> Various Vulkan fixes

- src/renderer_vk.cpp
- src/renderer_vk.h
The scratchbuffer was running out of space because the size was calculated with a different alignment than was used to advance entries. Only an issue at high amount of draw calls, more specifically it crashed example 17-drawstress.
Next step, actually outperform GL in draw call performance 👀
> Vulkan: fix scratch buffer size calculation

- scripts/geometryv.lua
- scripts/texturev.lua
Without these changes linking texturev and geometryv fails due to undefined references.
> Fix building with wayland

- scripts/shaderc.lua
- src/amalgamated.cpp
- src/renderer_vk.cpp
- src/renderer_webgpu.cpp
- src/shader.cpp
- src/shader.h
- tools/shaderc/shaderc.cpp
- tools/shaderc/shaderc_spirv.cpp
This change makes the `texComponent` and `texDimension` shaderc output not depend on or require using Vulkan and WebGPU enums. The new enums are stored in src/shader.h along with conversion functions in src/shader.cpp, which required changes to the amalgamated file as well as shaderc's source files.
I'm not too sure about the names of the enums, or if they should maybe be behind an additional `shader` namespace to clarify what they do.
⚠️ Disclaimer: The WebGPU changes are **untested** (read: uncompiled, because getting WebGPU to compile is too much for a saturday). Definitely need feedback from @hugoam before merging this.
> Make shaderc output independent of backend enums

- src/renderer_vk.cpp
This fixes a bug that only showed up after the changes in https://github.com/bkaradzic/bgfx/commit/453adcf661a593dc7d3bfd87852e432b499367e7. Vulkan doesn't like to be told to clear the stencil attachment when the texture has no stencil at all 🤷
> Vulkan: ignore BGFX_CLEAR_STENCIL if depth attachment has no stencil

- src/renderer_vk.cpp
- src/renderer_vk.h
This PR
- adds support for `BGFX_STATE_CONSERVATIVE_RASTER`, `BGFX_STATE_LINEAA`, `BGFX_RESET_SUSPEND`
- reports GPU memory in `Stats`
- fixes bugs related to swapchain recreation
- removes all hard asserts during `init()`
> Misc. Vulkan features and fixes

- src/renderer_vk.cpp
This hopefully fixes the issue discussed [here](https://github.com/bkaradzic/bgfx/pull/2417).
Device extension data is properly cleared after enumerating each physical device so that `s_extension` only reports extensions of the device selected in the end, not all devices combined.
@bkaradzic VK_EXT_line_rasterization is still disabled in this PR. You can turn it on locally and see if it fixes the issue on your setup, and then merge and turn it on again.
> Vulkan extension detection fix

- src/renderer_vk.cpp
Fixes two small issues
- write-after-write hazard when blitting to the same image
- missing barrier between compute dispatches if a view has no draws
> Vulkan: fix sync hazards

- tools/shaderc/shaderc_spirv.cpp
In renderer_vk.cpp un.num is not used therefore we can just set the regCount.
> Vulkan shader compiler uniform size fix (>255).

- src/dxgi.cpp
- src/dxgi.h
- src/renderer_d3d11.cpp
Right now there are two issues addressed in this PR
1. renderer_d3d11 does not remove swap chains from their associated swap chain panel when releasing. This causes crashes in debug images when changing or resizing SwapChainPanels. We now clean up swap chain panels through dxgi prior to releasing when the swap chain is associated with a SwapChainPanel
1. renderer_d3d11 does not assess changes to the native window handle once created. SwapChainPanels can be dynamically updated, which we now observe/support
> Support dynamic SwapChainPanel changes for DirectX11 UWP scenarios

- src/bgfx.cpp
- src/bgfx_p.h
- src/renderer_vk.cpp
This PR adds two related changes:
1. The view rect and scissor (if set) are cropped to the framebuffer size. If the view rect ends up entirely outside the framebuffer bounds, an assert fires.
2. More debug validation checks during framebuffer creation:
- attachment mip is valid
- attachment layer range is valid
- attachment layer count matches across all attachments
- attachment size matches across all attachments
> View rect/scissor and framebuffer validation

- examples/05-instancing/instancing.cpp
- src/bgfx.cpp
This expands the instancing demo to have a non-instanced path, and a slider for adjusting the number of cubes drawn.  When instancing is turned off and the slider is put at 256 or higher with default configs, a crash occurs without the off by one fix.
> Fix crash when hitting max draw call limit

- src/bgfx_p.h
If you do 
```
bgfx::setIndexBuffer()
bgfx::submit(BGFX_DISCARD_NONE)
bgfx::submit()
```
then the second submit will be broken because even though it still uses the correct index buffer it will lose the BGFX_SUBMIT_INTERNAL_INDEX32 state.
Basically all multi-pass calls involving a 32index buffer are broken currently in bgfx master. 
This fixes bug introduced by https://github.com/bkaradzic/bgfx/commit/5c304dad3b98cfa895a531527881347f3c52aeea
Feel free to change if better idea but the idea is sound.
> Fix: retain submit_index32 flag across draw states

- src/renderer.h
- src/renderer_vk.cpp
- src/renderer_vk.h
This PR mainly adds support for aliasing textures to different types in the shader, enabling a few use cases that currently end in validation errors/device lost:
- array textures can be bound to a SAMPLER2D, using the first layer
- non-array 2D textures can be bound to a SAMPLER2DARRAY with 1 layer
- 3D and cube textures can be bound to a SAMPLER2DARRAY
For this to take effect, shaders need to be compiled with shaderc producing binary version 8 or higher (added with the WebGPU backend: https://github.com/bkaradzic/bgfx/pull/2132). With older shaders, the sampler type is always assumed to match the texture type (this is equal to the current behaviour).
The only example relying on this fix is 21-deferred with texture array frame buffer. The shaders don't need recompilation, they recently …
> Vulkan: alias texture types in shaders + misc fixes

- examples/06-bump/fs_bump.sc
- examples/06-bump/vs_bump.sc
- examples/21-deferred/common.sh
- examples/31-rsm/fs_rsm_combine.sc
- examples/31-rsm/fs_rsm_lbuffer.sc
- examples/31-rsm/vs_rsm_lbuffer.sc
- examples/common/shaderlib.sh
Shaders were checking for everything that isn't `BGFX_SHADER_LANGUAGE_GLSL` but forgot `_SPIRV`. 
While I was checking for other wrong shader language ifdefs I also moved `toClipSpaceDepth` and `clipToWorld` to shaderlib.sh since they're used by both 21-deferred and 31-rsm and I made 06-bump shaders use the existing `mtxFromCols` instead of redefining them (incorrectly in one case).
Let me know if you want me to push recompiled shaders before merging or in another PR.
> Fix 31-rsm Vulkan shaders

- examples/15-shadowmaps-simple/fs_sms_shadow.sc
- src/renderer_vk.cpp
Fixes shaders having to ifdef around Vulkan when writing to `gl_FragColor` with a framebuffer with just a depth attachment.
Normally this results in
> [ UNASSIGNED-CoreValidation-Shader-OutputNotConsumed ] fragment shader writes to output location 0 with no matching attachment
so a dummy color attachment with no actual texture is used to make this compliant.
> Vulkan: allow writing to gl_FragColor without color attachment

- src/renderer_vk.cpp
The descriptor type was taken from the bind type of the draw, but for `IMAGE2D_RO` the shader uses `texture2D` (not `image2D` as used by the other `IMAGE2D` types).
This bug affects examples 37 and 39.
> Vulkan: fix IMAGE2D_RO binding

- src/renderer_d3d11.cpp
- src/renderer_vk.cpp
Fixes two issues related to vertex buffers in the D3D11 and VK backends.
1. https://github.com/bkaradzic/bgfx/discussions/2456, repro can be found there
2. VK backend only used the first stream's vertex offset and count
Repro for issue 2 in example 34-mvs:
1. add 8 times black (`{ 0x00000000 },`) to the front of `s_cubeColorVertices`
2. change `bgfx::setVertexBuffer(1, m_vbh[1])` to `bgfx::setVertexBuffer(1, m_vbh[1], 8, 8)`
3. cubes are black
> Vertex buffer fixes

- src/renderer_vk.cpp
Shaderc writes out a list of all uniforms before optimization and then goes through the list of storage buffers, updating the uniform info. With unused storage buffers, that update never happens so the binding index stays 0, causing out-of-bounds access after calculating the stage [here](https://github.com/bkaradzic/bgfx/blob/b298851bf01e9bd16c2e70bcafe5bbf7cf0dd4fc/src/renderer_vk.cpp#L5389).
The way this manifested itself was a random write to `m_textures[i].m_textureImage`, causing a validation error while trying to destroy an invalid handle 3 frames later. That was fun to debug 💩 
I was working on a fix in shaderc but realized it's better to avoid making unnecessary changes to shaderc and that a fix should also work with old shaders.
> Vulkan: ignore unused storage buffers

- src/renderer_gl.cpp
Tentative fix for https://github.com/bkaradzic/bgfx/issues/2459.
The instance buffer is unbound after every draw call, but not re-bound unless the vertex streams/start or instance data changed. This is incorrect in the case of two consecutive draw calls with identical vertex streams and instance buffers where the output differs because of another change (indirect buffer, uniform, etc.).
Tested against all examples and the repro given in the link (37-gpudriven) as well as 05-instancing with the following patch:
[05-instancing.patch.txt](https://github.com/bkaradzic/bgfx/files/6287197/05-instancing.patch.txt)
> GL: only unbind instance buffer if it changed

- bindings/bf/bgfx.bf
- bindings/cs/bgfx.cs
- bindings/d/types.d
- include/bgfx/defines.h
- scripts/bgfx.idl
Would've helped me understand a uniform binding issue, since BGFX_DISCARD_BINDINGS wont discard any bound texture samplers/uniforms per draw call. Let me know if theres a better way to describe. I am assuming doc generation is done out of hand so didn't bother with that in this PR, just replaced some references.
> Minor alteration to clarify that BGFX_DISCARD_STATE also discards uniforms

- examples/common/debugdraw/vs_debugdraw_fill_lit_mesh.sc
- examples/common/debugdraw/vs_debugdraw_fill_mesh.sc
This fixes validation errors in the VK backend with example 29-debugdraw.
The attributes are unused, but they're included in the resulting SPIR-V. VK backend doesn't find the attribute in `VertexLayout` because it doesn't exist and uses RGB32F as a fallback.
I'm not sure if this warrants a fix in shaderc or if that is expected behaviour.
@bkaradzic with this PR, if you recompile shaders for 31, 37, 39 and debugdraw, all the Vulkan examples should work, without any (validation) errors, apart from the ones missing features (multiple windows and occlusion queries) 🙏
> Remove unused attributes in debug draw shaders

- src/renderer_mtl.mm
With the metal renderer, if you create a frame buffer for a window it could zero reset flags like VSYNC when created.
This passes the existing flags in when creating the frame buffer.
> Retain reset flags when creating a new metal frame buffer for a window.

- src/bgfx_shader.sh
> Add textureSize() overloads for BgfxI/USampler2D

- src/renderer_vk.cpp
- src/renderer_vk.h
This PR adds support for headless instance/device creation (when setting `platformData.nwh` to `NULL`) and MSAA backbuffers (`BGFX_RESET_MSAA_XX`) to the Vulkan backend.
I also fixed a few issues with framebuffer resolve operations and blitting of MSAA images. Namely, resolve and mipgen only used the first layer, and mipgen always started at mip 0 instead of the mip attached to the framebuffer.
The diff is pretty huge because I moved the swapchain code into its own class. This is mostly in preparation for a follow-up PR for multiple window support (soon™ 🤡).
> Vulkan: add headless and MSAA backbuffer support

- src/makefile
The recent shaderc profiles refactor broke the embedded shaders compilation I believe
There was probably no reason those had special profiles anyway so I just put the same profile everywhere
> Fix embedded shaders compilation

- tools/shaderc/shaderc.cpp
I needed to build some raw SPIRV shaders with shaderc and noticed those targets were missing from the code so I added them
> Shaderc: Add missing raw compilation targets

- examples/43-denoise/denoise.cpp
WebGPU doesn't actually support using `RG11B10F` format as a render target.
So to make `43-denoise` work with WebGPU I added a `isTextureValid` check and fallback on `RGBA16F` format because I didn't really know what else I could use (although twice bigger, but it's just an example after all). If you have any other idea I can change something
> Fix 43-denoise when FB format invalid

- examples/22-windows/windows.cpp
- examples/common/entry/entry_windows.cpp
- src/bgfx.cpp
- src/renderer_d3d12.cpp
- fixed D3D12 backend crash, trying to index framebuffers with uninitialized handle
- use correct views (not last frame's views) for cropping view rect. this only showed up when combined with resizing windows
- example 22:
- use correct window size for imgui
- adjust window size to include the frame decoration. this was already done for the main window, but not for new ones. I checked all the other entry functions for creating windows (SDL, GLFW etc.) and according to their respective docs all of them create a window with the given size as the client area, so no fix needed for those. D3D doesn't seem to care about the render area being larger than the backbuffer, but Vulkan validation threw a fit.
> Fixes for multiple windows and example 22

- src/renderer_vk.cpp
- src/renderer_vk.h
Main two additions in this PR are:
- support for multiple windows (`BGFX_CAPS_SWAP_CHAIN`)
- support for backbuffer capture (`BGFX_RESET_CAPTURE`)
A few mostly related changes:
- use backbuffer color format supplied in `Init::resolution::format` and `reset()`, falls back to BGRA8/RGBA8 if not supported by swapchain
- swapchain recreation without stalling on the CPU if possible, should make window resizing smoother on some platforms
- fix init error when running on an Android 1.0 driver
- report all texture format caps (`FRAMEBUFFER_MSAA`, `VERTEX`, `MIP_AUTOGEN` were missing), check properly for a few more caps/limits
If anyone with a Linux system could give this a try, I'd appreciate it 🦆 My laptop decided to stop working and I don't have dual boot.
> Vulkan: multiple windows, capture support

- src/renderer_vk.cpp
- src/renderer_vk.h
Fix for https://github.com/bkaradzic/bgfx/issues/2410.
If vertex and fragment shader use the same stage and the shaders weren't both compiled with binary version 11 or higher, there is now an assert. For newer versions, the stages are merged correctly.
While I was touching that part of the code I also removed a needless indirection for the descriptor set layout. Instead of storing the hash and always looking it up in the cache, it stores the handle directly.
> Vulkan: merge shader bindings

- src/renderer_gl.cpp
If the `rgba` value with `bgfx::setState(state, rgba);` changed and `state` remained the same, the gl renderer failed to recognize this as a state change. This PR fixes this.
> Fix change in blend rgba not being detected as a state change

- src/renderer_d3d11.cpp
this then caused `DX_RELEASE(m_msaaRt, 0);` in `error:` to fire an assert since it tries to deref the garbage ptr
> d3d11: fix unintialized memory

- src/renderer_vk.cpp
- src/renderer_vk.h
Wanted to tie up a few loose ends that have been on my todo list for a bit 🍌 
- support for `BGFX_CAPS_OCCLUSION_QUERY`
- support for `BGFX_SAMPLER_SAMPLE_STENCIL`
- support for `BGFX_SAMPLER_BORDER_COLOR`
- this depends on [VK_EXT_custom_border_color](https://vulkan.gpuinfo.org/listdevicescoverage.php?extension=VK_EXT_custom_border_color) which seems to be supported on most recent desktop GPUs, but not much luck on mobile
- support for timer queries (`Stats::gpuTimeBegin/End` + `Stats::viewStats[i]::gpuTimeBegin/End`)
- use correct cached memory type for readbacks. This makes a drastic performance difference for backbuffer capture on my GPU
- less state binding between draw calls, where possible
- clear and blit are now performed before compute, as in the other renderers
- validation …
> Vulkan: occlusion queries, housekeeping

- src/renderer_vk.cpp
- src/renderer_vk.h
Second attempt :eyes: Tested on g++9, compiles correctly now.
Old PR here: https://github.com/bkaradzic/bgfx/pull/2505
> Vulkan: occlusion queries, housekeeping - attempt 2

- src/glimports.h
The function definition for `glFramebufferTexture` was missing when compiling for GLES, this fixes it.
> GLES: fix compilation after #2507

- tools/shaderc/shaderc.cpp
Compiling 'fs_texture_array.sc' with shaderc for OpenGLES fails with a syntax error,
because the matrix transpose function definitions occur before extension directives,
in this case EXT_texture_array.
Here is the error that shows up when trying to rebuild the texturev embedded shaders:
```
\bgfx\tools\texturev>make rebuild
Cleaning...
removed `vs_texture.bin.h'
removed `vs_texture_cube.bin.h'
removed `fs_texture.bin.h'
removed `fs_texture_3d.bin.h'
removed `fs_texture_array.bin.h'
removed `fs_texture_cube.bin.h'
removed `fs_texture_cube2.bin.h'
removed `fs_texture_msdf.bin.h'
removed `fs_texture_sdf.bin.h'
[vs_texture.sc]
[vs_texture_cube.sc]
[fs_texture.sc]
[fs_texture_3d.sc]
[fs_texture_array.sc]
Code:
---
90: }
91: vec3 toGamma(vec3 _rgb)
92: {
93: return pow(abs(_rgb), …
```
> Fixes texturev embedded shaders compilation

- examples/common/debugdraw/makefile
- examples/common/ps/makefile
- tools/geometryv/makefile
- tools/texturev/makefile
Only these four makefiles had these hardcoded paths.
All other makefiles don't specify the bgfx dir name.
> Fix hardcoded bgfx dir from include paths in makefiles

- src/renderer_gl.cpp
When trying to find all the instances of gl_FragDepth and replace them 
with bgfx_FragDepth it only finds the first instance.
> Fix usage of bx::findIdentifierMatch for gl_FragDepth

- scripts/shader-embeded.mk
- src/makefile
In non-embedded shaders there is a separation between essl binaries (examples/runtime/shaders/essl)
and glsl binaries (examples/runtime/shaders/glsl). On embedded shaders there is no such separation
and by default essl shaders are being used by the OpenGL runtime. This usually doesn't cause any
issues but in the case of the debugdraw shaders, that started using uvec4, this now leads to a
runtime error. This patch fixes this by splitting the embedded shaders into essl and glsl.
As asked, this is the first part of the change.
To be able to compile the 'examples/common/debugdraw' shaders, pull
request #2362 is needed.
> Split embedded shaders into essl and glsl - Part 1

- tools/shaderc/shaderc.cpp
Pull request #2317 broke compilation of the DebugDraw shaders (vs_debugdraw_fill.sc, etc)
on the Intel mesa driver. Shaders with a version lower than 130 have no
support for uvec or ivec by default on OpenGL.
This patch detects when these shaders are present and bumps the version when appropriate.
> Fix DebugDraw shaders compilation

- scripts/shader-embeded.mk
- src/makefile
This echo command on the makefile behaves differently between linux and gnuwin32:
```
-@echo extern const uint8_t* $(basename $(<))_pssl;>> $(@)
```
On linux the semicolon immediately ends the echo command and its output is never piped to the embedded shader's header.
If you try to fix it by quoting the string:
```
-@echo "extern const uint8_t* $(basename $(<))_pssl;" >> $(@)
```
It will work on linux but not on gnuwin32 because the quotes will appear on the outputted string.
The solution was to use printf which works consistently between the two.
Also on gnuwin32 the outputted string has 'CRLF' line endings, which clashes with the rest of the 'LF' line endings of the
embedded shaders header which were produced by shaderc.
The solution was to remove the 'CR' from the outputted string by …
> Make the generated embedded shader headers the same between linux and gnuwin32

- scripts/shader-embeded.mk
- scripts/tools.mk
- src/makefile
Adds support on tools.mk for the msys2 environment. The OS is still
considered windows but the command line tools for mkdir and rmdir
behave as if on linux.
The variable SHADER_TMP on the makefiles also had to be quoted to make
it work on msys2.
> Allow shaders to be compiled on msys2

- examples/common/nanovg/nanovg_bgfx.cpp
I've been using this code for over a year now in SiverNode. I think it's a valid usecase.
> Allow to create a nvg texture from a BGFX texture.

- tools/shaderc/shaderc.cpp
It was a bit confusing when I took a look at shaderc's help but compute shader type was not listed here and program said nothing when I passed `--type c` to it.
Wiki should be changed too: https://bkaradzic.github.io/bgfx/tools.html#shader-compiler-shaderc
> Add compute shader type to shaderc help.

- src/debug_renderdoc.cpp
Hello. This PR arises out of a [discussion I had with BaldurK](https://github.com/baldurk/renderdoc/issues/2279#issuecomment-844588691) about the right way to load the RenderDoc DLL in Windows. It seems bgfx is currently expecting the dll to be either next to the executable, or in the system PATH, but these are not preferable or supported ways of loading it according to Baldur. This particularly causes problems with the Vulkan backend due to the way RenderDoc is implemented as a layer in Vulkan.
The changes here:
- on Windows, if the process was launched from RenderDoc and the dll is already injected in the process, use it
- otherwise try to load the dll from RenderDoc's default installation path in Program Files
- use `GetModuleHandleA` instead of `EnumProcessModules` etc in `findModule` …
> Use already injected RenderDoc dll, or load it from default location

- 3rdparty/glsl-optimizer/src/glsl/ir_print_glsl_visitor.cpp
- tools/shaderc/shaderc.h
Hi, recently I noticed that shaderc results differ on different platforms.
After some investigation, I found two issues:
1. 'texFormat' in struct Uniform wasn't intialized (similar with #2174).
2. glsl-optimizer did special treatment for MSVC in 'print_float' for result consistency, but it causes inconsistency on the latest MSVC.
For the second issue, look at the comment in 'print_float', it removes a zero in MSVC's print result, but didn't check if the extra zero is actually there, which gives something like 1.0e+7 on the latest MSVC.
```
#if defined(_MSC_VER)
// While gcc would print something like 1.0e+07, MSVC will print 1.0e+007 -
// only for exponential notation, it seems, will add one extra useless zero. Let's try to remove
// that so compiler output matches.
if (posE != NULL)
{ …
```
> Fix shaderc consistency

- src/renderer_gl.cpp
This extension is used to detect support for gl_InstanceID and gl_VertexID. However, in more recent
versions of OpenGL, this is built-in functionality. On my system, it does not list that extension,
even though it supports those features, but BGFX was not detecting that.
Updated detection to look for GL>=3.1.
Note 1: even with this change, you do need to compile BGFX with the appropriate
BGFX_CONFIG_RENDERER_OPENGL value (>=31). The default of 21 is not high enough.
Note 2: Even with all of the above, you will likely hit issues with duplicate '#version' lines in
the generated shader code. For that, see issue #xxxx.
fixes issue #2570
> Improve detection of EXT_gpu_shader4

- src/renderer_vk.cpp
`g_callback->captureFrame` never gets called if the format is RGBA8, this fix correctly invokes the callback. Got introduced in https://github.com/bkaradzic/bgfx/pull/2491.
> Vulkan: fix RGBA8 backbuffer capture

- src/renderer_vk.cpp
Destroying a framebuffer in the Vulkan backend doesn't immediately reset/resolve the attachments for sampling operations. Normally that's not an issue since it happens when a new framebuffer is set. However, when destroying the FB, then not using any FB for several frames (compute-only or empty draw list) and then creating a new FB that gets assigned the same ID, the check for a new FB fails (since the IDs are identical). This results in
a) an assert ("Mismatching image layout") when trying to sample the destroyed FB's textures
b) the destroyed FB's textures not being resolved if they're multisampled
Repro in 01-cubes: [repro-pr-2547.patch.txt](https://github.com/bkaradzic/bgfx/files/6957246/repro-pr-2547.patch.txt)
This is a slightly less bandaid-y fix for …
> Vulkan: correctly resolve attachments of destroyed framebuffer

- src/renderer_vk.cpp
This fixes a bug reported by @krupitskas on Discord. Vulkan code didn't correctly differentiate between 3D and layered (cube) textures, which need different resource addressing for the z-slice.
> Vulkan: fix layer calculation for (cubemap) array texture update

- src/renderer_vk.cpp
Small fix for a bug introduced in https://github.com/bkaradzic/bgfx/pull/2576
> Vulkan: fix present elapsed calculation

- src/bgfx_shader.sh
When compiling for D3D, `textureGather` was missing the `comp` parameter to pick the texture component to gather and always defaulted to the red channel. This patch adds that parameter and calls the correct `GatherXX` function on the texture.
However, the `comp` parameter is now mandatory. I can't overload on a macro (`Redefining defined variable "textureGather"`), and I assume all the sampling functions are macros and not functions themselves for a good reason.
previous:
```glsl
textureGather(s_tex, uv) // red, OK
textureGather(s_tex, uv, 1) // green, ERROR
```
now:
```glsl
textureGather(s_tex, uv) // red, ERROR
textureGather(s_tex, uv, 0) // red, OK
```
> HLSL: add textureGather for all components

- examples/39-assao/cs_assao_generate_importance_map.sc
- examples/39-assao/cs_assao_generate_q.sh
- examples/39-assao/cs_assao_smart_blur.sc
Follow-up to https://github.com/bkaradzic/bgfx/pull/2595. Forgot to commit the updated examples with the correct `textureGather` syntax.
> Fix textureGather in example 39

- src/renderer_vk.cpp
Without this change, running examples under XWayland, SDL and vulkan
renderer results in a crash. Credit goes to @pezcode:
https://github.com/bkaradzic/bgfx/issues/2593#issuecomment-905462527
> Fix crash when switching to fullscreen with vulkan

- tools/shaderc/shaderc.cpp
The fix exists for 120 shaders that use some 130 features. On the other hand, if a 130 (or above) shader is not using those features, the actual code path will not apply that fix and the shader will fail to compile at runtime.
> Fixed shadow map sampling for 130 and above glsl profiles.

- src/bgfx_p.h
Hi there ! 👋 
When running code analysis, the Particubes (https://particubes.com) dev team got a compilation error and noticed this error in the usage of `fatal` function.
It seems to be a trivial fix / PR.
Thanks for your review 🙂
> fix usage of fatal() function when Clang analyzer is used

- src/renderer_mtl.mm
Metal Validation crash when clearWithRenderPass is false and MSAA on because of `stroreAction` is invalid.
> [Metal] store action was not set when clearWithRenderPass is false and MSAA on

- src/renderer_vk.cpp
- src/renderer_vk.h
Hopefully fixes an issue reported by @belegdol on Discord. Apparently Mesa + Xwayland require 5 swapchain images, but the Vulkan backend only allowed up to 4.
The change is rather trivial (bump the 4 up to 10) but I can't personally test this, so if anyone can confirm this fixes it, that would be great :bow:
Related issues:
https://github.com/mamedev/mame/issues/8057
https://gitlab.freedesktop.org/mesa/mesa/-/issues/4727#note_1072645
> Vulkan: raise maximum number of swapchain images

- examples/46-fsr/app.cpp
- examples/46-fsr/fsr.cpp
- tools/shaderc/shaderc_metal.cpp
- tools/shaderc/shaderc_spirv.cpp
As per the previous PR where we said POD casts should use C-style or ctor casts, I changed all the others to ctor casts, for consistency.
> Cleanup: change POD casts from static_cast to functional/ctor casts

- src/renderer_gl.cpp
bi.m_depth == 1 for usual 2D blit
> Fix 3D blit test

- examples/10-font/font.cpp
- examples/11-fontsdf/fontsdf.cpp
- examples/common/cube_atlas.cpp
- examples/common/cube_atlas.h
I faced a similar issue described in https://github.com/bkaradzic/bgfx/issues/534
First screenshot from Windows 7 with Direct3D11 rendering:
Second from Android with OpenGLES rendering:
(A similar problem arises on MacOS with Metal rendering)
My fix is based on how I render the font in ImGui. 
Tested on Direct3D9, Direct3D11, OpenGL, OpenGLES, Metal and Vulkan. All looks good.
> Fix font rendering

- src/glcontext_egl.cpp
bx::write used to have a default parameter before this commit:
https://github.com/bkaradzic/bx/commit/51c326484623c719bf0d0de8ff7ca0511a01feb4#diff-8aeee1800c8c4a41e89d09b8f6eee3dfdb361125aee087eeccd34af0240e2e13
But `glcontext_egl.cpp` was not updated.
> no more optional param for bx:write

- src/renderer_gl.cpp
On WebGL, the available ES version is only known at runtime, depending on whether a WebGL1 (ES 2 equivalent) or WebGL2 (ES 3 equivalent) context was obtained. The changes make the GL renderer rely on this runtime determination (m_gles3) in more places.
> Use m_gles3 flag more extensively (instead of compile-time ES version)

- tools/shaderc/shaderc.cpp
It looks more consistent this way, but I may miss something as to why it is set to 1 (instead of profile) in some cases.
> Set BGFX_SHADER_LANGUAGE_GLSL to actual profile more consistently

- bindings/bf/bgfx.bf
- bindings/cs/bgfx.cs
- bindings/d/types.d
- include/bgfx/defines.h
- scripts/bgfx.idl
- src/renderer_d3d12.cpp
Indirect batching doesn't work with WARP driver (Microsoft Basic Render Driver). It's the case when running on Azure Pipelines for example or when forcing WARP in DirectX control panel.
> Disable Batch indirect mode for Microsoft WARP

- src/renderer_mtl.mm
On macOS (and very likely iOS) the CPU performance is very bad (blocking CPU on each setFrameBuffer in MTL) because the bgfx's max latency is 0 which in MTL world doesn't mean default (3).
> MTL: Use default frame latency if 0 provided

- examples/common/font/font_manager.cpp
"Suspicious" shouldn't really be an assert as there are cases when those limits can be on the low side.
> Change TTF init asserts to warns and add some details to the output

- bindings/bf/bgfx.bf
- bindings/cs/bgfx.cs
- bindings/d/types.d
- include/bgfx/defines.h
- scripts/bgfx.idl
Current docs are a little ambiguous with the term "profiling"; sometimes it means
bgfx::CallbackI functions, and sometimes per-view stats collection. This makes it a little clearer.
> Enhance docs for BGFX_DEBUG_PROFILER

- src/renderer_mtl.mm
`kIOMainPortDefault` is only available on macOS 12 or later, as shown in `IOKitLib.h`:
```objc
/*! @const kIOMainPortDefault
@abstract The default mach port used to initiate communication with IOKit.
@discussion When specifying a main port to IOKit functions, the NULL argument indicates "use the default". This is a synonym for NULL, if you'd rather use a named constant. */
extern
const mach_port_t kIOMainPortDefault
__API_AVAILABLE(macos(12.0), ios(15.0), watchos(8.0), tvos(15.0));
```
There is a deprecated version of the same thing, `kIOMasterPortDefault`, but both are [a named constant for NULL](https://developer.apple.com/documentation/iokit/kiomasterportdefault), so to avoid availability issues in either direction I have changed it to `NULL`.
> Fix use of constant only available on macOS 12+

- examples/common/entry/entry_windows.cpp
"When you no longer need the HBRUSH object, call the DeleteObject function to delete it."
https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-createsolidbrush
👍
> Fix "GDI resource leak".

- examples/38-bloom/bloom.cpp
Hi, 
Changed the class name of the bloom example that was `ExampleDeferred` to `ExampleBloom` (I hope it wasn't on purpose).
Also used shifts directly at various places where floats where involved, reducing casts between floats and ints.
Best regards,
Jean
> Use shift directly instead of float casts

- src/bgfx.cpp
width and height must be smaller OR EQUAL than maxTextureSize
> Fixed wrong comparison of maxTextureSize

- bindings/bf/bgfx.bf
- bindings/cs/bgfx.cs
- bindings/d/funcs.d
- bindings/d/types.d
- examples/13-stencil/stencil.cpp
- examples/14-shadowvolumes/shadowvolumes.cpp
- examples/23-vectordisplay/vectordisplay.h
- examples/30-picking/picking.cpp
- examples/31-rsm/reflectiveshadowmap.cpp
- examples/36-sky/sky.cpp
- examples/41-tess/tess.cpp
- examples/42-bunnylod/progmesh.c
- examples/43-denoise/denoise.cpp
- examples/44-sss/screen_space_shadows.cpp
- examples/45-bokeh/bokeh.cpp
- examples/46-fsr/app.cpp
- examples/46-fsr/ffx_a.h
- examples/46-fsr/ffx_fsr1.h
- examples/46-fsr/fsr.cpp
- examples/common/font/font_manager.h
- include/bgfx/bgfx.h
- include/bgfx/c99/bgfx.h
- scripts/bgfx.idl
- scripts/genie.lua
- src/glcontext_nsgl.mm
- src/renderer_vk.cpp
- src/shader_dxbc.cpp
Found via `codespell -q 3 -S ./3rdparty,*.ttf -L attribut,ba,clude,conly,indext,inout,lod,nclude,retur,utput`
> Fix various typos

- examples/common/imgui/imgui.cpp
A few minor fixes for the ImGui backend:
- Meta/Cmd/Super/Windows key modifier state is passed to ImGui (if entry is used)
- fixed a bug with incorrect index offset calculation, see https://github.com/ocornut/imgui/issues/4863
- added support for per-draw vertex offset, makes it possible to render > 65k vertices even with 16-bit index buffer (https://github.com/ocornut/imgui/issues/2591)
> Imgui fixes

- src/renderer_vk.cpp
Title 🍌 
The log now also prints the instance "variant" - currently always 0 for normal Vulkan. Probably used for stuff like the upcoming [Vulkan SC](https://www.khronos.org/vulkansc/).
> Vulkan: replace deprecated version macros

- examples/common/imgui/imgui.cpp
Imgui 1.87 added new functions for registering mouse and key events, obsoleting directly writing to structures in `ImGuiIO`.
For more information see https://github.com/ocornut/imgui/issues/4921.
> Switch to imgui IO event API

- src/bgfx_shader.sh
In order to sample a `SAMPLERCUBE`, `textureCube` in GLSL >= 130 requires extension `GL_NV_shadow_samplers_cube`. However, the all-purpose `texture` will sample it.
Change suggested by user `kib`, on the Discord channel, after a problem sampling a cube reported by myself and another user (pinsrq).
> Added `textureCube` macro for GLSL  >= 130.

- src/renderer_gl.cpp
Depth/Stencil only framebuffers have m_num = 0 (counts only color attachments), thus the test on destroy does not pass, causing the FBO to leak.
> Fix leaked FBO for depth/stencil only view

- bindings/d/types.d
- scripts/bindings-d.lua
Previously, using any typed enums meant also putting the enum type name:
`bgfx_texture_format_t.BGFX_TEXTURE_FORMAT_RGBA8`
The way the enums are named makes this redundant, so I've added a string mixin to remedy the issue. Thus, enums can now be used the same way as in C:
`BGFX_TEXTURE_FORMAT_RGBA8`
This method of manually adding pre-processor functions is temporary and should eventually be fully-automated. For now though, more people can easily use them.
> Updated D bindings: enums expanded; added some C++ pre-processor functions

- src/bgfx.cpp
submit param _depth is no longer ignored when using default sort mode
> Use depth in default sort mode

- src/bgfx_shader.sh
Fixes issues with shader code like this:
```glsl
#define MY_SAMPLER 2
SAMPLER2D(s_texColor, MY_SAMPLER)
```
fcpp (C preprocessor used by shaderc) doesn't handle macro expansion with `##`, even with the usual shenanigans involving another macro doing the expansion. I've tried finding a fix in fcpp but wasn't very successful, hence this workaround.
Note that:
- the bug only affected shader targets (internally) using HLSL, ie. DX, Metal, VK
- the fix only works for DX with target SM > 3, ie. DX10 and up (no such limitation for Metal or VK)
- I verified with DX11/12/VK by modifying example 21-deferred shaders to use macros as above and recompiling
> Fix resource register macro expansion in shaders

- src/renderer_gl.cpp
According to https://www.khronos.org/opengl/wiki/Array_Texture `EXT_texture_array` is in core OpenGL since version 3.0, not 3.1.
This is important when making texture arrays on GLES3 on android and webassembly as bgfx wrongly returns 1 as the max layer size when in fact it is higher.
Tested on Android Emulator.
> gl: Get maxTextureLayers on versions 3.0 and up

- src/renderer_gl.cpp
- tools/shaderc/shaderc.cpp
On android with GLES3, shaders using texture2d arrays will complain that there is no precision for `sampler2DArray` and that `texture2DArray` does not exist.
Tested on Android Emulator with GLES3 and on Linux with OpenGL
> Fixes for shader texture array in GLES3

- bindings/zig/bgfx.zig
- scripts/bindings-zig.lua
@heretique, nice work with the Zig bindings. I've put together some changes that should be made to the autogeneration.
- You don't need `callconv(.C)` for extern function declarations. `extern` implicitly sets `callconv(.C)`. 
- `const` qualifiers were lost during the conversion.
- Encoder should be defined as `pub const Encoder = opaque {};`. I'm not certain about the why, but I believe an empty struct  will decay to something that can't be marked extern, while `opaque {}` specifies a non-zero type that works across the ABI boundary. I also changed Encoder to use a nullable pointer `?*`.
- Array definitions weren't correct for function parameters. Anything marked as float[n] in the idl is translated to `f32` instead of  `[n]f32`. It looks like the C# bindings you based this on also has …
> Update Zig binding generation

- examples/42-bunnylod/bunnylod.cpp
- examples/42-bunnylod/progmesh.c
1. Fix a bug in `array_push`
2. I found `bgfx::weldVertices` is not equivalent to my orignal `findDuplicateVertices`. ( Replaced in https://github.com/bkaradzic/bgfx/pull/2156) , so an additional transformation (`mergeIndices`) needed.
> bugfix : example 42

- examples/42-bunnylod/bunnylod.cpp
Sorry, there is still a bug in https://github.com/bkaradzic/bgfx/pull/2769 . Fixed it.
And rename mergeIndices() to rearrangeIndices() .
The details about `rearrangeIndices()` :
The original indices are
```
0 1 2 3 4 5 3 4 6
```
If `bgfx:weldVertices()` merge vertex 3 to 1, an 4 to 2 , the indices would be
```
0 1 2 1 2 5 1 2 6
```
`rearrangeIndices()` rearrange these indices to
```
0 1 2 1 2 3 1 2 4
```
(5 to 3, 6 to 4)
> bugfix and rename mergeIndices()

- src/renderer_gl.cpp
Removing erroneous extra bracket for aliasing shadow2DProj in GLSL. Would have caused compilation failure if used.
> Fixing shadow2DProj in GLSL

- src/renderer_mtl.mm
If I declare an image in compute shader, that image will failed to set in the bind type of the pipeline state object:
https://github.com/bkaradzic/bgfx/blob/master/src/renderer_mtl.mm#L2022
because image object does not get from shader as uniforms. This check will cause 'ps->m_bindTypes' not be set.
I try to work around this by create an uniform with the same name as I declare in compute shader. But I think metal renderer should not assume the reflection argument type as 'MTLArgumentTypeTexture' must be texture.
This fix related to this issue:
https://github.com/bkaradzic/bgfx/issues/2778
> fix image is not set in pipeline state object in metal renderer

- src/renderer_gl.cpp
Rebind the previously bound FBO after rendering an emulated blit instead
of going back to the default FBO.
> GL: Properly reset FBO after emulated blit

- src/renderer_mtl.h
- src/renderer_mtl.mm
I need metal renderer to auto generate mipmap, other renderer have been supported about this.
And I found this issue have discuss about this:
https://github.com/bkaradzic/bgfx/issues/798
So I follow this discuss and make it work.
Here is the document I referenced:
https://developer.apple.com/documentation/metal/mtlblitcommandencoder/1400748-generatemipmapsfortexture
https://developer.apple.com/metal/Metal-Feature-Set-Tables.pdf
Something should note about which format can generate mipmap.
As the document say that, texture format should:
> Mipmaps are generated with scaled images for all levels up to the maximum level. The mipmap level count for the texture must be greater than 1. Mipmap generation works only for textures with color-renderable and color-filterable pixel formats.
And the …
> support Metal renderer to auto generate mipmap for render target

- src/glcontext_wgl.cpp
On Mesa, the pixel format would match the 0 stencil bits as requested. This change helps bring the pixel format to match what `createContext` would use. Issue can be easily reproduced by enabling Mesa software rasterization and running example-13-stencil, specifically the `Projection Shadows Scene`.
> Changed WGL_STENCIL_BITS_ARB to match what gets used in createContext

- src/bgfx_p.h
Compute kSortKeyViewNumBits automatically via log2(BGFX_CONFIG_MAX_VIEWS), so that we could change BGFX_CONFIG_MAX_VIEWS to be above 2^10 = 1024 without changing the `bgfx` source code..
One possible problem with this approach is running out of bits, so maybe we could assert for that, I am not sure where to do it and how many bits we can use though.
Using `bx::uint32_cntlz` because `bx::log2` is not constexpr.
Tested on linux opengl2.1 with BGFX_CONFIG_MAX_VIEWS=4096, seems to work.
> Compute kSortKeyViewNumBits automatically.

- bindings/zig/bgfx.zig
- scripts/bindings-zig.lua
Updated the bindings generation to provide more idiomatic zig bindings.
Naming of the functions now follow zig's [style guide](https://ziglang.org/documentation/0.9.1/#Style-Guide)
Now we support method like calls for vertex layouts or encoders. We also support `VertexLayout`'s fluent interface :
```
posColorLayout.begin(bgfx.RendererType.Noop)
.add(bgfx.Attrib.Position, 3, bgfx.AttribType.Float, false, false)
.add(bgfx.Attrib.Color0, 4, bgfx.AttribType.Uint8, true, false)
.end();
```
I haven't found yet a good way of handling variadic arguments in zig wrappers so for now `dbg_text_printf` and `dbg_text_vprintf` are not exported anymore since I noticed that the bindings for them were not working properly.
> more idiomatic zig bindings

- bindings/bf/bgfx.bf
- bindings/cs/bgfx.cs
- bindings/d/types.d
- bindings/zig/bgfx.zig
- include/bgfx/defines.h
- scripts/bgfx.idl
- src/glimports.h
- src/renderer_gl.cpp
OpenGL ES with Mali GPU + MSAA doesn't show any rendering.
As stated in this doc: https://developer.arm.com/documentation/101897/0200/fragment-shading/multisampling-for-opengl-es
```
Do not use glBlitFramebuffer() to implement a multisample resolve.
```
This will not do the blit but will log an error in Logcat.
To fix it, simply render a full screen quad instead of a bit. I've added this code path only for ARM Mali.
> Fix MSAA with ARM Mali OpenGL ES

- examples/common/nanovg/nanovg_bgfx.cpp
Fix the transient vertex buffer's overflow assert being fired. Now if the tvb is overflowed a warning is emitted and the draw is skipped
> Update nanovg_bgfx.cpp, check Transient Vertex Buffer available size before allocating

- src/renderer_d3d12.cpp
With D3D12, when using instances with more than 1 stream, the PSO creation fails because `InputSlot` for instances points to a non instanced input.
Repro with Example05 in this branch: https://github.com/CedricGuillemet/bgfx/tree/d3d12StreamInstanceError
Simple fix: change the input slot to be the first instance one.
> Fix D3D12 InputSlot when having streams w/ instances

- src/glcontext_eagl.h
- src/glcontext_eagl.mm
- src/glcontext_egl.cpp
- src/glcontext_egl.h
- src/glcontext_glx.cpp
- src/glcontext_glx.h
- src/glcontext_html5.cpp
- src/glcontext_html5.h
- src/glcontext_nsgl.h
- src/glcontext_nsgl.mm
- src/glcontext_wgl.cpp
- src/glcontext_wgl.h
- src/renderer_gl.cpp
On many Android devices tested internally, enabled MSAA breaks rendering (glitches, crashes, no rendering at all ...)
But when enabled during context creation, things are fine.
This PR, enables MSAA at context creation for Android/EGL and enables a flag that doesn't create MSAA FBO and its resolve.
> Enable MSAA setting at context creation for Android

- src/renderer_d3d11.cpp
- src/renderer_d3d12.cpp
This PR is all about ensuring the correct type is chosen when resolving on both D3D11/D3D12.
For eg. Depth textures when using `m_fmt` resolve to type `TYPELESS` while in fact they are of type `FLOAT` when using the `m_fmtSrv` parameter ( which I think was the intended one to be used since day 1 ).
A simple example to see this in action and to test it, is to use a framebuffer with a color and depth texture with flag `BGFX_TEXTURE_RT_MSAA_X16` set.
> Resolve texture format correctly on D3D11/D3D12

- src/bgfx.cpp
I noticed that this https://github.com/bkaradzic/bgfx/commit/0363560934172853742390bf516ba2cbaa901968
broke https://github.com/bkaradzic/bgfx/blob/b5e7a4cccd8467d5f3c9d53ac220ecf8f0861b75/examples/16-shadowmaps/shadowmaps.cpp#L1750
which shouldn't be the case. The validation was meant for only multisample flags.
my boolean logic assumes that it must be BGFX_TEXTURE_RT in the flag or BGFX_TEXTURE_RT_MSAA_XX in the flag.
> Fix invalid boolean logic of texture validation

- 3rdparty/stb/stb_rect_pack.h
dear-imgui updated the stb_rect_pack which bgfx should match.
Users with the old stb_rect_pack will get an assertion failure with font atlases not being packed properly with latest bgfx.
See https://github.com/ocornut/imgui/blob/master/imstb_rectpack.h
> Update stb_rect_pack.h to match dear-imgui

- examples/47-pixelformats/pixelformats.cpp
Use positive logic for "alpha" in pixelformats example
> pixelformats: Use "Alpha" instead of "Ignore Alpha"

- src/glcontext_egl.cpp
Some platforms fail with a narrowing warning due to the implicit typecast here when cross-compiling to android
> egl: Fix narrowing warning/error

- src/renderer_gl.cpp
- src/renderer_gl.h
Currently none of the formats swizzle, but I'm prototyping the `B5G6R5` which would require swizzling R and B components due to GLES not having `GL_BGR` defined for internal formats.
I don't see any use for any of GL_TEXTURE_SWIZZLE_R, GL_TEXTURE_SWIZZLE_G, GL_TEXTURE_SWIZZLE_B, GL_TEXTURE_SWIZZLE_A so I didn't include any cases with them.
> opengl: Implement texture swizzle mapping

- bindings/bf/bgfx.bf
- bindings/cs/bgfx.cs
- bindings/d/types.d
- bindings/zig/bgfx.zig
- include/bgfx/bgfx.h
- include/bgfx/c99/bgfx.h
- scripts/bgfx.idl
- src/bgfx.cpp
- src/bgfx_p.h
- src/renderer.h
- src/renderer_d3d11.cpp
- src/renderer_d3d11.h
- src/renderer_d3d12.cpp
- src/renderer_d3d12.h
- src/renderer_d3d9.cpp
- src/renderer_d3d9.h
- src/renderer_gl.cpp
- src/renderer_gl.h
- src/renderer_mtl.h
- src/renderer_mtl.mm
- src/renderer_noop.cpp
- src/renderer_vk.cpp
- src/renderer_vk.h
- src/renderer_webgpu.cpp
- src/renderer_webgpu.h
Squashed version of: https://github.com/bkaradzic/bgfx/pull/2898
Per the discussion over there, I have not implemented the Metal backend.
Similar case for WebGPU, actually - did not seem like all the necessary parts where there.
> Record frame num in view stats

- makefile
- scripts/genie.lua
Add comdlg32 library for GetOpenFileNameA API.
> clang-mingw: Enable building tools and examples

- .github/workflows/main.yml
Changes:
* Move the project generation command in prepare step to run in host ubuntu-22.0 os.
* Add EMSCRIPTEN explicitly in both prepare and build step.
* Run make command with respect to root bgfx workspace directory.
> CI: Fix wasm build running genie in host

- src/renderer_d3d12.cpp
Suppose this is the draw call sequence in a frame:
- triangle strip
- touch (required to apply stencil changes for example)
- triangle list
Touch masks the change (as it's triangle list by default) by setting changedFlags, but not primIndex. When the triangle list is processed, the STATE_PT is already set to triangle list, so the test for changedFlags is skipped and primIndex stays with triangle strip.
The fix detects the change in the STATE_PT and updates primIndex.
> d3d12: fixes tri list primitive state change not ackd. after touch call

- src/bgfx_shader.sh
texture2DBias() was defined in term of texture2D() which was then redefined with the bias parameter stripped (leads to a shader compilation error)
> Fix textureXXXBias() macro definitions for glsl >= 130

- src/renderer_gl.cpp
Sampler Objects are now used only based on the m_samplerObjectSupport boolean, in line with m_gles3 being discovered at runtime due to WebGL.
This should also fix the issue reported in an earlier PR https://github.com/bkaradzic/bgfx/pull/2947 (@PyryM)
> Simplify the sampler object code path selection in GL backend

- .github/workflows/main.yml
- 3rdparty/native_app_glue/NOTICE
- 3rdparty/native_app_glue/android_native_app_glue.c
- 3rdparty/native_app_glue/android_native_app_glue.h
- docs/build.rst
- makefile
- scripts/example-common.lua
This is companion PR to https://github.com/bkaradzic/bx/pull/289
Changes:
* list `android-x86_64` configuration
* use local copy of `native_app_glue` in example harness
* local copy was modified to compile as C++
* Android builds was added to github actions
> Android NDK update, bgfx side

- .github/workflows/main.yml
This is follow up to previous `android-ndk-update` draft PR which was merged as-is.
CI was pointed to my repo/branch to test if actions run. This PR reverts that and point them back to `bkaradzic/bx`
@bkaradzic Can you amend last commit https://github.com/bkaradzic/bgfx/commit/04732d89e369844a8d5425210965faba380e0b4b to remove:
`CI: **DO NOT MERGE** pick bx/PR with android support update`?
It is why I kept it as a draft.
> CI: Point android ci to bkaradzic/bx

- 3rdparty/glsl-optimizer/src/glsl/ir_print_glsl_visitor.cpp
This sample vertex shader:
```$input a_position
invariant gl_Position;
void main()
{
gl_Position = vec4(0.0, 0.0, 0.0, 0.0);
}
```
Produces this output when passed though shaderc (cmd: `shaderc --type vertex --profile 300_es --varyingdef varying.def.sc --stdout -f test_invariant_qualifier.sc`)
```precision highp sampler2DArray;
precision highp int;
precision highp float;
layout(location=-17) invariant gl_Position;
void main ()
{
gl_Position = vec4(0.0, 0.0, 0.0, 0.0);
}
```
This location is bogus and prevents further compilation. Note that this does not happens with `profile 100_es`.
> glsl-optimizer: avoid adding location to built-in variables

- src/renderer_d3d11.cpp
The 3256 line of renderer_d3d11.cpp converts the cubemap in the image format in the compute shader to the textureArray format. As a result, the texture ivec3 values in cs_5_0 cannot be correctly sampled.
> fix renderer_d3d11 cs image input format transformation of cubemap

- src/renderer_d3d9.cpp
The d3d9 renderer fails on creation of index buffers with **32-bit indices are not supported. Use bgfx::getCaps to check BGFX_CAPS_INDEX32 backend renderer capabilities.** error since the BGFX_CAPS_INDEX32 caps is not handled in the d3d9 renderer path.
This PR has this issue fixed, the INDEX32 index buffers can now be created for d3d9 backend.
> Added INDEX32 caps support for d3d9 renderer

- src/renderer_d3d9.cpp
In D3D9 the wait for vertical sync is implicitly handled inside the device->Present and SwapChain->Present calls based on the value of PresentationInterval field of D3DPRESENT_PARAMTERS, so there is no need to explicitly call WaitForVBlank on flip.
P.S.: If the PresentationInterval field of D3DPRESENT_PARAMTERS is set correctly according to BGFX_RESET_VSYNC (i.e. to D3DPRESENT_INTERVAL_ONE) which is already done in d3d9 renderer, then there is no need to call WaitForVBlank.
Test/Proof: If you set the reset flag to BGFX_RESET_NONE on bgfx::init, for the d3d9 backend it will still keep syncing with monitor vsync which is not expected behavior, it should be unlocked from vsync like other gfx backends, this patch will fix this issue for BGFX_RESET_NONE on d3d9.
> Removed redundant WaitForVBlank from d3d9 renderer

- scripts/shader-embeded.mk
- scripts/shader.mk
- tools/shaderc/shaderc_hlsl.cpp
shaderc HLSL profile switch is fixed to accept s_3_0, s_4_0, s_5_0 instead of ps_.../vs_.../cs_..., why this fix is necessary?
1- Consistency: with other shader language profiles, e.g. for OpenGL or spirv we only need to specify the profile name (including version) but for hlsl and D3DCompile it was different and used to be like vs_5_0 or ps_5_0, which doesn't make sense IMO.
2- Redundant Info: The shader type (vertex, fragment, compute) is already specified via --type switch, why should we repeat the shader type info in both --profile and --type? (for hlsl only). The type can already be deduced from the --type switch and doesn't make sense to repeat it in --profile like vs_... ps_...  (the s_... should be enough)
3- This is what the shaderc.exe CLI tool help instructs :) it says for hlsl …
> shaderc HLSL profile switch fix

- tools/shaderc/shaderc.cpp
- tools/shaderc/shaderc_spirv.cpp
This fixes https://github.com/bkaradzic/bgfx/issues/3016
This change ~specifcally~ specifically:
- adds support for Vulkan 1.3 using SPIR-V 1.6 as a profile target
- moves ordering of help information of SPIR-V block
- updates the SPIR-V to Vulkan mapping documentation
> shaderc update to support Vulkan 1.3 and SPIR-V 1.6 profile option

- tools/shaderc/shaderc.cpp
The preprocessor in shaderC removed precision qualifier when using ESSL
An example to reproduce the bug: 
* adding "precision highp sampler2D;" to fs_cubes.sc
* call: shaderc.exe -f examples/01-cubes/fs_cubes.sc --type fragment --profile 300_es --varyingdef examples/01-cubes/varying.def.sc --stdout -i src/
* Result: 
>>>  14: precision sampler2D;
>>>  11:           ^ 
Error: (14,11): error: syntax error, unexpected SAMPLER2D, expecting LOWP or MEDIUMP or HIGHP
> Fix shader preprocessor constructor call

- src/renderer_gl.cpp
Context: GL (and GLES with [EXT_sRGB_write_control](https://registry.khronos.org/OpenGL/extensions/EXT/EXT_sRGB_write_control.txt)) determine whether to perform sRGB writes based on both the format of the current surface / FBO attachment **and** the FRAMEBUFFER_SRGB flag.
The patch enables FRAMEBUFFER_SRGB for all FBOs, so that the sRGB mode is solely controlled by the texture format of the color attachments (e.g. RGBA8 vs SRGB8). This is in line with the behavior of the other backends, and GLES without EXT_sRGB_write_control (and in turn with WebGL 2).
_Note 1_: The "default" framebuffers (onscreen surfaces) are left as is, meaning they're controlled by the FRAMEBUFFER_SRGB flag, because after some experiments, it seems that drivers behave very erratically when asked for SRGB capable …
> [GL] Fix sRGB framebuffer write

- examples/common/nanovg/nanovg_bgfx.cpp
- examples/common/nanovg/nanovg_bgfx.h
The nvgCreateBgfxTexture() helper function is already implemented in the nanovg wrapper library, so its useful to expose this function to the user.
Also expose the NVG_IMAGE_NODELETE flag so this can be passed to the nvgCreateBgfxTexture() function, to indicate that the caller retains ownership of the bgfx texture.
> Expose nvgCreateBgfxTexture() helper function

- examples/common/nanovg/fontstash.h
- examples/common/nanovg/nanovg_bgfx.cpp
I'm compiling these files directly in my own project, so wanted to fix these compiler warnings (as I have them enabled for the rest of my own code)
> Fix compiler warnings for nanovg wrapper 

- src/dxgi.cpp
- src/dxgi.h
- src/renderer_d3d11.cpp
I haven't tested this yet, but putting this up to see if we are okay with this kind of change. Copying the interface is the quickest way to make it work. Windows App SDK comes in a NuGet package and I don't think bringing this in as a dependency is a good idea.
> Add support for Windows App SDK (WinUI 3)

- README.md
I have attempted to make the list of example bgfx projects listed in the README.md file have consistent formatting (each project description paragraph begins with the project/game name and a link to it, plus I have made the image alt text consistent). I have also fixed the two broken image URLs for the games Guild Wars 2 and PeakFinder.
> Make the formatting of example projects consistent in README.md and fix broken image URLs

- tools/shaderc/shaderc_hlsl.cpp
when multi uniforms defined in one line and there are some unused uniforms in that line, like this:
...
uniform float4 cShadowSplits;
uniform float4 cUOffset; uniform float4 cVOffset; uniform float4 cMatDiffColor; uniform float4 cMatEmissiveColor;
uniform float4x4 cModel;
...
cMatDiffColor and cMatEmissiveColor are unused uniforms.
> fix unused uniforms replace

- README.md
- docs/build.rst
- docs/internals.rst
- docs/overview.rst
A minor change to reflect how Apple currently names their software:
• Since 2015 AppleTVs run "tvOS" and since 2019 iPads run "iPadOS", rather than both running iOS.
• Since 2016 Macs run "macOS" rather than "OSX". Since macOS's major version number is incremented for major updates the "X" (10 in Roman numerals) doesn't make sense anymore. "OSX (11+)" reads like a contradiction: "Mac OS version 10 (version 11)"
> Update Apple platform naming in readme

- src/bgfx.cpp
This updates the behaviour of bgfx::init() to ensure that it checks for the BGFX_RESET_FLIP_AFTER_RENDER flag.
> Ensure bgfx::init() respects BGFX_RESET_FLIP_AFTER_RENDER

- tools/shaderc/shaderc_metal.cpp
As documented in [MTLPrimitiveTypePoint](https://developer.apple.com/documentation/metal/mtlprimitivetype/point), not specifying the point size when using the points primitive type is undefined behavior, and results in broken output on Apple silicon devices.
This patch fixes #2822 by having shaderc always emit an extra member to `xlatMtlMain_out` in vertex shaders with a default value of 1. This ensures that a value for the `[[point_size]]` attribute is always present. For example, in `01-cubes`, the output structure becomes:
```cpp
struct xlatMtlMain_out
{
float bgfx_metal_pointSize [[point_size]] = 1;
float4 _entryPointOutput_v_color0 [[user(locn0)]];
float4 gl_Position [[position]];
};
```
Shaders other than vertex are left untouched. Users do not need to change their shader source …
> Fix for #2822 -- points rendering error on Apple silicon

- bindings/bf/bgfx.bf
- bindings/cs/bgfx.cs
- bindings/d/types.d
- bindings/zig/bgfx.zig
- examples/00-helloworld/helloworld.cpp
- include/bgfx/bgfx.h
- include/bgfx/c99/bgfx.h
- include/bgfx/defines.h
- scripts/bgfx.idl
- src/bgfx.cpp
- src/bgfx_p.h
- src/config.h
It's hard to recognize the debug text on iPhone with retina display . See https://github.com/bkaradzic/bgfx/discussions/2863
This patch introduce `scaleDebug` in `Init::Resolution` strcuture, so we can scale the debug text 2x larger or more.
> Larger debug text for retina display

- src/glcontext_egl.cpp
I require support for headless rendering in order to conduct graphic unit tests on Ubuntu headless machines. 
This solution works on both headless and non-headless machines, regardless of whether they have a GPU or not. 
In cases where a GPU is not available, it should utilize the Mesa LLVMpipe software rendering approach along with the xvfb-run command.
> Support OpenGL on EGL and allow headless context creation

- src/renderer_d3d12.cpp
The D3D12 `clear` function is not passing the given `_rect` to `frameBuffer.clear`. This unexpectedly causes the entire framebuffer to be cleared when `m_fbh` is valid and a rect is given.
This change fixes the issue by passing the given `_rect` and associated `_num` args to `frameBuffer.clear` when `m_fbh` is valid.
> Fix D3D12 clear rect not being passed to `frameBuffer.clear`

- src/glcontext_egl.cpp
On Linux machines where the xxx-dev packages are not installed, the libEGL.so symlink is not available.
> Fixed EGL library name on Linux

- src/renderer_mtl.mm
This is a fix for https://github.com/bkaradzic/bgfx/issues/3028.
m_backBufferColorMsaa was set when sampleCount > 1, but was never reset when sampleCount became 1 again.
Many other bits of code in the Metal renderer decide what to do by checking m_backBufferColorMsaa, so these would all do the wrong thing if you toggled MSAA on and then back off.
I don't know what I'm doing, I don't know Metal, please check carefully before merging. This is just what worked for me.
> Fix toggling MSAA on Metal.

- src/renderer_mtl.mm
This broke rendering to MSAA framebuffers.
> Metal: Fix framebuffer hash ignoring sampleCount

- src/renderer_vk.cpp
- src/renderer_vk.h
This fixes the outstanding problems mentioned in #2416. I do not really know C++ so tips how to determine wl_surface dynamically are welcome.
In order to test this, `--with-sdl --with-wayland` needs to be added to makefile line 116.
> Fix Vulkan renderer on wayland

- bindings/bf/bgfx.bf
- bindings/cs/bgfx.cs
- bindings/d/package.d
- bindings/zig/bgfx.zig
- include/bgfx/defines.h
- scripts/bgfx.idl
- src/renderer_d3d11.cpp
- src/renderer_d3d12.cpp
- src/renderer_gl.cpp
- src/renderer_mtl.mm
- src/renderer_vk.cpp
- tools/shaderc/shaderc.cpp
Added a new capability to check for PrimitiveID support for common backends.
Vulkan backend will generate a validation error if PrimitiveID is used in a fragment shader without enabling the geometry shader feature that this built-in is dependent on.
It's important to mention that this won't imply that BGFX supports geometry shaders in any way or form.
> Added a new capability to check for PrimitiveID support

- src/renderer_vk.cpp
This fixes an issue mainly with SDL2 (and maybe other backends) where a Metal layer has to be strictly created by SDL2, and it won't work with Metal layers created outside of its context.
> Fixed creating MoltenVk surface with agnostic backends such as SDL2

- src/renderer_d3d11.cpp
Crashes when trying to create the depth stensil texture with 0x0 in headless initialization.
> Fix an issue where initializing DX11 headless would cause a crash.

- src/glimports.h
When compiling on Linux with BGFX_OPENGLES_VERSION=20 (or any version less then 30), duplicate import of certain functions occurs due to the active BGFX_USE_GL_DYNAMIC_LIB flag during the Linux build process.
> Fixed duplicate import of functions on Linux using gles20

- src/renderer_d3d12.cpp
D3D12 dynamic texture array update had an attempted fix in commit da9e2f0, but it was missing one line of code to make it work, leaving the `layer` variable unused. A subsequent commit cleaned up the unused variable. This pull request restores that fix, and uses the `layer` variable by doing the same the D3D11 renderer does.
Additionally pull request #3026 fixed a loop variable over texture sides from `uint8_t` to `uint16_t`. In the same method there's an identical loop with the same issue, and I also fixed that one.
> Fix D3D12 dynamic texture array update

- scripts/genie.lua
The issue for this PR is tracked here,
https://github.com/bkaradzic/bgfx/issues/3183
This PR adds the correct SONAME for the target dynamic libraries for Android so the dynamic linker can search the default paths for shared libraries instead of a fixed path.
Below is the output from readelf showing correct embedding of SONAME.
> [garethf@fedora bgfx]$ ls -l .build/android-arm64/bin/*.so
-rwxr-xr-x. 1 garethf garethf  5469048 Oct 16 15:55 .build/android-arm64/bin/libbgfx-shared-libDebug.so
-rwxr-xr-x. 1 garethf garethf  7742072 Oct 16 15:56 .build/android-arm64/bin/libbgfx-shared-libRelease.so
-rwxr-xr-x. 1 garethf garethf 11408680 Oct 16 15:55 .build/android-arm64/bin/libexample-17-drawstressDebug.so
-rwxr-xr-x. 1 garethf garethf  2912776 Oct 16 15:56 …
> Small fix on soname defining on ldflags for Android examples.

- src/dxgi.cpp
Fix access violation in headless mode during bgfx::shutdown(). This pointer is usually set by the SwapChainPanel which doesn't exist in headless mode.
Tested in local build of my project. It was simple enough I did not test with the example projects.
> Check nativeWindow pointer before dereferencing

- src/renderer_gl.cpp
The new Google Pixel 8 device supports maxTextureSize of 65535. The current implementation sets this value to 0 and lets crash my app. With the cast to uint32t the app works correctly again.
> fixed wrong cast uint16t to uint32t

- examples/common/font/font_manager.cpp
Kerning is now also scaled with the scaled child font when using SDF fonts. In examples/common/font_manager.cpp kerning was not considering scale of the child font, always using kerning offset of the master font. When scaling SDF font down it visibly too large. 
Look at the pair "Yo" in "You" in example11 before the fix:
After the fix
> Fix kerning for SDF scaled fonts in font_manager.cpp

- src/renderer_d3d12.cpp
When `stream.m_startVertex` is not 0 we target a position past the start of the buffer, so `BufferLocation + SizeInBytes` will be past the end of the buffer, which the debug layer will complaining about.
With this fix we're only creating a view for the part of the buffer we actually need to access.
It will be good if somebody with D3D12 experience can verify my assumptions here. Also, I'm not sure the same issue will be present in any other location, but I can confirm with this fix in place my game doesn't throw more validation errors (about this specifically, of course) and everything seems to work fine.
> Fix D3D12 VBV reading size

- src/renderer_d3d12.cpp
DX12 backend is ignoring a user's DX12 device passed trough Init::PlatformData::context
> Fix DX12 backend ignoring Init::PlatformData::context

- bindings/d/package.d
- scripts/bindings-d.lua
I have no idea why it still shows the 9 commits you already merged, but the last 2 are the new ones. Apparently I have no idea how Git works... :')
Changes:
1. I fixed a platform-specific mangling error caused by
a. C++ Itanium mangling distinguishing between `long` and `long long`; and
b. the definition of (`u`)`int64_t` arbitrarily being either `long` or `long long`.
2. D function binding generation now uses the improved BindBC-Common API (0.1.0 -> 0.1.1), which is nearly identical while also a lot more extensible for me, and approachable for others.
> D bindings: fix mangling error, use improved BindBC-Common API

- tools/shaderc/shaderc.cpp
fix compute shader emitting pssl preamble when target shader type is _not_ PSSL
> Fix incorrect psslShaderPreamble in compute shader

- examples/common/nanovg/nanovg_bgfx.cpp
Flush the nanovg draw commands whenever the next draw would overflow the uint16_t index type.
Additionally added a bunch of BX_ASSERT (which don't get compiled into release builds) to prevent more bugs along these lines.
I think that, at least given the way things work, this should be a nanovg-bgfx-specific patch, and not a nanovg patch. Nanovg takes a different approach, without index buffers:
https://github.com/memononen/nanovg/blob/f93799c078fa11ed61c078c65a53914c8782c00b/src/nanovg_gl.h#L1029-L1030: 
```cpp
for (i = 0; i < npaths; i++)
glDrawArrays(GL_TRIANGLE_FAN, paths[i].fillOffset, paths[i].fillCount);
```
Therefore, nanovg never suffered this issue, as there were no indices to overflow.
---
Demo with a lot of content (example code not modified in this PR):
Whoop whoop! It took 6 …
> Fixes #1671 and Fixes #1139.

- bindings/d/package.d
- scripts/bgfx.idl
- scripts/bindings-d.lua
- Fixed `c_uint64` being generated as `uc_int64` at random, due to non-deterministic hash-map iteration ordering in Lua.
- Added 2 missing default arguments to `bgfx.idl`.
- Re-generated bindings with new `bgfx.idl`.
> Fix random, erroneous D binding type generation; add missing IDL defaults

- src/renderer_mtl.mm
Fixes metal texture/buffer binding when the same resource is bound to both (vertex and fragment) stages
https://github.com/bkaradzic/bgfx/issues/3024
> Fixes metal texture/buffer binding issue

- src/renderer_d3d12.cpp
Tested via bgfx.cmake using MSVC's `clang-cl.exe` as `CMAKE_C_COMPILER` and `CMAKE_CXX_COMPILER`
> Minor changes to support Clang on Windows

- src/bgfx_p.h
`calcNumMips` function was calculating often wrong number of mipmaps for textures whose dimensions are not power of 2 such as 96x96; Apparently this is not an issue in Vulkan and probably others(IMHO is bad), but Metal seems to complain about it:
```
-[MTLTextureDescriptorInternal validateWithDevice:]:1357: failed assertion `Texture Descriptor Validation
MTLTextureDescriptor requests 8 mipmap levels, but the dimensions (96, 96, 1) can only support a maxiumum of 7 levels
'
```
I introduced `floorLog2` function in `bx` so now this function can use it instead of `ceilLog2`, which works properly for all texture dimensions.
PS: This PR might fail checks because it might not be using the updated `bx`: https://github.com/bkaradzic/bx/pull/314
> Fixed calcNumMips for non-power-of-2 texture dimensions

- src/bgfx.cpp
- src/bgfx_p.h
- src/renderer_d3d12.cpp
This fixes https://github.com/bkaradzic/bgfx/issues/3176 and the other intermittent questions about this problem.
This way of runtime checking the windows build is the least ugly/hacky that I could find (and yet, it's still awful).
I only tested on win11 build 22621. If we think tests on other versions or builds are necessary I can try to make some VMs.
> Fix D3D12 debug crash due to validation layers SDK bug

- src/renderer_gl.cpp
In case of OpenGL ES another versioning is used for the compute shader compiler.
> Support compute shaders for OpenGLES 3.1 by injecting a proper version.

- examples/09-hdr/hdr.cpp
- examples/33-pom/pom.cpp
- src/bgfx_p.h
- src/shader_dxbc.cpp
Use `bx::bit_cast()` where appropriate for type punning, and applying packed struct for arrays when necessary.
`bx::bit_cast()` is introduced in bkaradzic/bx#313 to address the similar issue of type punning in `bx` (bkaradzic/bx#312).
~This PR also uses `reinterpret_cast` for direct `void*` translations for integer handles.~
~Within `renderer_vk.cpp`, we remove the union when casting from void* to xcb_window_t, it isn't necessary.~
> Make use of bx::bit_cast

- src/renderer_gl.cpp
I've been having some issues when restarting BGFX using `bgfx::shutdown()` and `bgfx::init()`. It seems that some vertex attributes are disabled when they shouldn't be. I think this is because the following static variables are not reset:
- s_currentlyEnabledVertexAttribArrays
- s_vertexAttribArraysPendingDisable
- s_vertexAttribArraysPendingEnable
This change just resets these back to zero when initializing.
> Fix vertex attributes having incorrect state when restarting BGFX

- bindings/d/package.d
- scripts/bindings-d.lua
These functions heretofore were unmarked as the result of an oversight. This change doesn't affect backwards-compatibility.
> D bindings: Mark enum conversion functions `nothrow @nogc pure @safe`

- README.md
As of game version 4.0.0 (released in March 2024), Crypt of the NecroDancer's custom engine uses bgfx for rendering on Windows (D3D11), macOS (Metal), Linux (OpenGL), Nintendo Switch (Vulkan) and PlayStation 4 (GNM).
> Added Crypt of the NecroDancer to README

- README.md
Added a description of the Tomb4Plus project which added bgfx support to replace its legacy Direct3D in the version 0.2 release.
> Added #madewithbgfx entry for Tomb4Plus

- examples/common/bgfx_utils.cpp
Fixes possible concurrency issue - makes code usable in a multithreaded environment. imageReleasCb releases imageContainer after bgfx::createTexture...() is called. If bgfx::frame() is called from another thread, the release can happen before imageContainer is used in bgfx::calcTextureSize(), leading to a crash. Although loadTexture() is not used in multithreaded environment in the examples, calling bgfx::calcTextureSize() before bgfx::createTexture...() is a better reference for users.
> Examples: change order of calls in loadTexture()

- src/glcontext_html5.cpp
Fixes compile error:
```
glcontext_html5.cpp:74:45: error: cast from pointer to smaller type
'EMSCRIPTEN_WEBGL_CONTEXT_HANDLE' (aka 'int') loses information
74 |                 EMSCRIPTEN_WEBGL_CONTEXT_HANDLE context =
reinterpret_cast<EMSCRIPTEN_WEBGL_CONTEXT_HANDLE>(g_platformData.context);
|
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```
> Fixes Emscripten wasm64 compile error in `glcontext_html5.cpp`.

- src/renderer_mtl.mm
A lot of the warnings could be silenced by doing what Apple suggests: using the `@available` check at the code. However, I agree that readability increases if you name the feature you are testing for, instead of just random-looking version number checks.
Examples still work.
> Restore support for older macOS/iOS version. Determine features at init, and use at runtime.

- docs/bgfx.rst
- include/bgfx/bgfx.h
included BGFX_TEXTURE_* description and explicit reference to them when describing createFrameBuffer functions
> Changes to API reference

- tools/shaderc/shaderc_hlsl.cpp
Fixes "error: 'MAKEFOURCC' was not declared in this scope", when compiling with mingw64. 
The macro (in the bx library) is slightly different from the one found in the system header <mmsyscom.h> (which isn't included in the source), but with values under a byte, the result is the same.
> use BX_MAKEFOURCC in shaderc_hlsl.cpp

- src/shader_spirv.cpp
Allows compiling with the conformant preprocessor on MSVC.
> Support /Zc:preprocessor on MSVC for standard compliant preprocessor.

- examples/common/entry/dialog.cpp
- examples/common/entry/entry_sdl.cpp
- include/bgfx/embedded_shader.h
- src/bgfx.cpp
- src/config.h
- src/renderer_mtl.h
- src/renderer_mtl.mm
- tools/shaderc/shaderc.cpp
Hello,
This PR adds visionOS support to bgfx. It's the continuation of [this PR](https://github.com/bkaradzic/bx/pull/323) which added support to `bx` library. I've worked on this together with @mani3xis.
Apple Vision uses bgfx in single threaded mode (`BGFX_CONFIG_MULTITHREADED = 0`), but the example framework isn't really working nice with single threaded mode, so there might be some crashes in the examples but it works great when integrated separately.
> feat: add visionOS support

- src/dxgi.cpp
when my computer have more than 4 gpus, it's break on close when call `DX_RELEASE(m_factory, 0)` at function `Dxgi::shutdown()`
because there is an `AdapterI` object leak if gpu count more than `BX_COUNTOF(_caps.gpu)`, it's should compare first then call `EnumAdapters`
fix #3305
> Fix adapter object leak when there are more than 4 graphics cards

- src/renderer_vk.cpp
Constructed this together with @pezcode.
This very simple change fixes the issue on my device.
Summary:
- my device made a swapchain of 2 images.
- bgfx has by default a max frame latency of 3; so 3 frames in flight.
- there is therefore missing one semaphore to have enough for the 3 frames in flight.
This fixes #3302 and replaces #3303.
> Make the semaphore pool larger, such that there are enough for any number of swapchain images AND frames in flight.

- src/renderer_gl.cpp
Fixes GLSL shader compile errors due to wrong `#version 120` instead of `#version 130`.
Before setting the version the following checks are performed:
```c++
const bool usesVertexID = true
&& !s_extension[Extension::EXT_gpu_shader4].m_supported
&& !bx::findIdentifierMatch(code, "gl_VertexID").isEmpty()
;
...
const bool usesGpuShader4 = true
&& s_extension[Extension::EXT_gpu_shader4].m_supported
&& !bx::findIdentifierMatch(code, s_EXT_gpu_shader4).isEmpty()
;
```
So if `s_extension[Extension::EXT_gpu_shader4].m_supported` evaluates to `true` and we use a shader that only uses `gl_VertexID` we will get `usesVertexID=false` and `usesGpuShader4=true`. 
This leads to the version not recognizing that version `130` is necessary (https://registry.khronos.org/OpenGL-Refpages/gl4/html/gl_VertexID.xh …
> Use correct GLSL shader version if onyl gl_VertexID is used

- include/bgfx/embedded_shader.h
- src/renderer_vk.cpp
I have a fully working version of bgfx running on the Nintendo Switch, rendering via Vulkan. Unfortunately due to the licensing of the Switch SDK I have to be careful of what code I can publish. This is the first step, sharing a little bit of code that is not closely tied to Nintendo.
This works together with https://github.com/bkaradzic/bx/pull/332.
> Minimal changes for Vulkan support on NX.

- examples/common/entry/entry_sdl.cpp
Running into 3 issues with example entry's SDL2 implementation.
1) SDL2's concept of GameController is a like a PS or Xbox controller, two sticks, four face buttons, etc. These are the same as the bgfx example's Gamepad. SDL also has a concept of Joystick, which could be anything, like a flight stick. Game Controllers are implemented by these lower level joysticks.
Entry SDL gets duplicate events, for both controller and the joystick implementing it. Game controller buttons are remapped to bgfx gamepad, but joystick buttons are not. This causes joystick events to produce incorrect button presses.
Additionally, the joystick z-axis behaves differently than game controller or bgfx gamepad. With at-rest value being negative, not zero.
Due to all of this, it seems like the best approach would …
> Fixing issues with controller in entry_sdl.cpp, introduces change in behavior.

- examples/common/imgui/imgui.cpp
ImGui changed their mod key enum names. They weren't changed here probably due to not testing with USE_ENTRY 1
> Change ImGuiKey_Mod* to new names ImGuiMod_*

- src/renderer_mtl.mm
VisionOS SDK was introduced in xcode 15.2.
xcode 15.0, 15.1 do not have the visionOS platform defined. Additionally, if you use a different llvm such as llvm 17 or 18 from homebrew, the platform might not be defined even when using xocde 15.2 or newer.
* Fixes #3314
> Fix issue with visionOS not being defined

- src/renderer_mtl.h
- src/renderer_mtl.mm
This PR partially fixes issues with bgfx rendering on Apple Vision Pro devices. It aims to fix issues described in this Tweet: https://x.com/o_kwasniewski/status/1811313113527992391
Here is the outline of what this PR is doing: 
- Correctly calculate and set the viewports for each eye
- Retrieve configuration `layer_renderer`
- Set Vertex Amplification to make both eyes see the content. (MRT - multiple render targets)
- Fixes issues with frame rendering function calls (now it's following Apple docs)
- Properly sets fields on renderPassDescriptor
- Warns users that `BFGX does not support .dedicated` layout at this point
> fix: properly set viewports and render targets for Apple Vision Pro

- include/bgfx/bgfx.h
Some minor fixes to the Doxygen comments in `bgfx.h`
> fix: Doxygen warnings

- src/renderer_mtl.mm
This PR fixes the last issue with Apple Vision Pro rendering on a real device.
Note: While reviewing, look only at this commit: https://github.com/bkaradzic/bgfx/pull/3326/commits/b83ca5e3ce99b79599d5e92c140536a51dc5d29d another one has already open PR (#3325)
Currently, when we don't attach the device anchor to the drawable (`cp_drawable_set_device_anchor`) the drawables are not presented on the device. To retrieve the device anchor we need to do following things: 
1. Initalize a new world tracking provider: 
```cpp
ar_world_tracking_configuration_t config = ar_world_tracking_configuration_create();
world_tracking = ar_world_tracking_provider_create(config);
```
2. Start an AR session with this provider
```cpp
ar_session = ar_session_create();
auto data_providers = …
```
> Fix: add world tracking on Apple Vision Pro for drawables to be visible

- examples/common/entry/entry_android.cpp
Fixes #3333 
Since the android entry is very close to android samples, the changes were heavily inspired by https://github.com/android/ndk-samples/pull/1008
Tested with https://github.com/gsfare/bgfx-android-examples on a pixel 7 pro with NDK r26.
Successfully compiles with r27.
> Replace ALooper_pollAll with ALooper_pollOnce

- src/glcontext_egl.cpp
Release EGL's per-thread resources before unloading the EGL library to avoid a potential crash when the render thread is terminated.
> egl: Release per-thread resources before unloading

- src/renderer_mtl.h
- src/renderer_mtl.mm
This uses the type of `nwh` to determine whether to implement immersive rendering through Compositor Services, or fall back to standard Metal rendering with CAMetalLayer
Opening this up for review as @okwasniewski has kindly begun trying out the changes
> feat: optional immersive rendering in visionOS

- src/renderer_mtl.mm
This PR fixes visionOS 1.2 build errors. 
I've checked the previous PR on visionOS 2.0 (which supports MTKView) but 1.2 doesn't, causing a build error. 
Everything still works after this change, it's just not trying to reference MTKView anymore. 
Screenshot from Babylon Native flat rendering integration.
> fix: visionOS 1.2 build errors

- src/renderer_d3d12.cpp
If querying the debug1 interface fails, don't attempt to release it.
> Fix a crash in renderer_d3d12.cpp

- examples/common/entry/entry_glfw.cpp
- examples/common/entry/entry_sdl.cpp
- examples/common/example-glue.cpp
- src/glcontext_egl.cpp
- src/glcontext_egl.h
- src/renderer_vk.cpp
So, this fixes what #1679 should have done in the first place.
Summary: 
- The creation of a `wl_egl_window` is only necessary when working with OpenGL. Creating that under Vulkan is plain wrong.
- In this PR, the EGL context now creates this `wl_egl_window` when the `NativeWindowHandleType` is set to `Wayland`.
- This PR reverts the hack in the Vulkan renderer which extracts the original `wl_surface` out of an otherwise-unused `wl_egl_surface`.
- This PR adds the window-resize glue code required to keep properly rendering, when EGL is using a Wayland window.
- These changes clean up and unify the initialization of bgfx in terms of setting the `ndh` and `nwh` in `bgfx::PlatformData`.
This PR was constructed after a lot of reading and carefully examining what exactly SDL2 does when you ask …
> Properly support Wayland under EGL and Vulkan.

- src/renderer_vk.cpp
- src/renderer_vk.h
This change was developed using publicly available information found in Vulkan headers and official documentation. No proprietary NX resources were used.
This is a smaller alternative to #3356 based on comments in that PR.
> Improve NX Vulkan support.

- examples/common/entry/entry_sdl.cpp
- scripts/genie.lua
- src/glcontext_egl.cpp
- src/glcontext_egl.h
Follow-up on #3358. Tested with SilverNode and the examples under both Vulkan (irrelevant) and EGL (relevant).
Confirmed that libwayland-egl.so is no longer linked:
```cpp
❯ ldd .build/linux64_gcc/bin/example-06-bumpRelease
linux-vdso.so.1 (0x00007f9005562000)
libSDL2-2.0.so.0 => /lib64/libSDL2-2.0.so.0 (0x00007f9005373000)
libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f9005000000)
libm.so.6 => /lib64/libm.so.6 (0x00007f900528f000)
libmvec.so.1 => /lib64/libmvec.so.1 (0x00007f9004f06000)
libc.so.6 => /lib64/libc.so.6 (0x00007f9004d15000)
/lib64/ld-linux-x86-64.so.2 (0x00007f9005564000)
libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f9004ce7000)
```
> Dynamically load libwayland-egl.so.1 when dealing with Wayland.

- src/renderer_vk.cpp
Potentially fixes #3227. At least on my machine, aggressively resizing the window no longer causes a device lost. For my setup, this change is an improvement. The idea is taken from here: https://github.com/mpv-player/mpv/issues/8360#issuecomment-1486705836
> Insert vkDeviceWaitIdle to prevent VK_DEVICE_LOST.

- makefile
Copy-paste error in makefile: `linux-clang-debug64`-target was invoking GCC build instead.
> Fixed clang-debug target trying to build with gcc.

- examples/common/entry/entry_noop.cpp
_handle no longer exists in getNativeWindowHandleType so this would not compile
> Fix compiling entry_noop

- src/dxgi.cpp
DXGI_SWAP_CHAIN_DESC1 has an additional 'Scaling' option that is set in bgfx's SwapChainDesc but is not used in DXGI_SWAP_CHAIN_DESC. 
This change uses DXGI_SWAP_CHAIN_DESC1 if available and uses DXGI_SWAP_CHAIN_DESC otherwise.
> Use DXGI_SWAP_CHAIN_DESC1 for creating swap chain if available for additional scaling options

- src/bgfx.cpp
When rendering 1275 drawcalls with heavy uniform use without discarding textures and uniforms, I was having terrible performance, worse than when discarding.
While investigating, I realized that when BGFX calls `rendererUpdateUniforms`, it always had `_begin` set to 0.
I looked at how `EncoderImpl::dispatch` always sets the `m_uniformBegin` to `m_uniformEnd` after each item is added, so I did the same for `EncoderImpl::submit`, and the issue is fixed! I actually have much better performance than when using discards, which is to be expected!
As requested, I tested the examples and they seem to work fine, so I believe there should be no side effects!
> Fix: Fix Uniform buffer doing too many iterations when updating renderer uniforms

- examples/common/entry/entry.cpp
- examples/common/entry/entry_sdl.cpp
- src/renderer_vk.cpp
- src/renderer_vk.h
Should fix:
- #3242
- #3227, but properly. (I left the `vkDeviceWaitIdle` in to be sure).
- https://discord.com/channels/712512073522872352/1294399114787946496
The SDL entry code had a bug where the user resizing the window, triggers a window resize event, which calls SDL_SetWindowSize(), which triggers a window size. This loop reverted the window size to the previous size.
To fix the main issue with the Vulkan backend, I clamp the swapchain size to what the driver allows. I set the `m_resolution` of the swapchain and framebuffer to the actual result after clamping, instead of what the user requests. This way, one of the next frames, when the user's windowing code catches up with the resize, both the requested resolution and the Vulkan-allowed resolution match, and both are again in sync. …
> Fix Vulkan swapchain invalidation issue.

- src/renderer_mtl.mm
> [Metal] Always set the swizzle of the render target.

- src/renderer_gl.cpp
Fixes https://github.com/bkaradzic/bgfx/issues/3401
> Fix only one frame rendered in mobile opengles with intermediate frame buffer

- src/renderer_vk.cpp
I was still getting some VK_DEVICE_LOST crashes and this fixes it. Followed some changes from https://github.com/bkaradzic/bgfx/commit/01af383a6cc90977138d70ab7d9c46a2a0d9b08a#diff-4fe4dacbf31bf95719870316660d20e1deca6ebbfa3f39c6b2b8b0b302d629f9
@mcourteaux Does this look right to you?
> Another fix for crashing with VK_DEVICE_LOST

- src/glcontext_html5.cpp
This PR fixes a compile error for `wasm` that is related to the TinySTL refactors
> Fix wasm tinystl compile error

- README.md
Updates the Android platform support description in README to be more clear 
for Android developers.
- Changed `Android (14+)` to `Android (4.0+) - API 14 or later`
The previous notation "14+" could be misinterpreted by Android developers as:
- Android 14.0 (API 34)
- API level 14 (Android 4.0)
This change removes ambiguity by explicitly stating both the Android version 
and API level.
- No functional changes, documentation update only
> docs: improve Android platform requirement clarity in README

- .github/workflows/file_format.py
- .pre-commit-config.yaml
This PR adds a script for file formatting, set up to be used with [pre-commit](https://pre-commit.com/), and formats the files in this repo using the script.
- The formatting script is cross-platform, works on Windows, MacOS, and Linux.
- The formatting script can run without installing any OS-level dependencies, except for Python. Once Python is installed you can install `pre-commit` via `pip install pre-commit`. Then `pre-commit run --all-files` in the repo to run.
- The formatting script can run automatically on changed files when making a commit using Git's pre-commit hooks feature, if you opt-in via `pre-commit install` in the repo.
- Due to the `static_checks.yml` file, the formatting script runs automatically on PRs via GitHub Actions CI checks.
The script ensures text files do not …
> Add a file formatting script for pre-commit

- src/renderer_vk.cpp
- src/renderer_vk.h
Fixes #3418 properly, and replaces the patch in 72f9b8b51.
CC @synaptor.
> Fix TextVideoMemBlitter staging buffer issue.

- src/config.h
- src/renderer_vk.cpp
- src/renderer_vk.h
Ideas for future: 
- Have a field in the bgfx::Stats that indicates how many allocations are just dangling around in the cache.
- Have a clear cache call in the API. That's useful to react to system requests to free memory, like on Android.
Please review:
- Is this default setting of 128 MB sane? Is this fine for Mobile devices?
> Vulkan memory allocation LRU cache

- src/bgfx_p.h
Currently, if user never calls `setPaletteColor`, `m_submit->m_colorPalette` is never cleared either and contains undefined data. Sampling textures configured with `SAMPLER_*_BORDER` yields weird behavior.
> Initialize color palette at start

- src/glcontext_html5.cpp
EMSCRIPTEN_WEBGL_CONTEXT_HANDLE is 64bit when using MEMORY64 but it's stored as an int 32 bit causing overflow
> [emscripten] Fix MEMORY64 mode

- src/shader_dxbc.cpp
While trying to create a shader in our project I get shader compiler issue each time I try to use f16tof32 function.
After some investigation I found that some DXBC opcode info were incorrect. So I browse HLSL - asm documentation to fix them.
https://learn.microsoft.com/fr-fr/windows/win32/direct3dhlsl/f16tof32--sm5---asm-
As I'm not expert into this part, don't hesitate to notice me or suggest me changes :)
> Fix some DXBC opcode info

- src/renderer_vk.cpp
The original logic fails if the extension is not present:
1. the user specifies Wayland window type
2. the extension is not present (due to RenderDoc disabling Wayland surface creation)
3. bgfx instead attempts X11 surface creation, on a Wayland window.
So, this PR makes sure bgfx doesn't do the flawed 3rd step above: it just gives up. There is no point in trying to create an X11 surface on a Wayland window, or vise-versa.
> Slightly better surface creation logic for Vulkan.

- src/renderer_mtl.mm
* When using the Metal rendering backend and updating the window handle via setPlatformData(), the passed in Metal layer was not stored. Instead, the old window handle (Metal layer) was still used.
* The fix addresses a scenario where two BGFX-backed Metal views on iOS are created and rendering needs to happen either on one view or the other.
* `m_metalLayer` is not cleared/set no `NULL`, only released: https://github.com/bkaradzic/bgfx/blob/23baae9e0010ee03edd8904fc7e176c76f4f8e2c/src/renderer_mtl.mm#L3518
* When `m_metalLayer` is not cleared, the check here fails: https://github.com/bkaradzic/bgfx/blob/23baae9e0010ee03edd8904fc7e176c76f4f8e2c/src/renderer_mtl.mm#L3536
* As a result the new handle is not stored in `m_metalLayer`: …
> Fix for Metal: persist new window handle (Metal layer) when swapping view

- bindings/c3/bgfx.c3
- scripts/bindings-c3.lua
- scripts/genie.lua
Added support to generate the [C3 Lang](https://c3-lang.org) bindings. Tested on windows only. In C3 it looks as follow:
```c
bgfx::set_view_clear(0, (ushort) (bgfx::ClearFlags.COLOR|bgfx::ClearFlags.DEPTH), 0x303030FF, 1.0f, 0);
bgfx::set_view_rect(0, 0, 0, (ushort)ctx.width, (ushort)ctx.height);
bgfx::touch(0);
bgfx::Stats* stats = bgfx::get_stats();
bgfx::dbg_text_image(
(ushort) math::max(stats.textWidth  / 2, 20)-20,
(ushort) math::max(stats.textHeight / 2,  6)-6,
40,
12,
&s_logo,
160
);
bgfx::dbg_text_printf(0, 1, 0x0f, "Color can be changed with ANSI \x1b[9;me\x1b[10;ms\x1b[11;mc\x1b[12;ma\x1b[13;mp\x1b[14;me\x1b[0m code too.");
bgfx::dbg_text_printf(80, 1, 0x0f, "\x1b[;0m    \x1b[;1m    \x1b[; 2m    \x1b[; 3m    \x1b[; 4m    \x1b[; 5m    \x1b[; 6m    \x1b[; 7m    \x1b[0m"); …
```
> Add bindings for C3 Lang

- scripts/shaderc.lua
When I use `clang` version 17 to compile `shaderc`, the resulting `essl`/`glsl` shaders have all constants replaced with the value `(-1.0/0.0)`. Removing `FloatFast` for the `glsl-optimizer` target resolved the issue for me.
```
$input a_position
void main()
{
gl_Postition = vec4(0.0, 0.0, 0.0, 1.0);
}
```
```
precision highp int;
precision highp float;
void main()
{
gl_Position = vec4((-1.0/0.0), (-1.0/0.0), (-1.0/0.0), (-1.0/0.0));
}
```
> Remove FloatFast option for glsl-optimizer

- src/glcontext_egl.cpp
EGL_DISPMANX_WINDOW_T is not defined for modern Raspberry Pi. To fix it you must define a replacement struct, and use raw casting to EGLNativeWindowType
See: https://forum.qt.io/topic/88588/qtbase-compilation-error-with-device-linux-rasp-pi3-g-qeglfskmsgbmwindow-cpp/9 for details of the fix
> Fix Raspberry Pi Build - EGL_DISPMANX_WINDOW_T not defined
